"""Credit card: revolving limit, rate by grade.

Generated by make_bank.py; edit the generator, not this file."""
from decider import flow

from bank.products.credit_card.affordability import cc_affordability
from bank.products.credit_card.limits import cc_limits
from bank.products.credit_card.policy import cc_policy
from bank.products.credit_card.pricing import cc_pricing
from bank.products.credit_card.scorecard import cc_scorecard
from bank.products.credit_card.stress import cc_stress

credit_card = flow(cc_scorecard, cc_policy, cc_pricing, cc_affordability, cc_stress, cc_limits, name="credit_card")
