"""Credit card: revolving limit, rate by grade. Affordability: the instalment at the offered and a stressed rate against disposable income.

Generated by make_bank.py; edit the generator, not this file."""
from decider import flow, param, step


def cc_instalment(requested_amount: float, requested_term: float, cc_monthly_rate: float, cc_monthly_fee: float) -> float:
    return requested_amount * cc_monthly_rate / (1 - (1 + cc_monthly_rate) ** -requested_term) + cc_monthly_fee


def cc_stress_rate(cc_rate: float, buffer: float = param(0.03)) -> float:
    return cc_rate + buffer


def cc_stress_instalment(requested_amount: float, requested_term: float, cc_stress_rate: float) -> float:
    return requested_amount * (cc_stress_rate / 12) / (1 - (1 + cc_stress_rate / 12) ** -requested_term)


def cc_affordable_instalment(disposable_income_buffered: float, share: float = param(0.5)) -> float:
    return max(disposable_income_buffered * share, 0.0)


def cc_instalment_fits(cc_stress_instalment: float, cc_affordable_instalment: float) -> bool:
    return cc_stress_instalment <= cc_affordable_instalment


def cc_max_affordable_amount(cc_affordable_instalment: float, requested_term: float, cc_stress_rate: float) -> float:
    return cc_affordable_instalment * (1 - (1 + cc_stress_rate / 12) ** -requested_term) / (cc_stress_rate / 12)


def cc_dti_band_0(debt_service_ratio: float, lo: float = param(0), hi: float = param(0.2)) -> bool:
    return lo <= debt_service_ratio < hi


def cc_dti_band_1(debt_service_ratio: float, lo: float = param(0.2), hi: float = param(0.35)) -> bool:
    return lo <= debt_service_ratio < hi


def cc_dti_band_2(debt_service_ratio: float, lo: float = param(0.35), hi: float = param(0.5)) -> bool:
    return lo <= debt_service_ratio < hi


def cc_dti_band_3(debt_service_ratio: float, lo: float = param(0.5), hi: float = param(1.0)) -> bool:
    return lo <= debt_service_ratio < hi


def cc_grade_1_share(grade: int, share: float = param(1.0)) -> float:
    return share if grade == 1 else 0.0


def cc_grade_2_share(grade: int, share: float = param(0.85)) -> float:
    return share if grade == 2 else 0.0


def cc_grade_3_share(grade: int, share: float = param(0.7)) -> float:
    return share if grade == 3 else 0.0


def cc_grade_4_share(grade: int, share: float = param(0.55)) -> float:
    return share if grade == 4 else 0.0


def cc_grade_share(cc_grade_1_share: float, cc_grade_2_share: float, cc_grade_3_share: float, cc_grade_4_share: float) -> float:
    return cc_grade_1_share + cc_grade_2_share + cc_grade_3_share + cc_grade_4_share


cc_affordability = flow(
    cc_instalment,
    cc_stress_rate,
    cc_stress_instalment,
    cc_affordable_instalment,
    cc_instalment_fits,
    cc_max_affordable_amount,
    cc_dti_band_0,
    cc_dti_band_1,
    cc_dti_band_2,
    cc_dti_band_3,
    cc_grade_1_share,
    cc_grade_2_share,
    cc_grade_3_share,
    cc_grade_4_share,
    cc_grade_share,
    name="affordability",
)
