"""Credit card: revolving limit, rate by grade. Limits: product caps and the offer.

Generated by make_bank.py; edit the generator, not this file."""
from decider import flow, param, step


def cc_product_cap(grade: int, cap: float = param(150000.0)) -> float:
    return cap * (1.0 if grade <= 2 else 0.6)


def cc_ltv_cap(requested_amount: float) -> float:
    return requested_amount


def cc_income_cap(gross_income: float, multiple: float = param(2.0)) -> float:
    return gross_income * multiple


def cc_max_amount(cc_product_cap: float, cc_ltv_cap: float, cc_income_cap: float, cc_max_affordable_amount: float, cc_grade_share: float) -> float:
    return min(cc_product_cap, cc_ltv_cap, cc_income_cap, cc_max_affordable_amount) * cc_grade_share


@step(output="offer_amount")
def cc_offer_amount(requested_amount: float, cc_max_amount: float, rounding: float = param(500.0)) -> float:
    return max(min(requested_amount, cc_max_amount) // rounding * rounding, 0.0)


@step(output="offer_term")
def cc_offer_term(requested_term: float) -> float:
    return requested_term


@step(output="offer_rate")
def cc_offer_rate(cc_rate: float) -> float:
    return cc_rate


@step(output="monthly_instalment")
def cc_offer_instalment(offer_amount: float, offer_term: float, cc_monthly_rate: float, cc_monthly_fee: float) -> float:
    return offer_amount * cc_monthly_rate / (1 - (1 + cc_monthly_rate) ** -offer_term) + cc_monthly_fee if offer_amount > 0 else 0.0


@step(output="declined")
def cc_declined(cc_policy_declined: bool, cc_instalment_fits: bool, offer_amount: float, minimum: float = param(2000.0)) -> bool:
    return cc_policy_declined or offer_amount < minimum


@step(output="decline_reason")
def cc_decline_reason(cc_policy_reason: str, cc_policy_declined: bool, declined: bool) -> str:
    return cc_policy_reason if cc_policy_declined else ("Offer below the product minimum" if declined else "")


cc_limits = flow(
    cc_product_cap,
    cc_ltv_cap,
    cc_income_cap,
    cc_max_amount,
    cc_offer_amount,
    cc_offer_term,
    cc_offer_rate,
    cc_offer_instalment,
    cc_declined,
    cc_decline_reason,
    name="limits",
)
