"""Credit card: revolving limit, rate by grade. Policy rules: each rule declines an application for one reason.

Generated by make_bank.py; edit the generator, not this file."""
from decider import flow, param, step


@step(output="cc_min_age")
def cc_min_age(age: float, limit: float = param(18.0)) -> bool:
    """Under the minimum age."""
    return age < limit


@step(output="cc_max_age")
def cc_max_age(age: float, limit: float = param(70.0)) -> bool:
    """Over the maximum age at maturity."""
    return age > limit


@step(output="cc_min_gross_income")
def cc_min_gross_income(gross_income: float, limit: float = param(4500.0)) -> bool:
    """Income below the minimum."""
    return gross_income < limit


@step(output="cc_min_net_income")
def cc_min_net_income(net_income: float, limit: float = param(3500.0)) -> bool:
    """Net income below the minimum."""
    return net_income < limit


@step(output="cc_max_debt_service")
def cc_max_debt_service(debt_service_ratio: float, limit: float = param(0.45)) -> bool:
    """Debt repayments too high."""
    return debt_service_ratio > limit


@step(output="cc_min_bureau")
def cc_min_bureau(bureau_score: float, limit: float = param(560.0)) -> bool:
    """Bureau score too low."""
    return bureau_score < limit


@step(output="cc_max_enquiries")
def cc_max_enquiries(enquiries_6m: float, limit: float = param(7.2)) -> bool:
    """Too many recent credit enquiries."""
    return enquiries_6m > limit


@step(output="cc_max_missed")
def cc_max_missed(missed_payments_12m: float, limit: float = param(3.0)) -> bool:
    """Missed payments in the last year."""
    return missed_payments_12m > limit


@step(output="cc_max_judgements")
def cc_max_judgements(judgements: float, limit: float = param(0.0)) -> bool:
    """Judgement on record."""
    return judgements > limit


@step(output="cc_min_employment")
def cc_min_employment(months_employed: float, limit: float = param(3.3)) -> bool:
    """Employed for too short a time."""
    return months_employed < limit


@step(output="cc_min_address")
def cc_min_address(months_at_address: float, limit: float = param(0.9)) -> bool:
    """Address too recent."""
    return months_at_address < limit


@step(output="cc_max_utilisation")
def cc_max_utilisation(card_utilisation: float, limit: float = param(0.85)) -> bool:
    """Card limits nearly exhausted."""
    return card_utilisation > limit


@step(output="cc_max_dependants")
def cc_max_dependants(dependants: float, limit: float = param(8.8)) -> bool:
    """Household too large for declared income."""
    return dependants > limit


@step(output="cc_min_disposable")
def cc_min_disposable(disposable_income: float, limit: float = param(1350.0)) -> bool:
    """Too little left each month."""
    return disposable_income < limit


@step(output="cc_max_requested")
def cc_max_requested(requested_amount: float, limit: float = param(315000.0)) -> bool:
    """Amount above the product maximum."""
    return requested_amount > limit


@step(output="cc_min_requested")
def cc_min_requested(requested_amount: float, limit: float = param(2200.0)) -> bool:
    """Amount below the product minimum."""
    return requested_amount < limit


@step(output="cc_sector_1_max_debt")
def cc_sector_1_max_debt(employer_sector: int, debt_service_ratio: float, limit: float = param(0.36)) -> bool:
    """Debt repayments too high for sector 1."""
    return employer_sector == 1 and debt_service_ratio > limit


@step(output="cc_sector_1_min_score")
def cc_sector_1_min_score(employer_sector: int, bureau_score: float, limit: float = param(650.0)) -> bool:
    """Bureau score too low for sector 1."""
    return employer_sector == 1 and bureau_score < limit


@step(output="cc_sector_1_min_income")
def cc_sector_1_min_income(employer_sector: int, net_income: float, limit: float = param(6750.0)) -> bool:
    """Net income too low for sector 1."""
    return employer_sector == 1 and net_income < limit


@step(output="cc_sector_1_max_loan_to_income")
def cc_sector_1_max_loan_to_income(employer_sector: int, requested_amount_to_gross_income: float, limit: float = param(7.3)) -> bool:
    """Loan too large for income in sector 1."""
    return employer_sector == 1 and requested_amount_to_gross_income > limit


@step(output="cc_sector_2_max_debt")
def cc_sector_2_max_debt(employer_sector: int, debt_service_ratio: float, limit: float = param(0.53)) -> bool:
    """Debt repayments too high for sector 2."""
    return employer_sector == 2 and debt_service_ratio > limit


@step(output="cc_sector_2_min_score")
def cc_sector_2_min_score(employer_sector: int, bureau_score: float, limit: float = param(655.0)) -> bool:
    """Bureau score too low for sector 2."""
    return employer_sector == 2 and bureau_score < limit


@step(output="cc_sector_2_min_income")
def cc_sector_2_min_income(employer_sector: int, net_income: float, limit: float = param(5000.0)) -> bool:
    """Net income too low for sector 2."""
    return employer_sector == 2 and net_income < limit


@step(output="cc_sector_2_max_loan_to_income")
def cc_sector_2_max_loan_to_income(employer_sector: int, requested_amount_to_gross_income: float, limit: float = param(4.8)) -> bool:
    """Loan too large for income in sector 2."""
    return employer_sector == 2 and requested_amount_to_gross_income > limit


@step(output="cc_sector_3_max_debt")
def cc_sector_3_max_debt(employer_sector: int, debt_service_ratio: float, limit: float = param(0.4)) -> bool:
    """Debt repayments too high for sector 3."""
    return employer_sector == 3 and debt_service_ratio > limit


@step(output="cc_sector_3_min_score")
def cc_sector_3_min_score(employer_sector: int, bureau_score: float, limit: float = param(625.0)) -> bool:
    """Bureau score too low for sector 3."""
    return employer_sector == 3 and bureau_score < limit


@step(output="cc_sector_3_min_income")
def cc_sector_3_min_income(employer_sector: int, net_income: float, limit: float = param(7750.0)) -> bool:
    """Net income too low for sector 3."""
    return employer_sector == 3 and net_income < limit


@step(output="cc_sector_3_max_loan_to_income")
def cc_sector_3_max_loan_to_income(employer_sector: int, requested_amount_to_gross_income: float, limit: float = param(3.5)) -> bool:
    """Loan too large for income in sector 3."""
    return employer_sector == 3 and requested_amount_to_gross_income > limit


@step(output="cc_sector_4_max_debt")
def cc_sector_4_max_debt(employer_sector: int, debt_service_ratio: float, limit: float = param(0.31)) -> bool:
    """Debt repayments too high for sector 4."""
    return employer_sector == 4 and debt_service_ratio > limit


@step(output="cc_sector_4_min_score")
def cc_sector_4_min_score(employer_sector: int, bureau_score: float, limit: float = param(640.0)) -> bool:
    """Bureau score too low for sector 4."""
    return employer_sector == 4 and bureau_score < limit


@step(output="cc_sector_4_min_income")
def cc_sector_4_min_income(employer_sector: int, net_income: float, limit: float = param(7500.0)) -> bool:
    """Net income too low for sector 4."""
    return employer_sector == 4 and net_income < limit


@step(output="cc_sector_4_max_loan_to_income")
def cc_sector_4_max_loan_to_income(employer_sector: int, requested_amount_to_gross_income: float, limit: float = param(10.4)) -> bool:
    """Loan too large for income in sector 4."""
    return employer_sector == 4 and requested_amount_to_gross_income > limit


@step(output="cc_sector_5_max_debt")
def cc_sector_5_max_debt(employer_sector: int, debt_service_ratio: float, limit: float = param(0.54)) -> bool:
    """Debt repayments too high for sector 5."""
    return employer_sector == 5 and debt_service_ratio > limit


@step(output="cc_sector_5_min_score")
def cc_sector_5_min_score(employer_sector: int, bureau_score: float, limit: float = param(645.0)) -> bool:
    """Bureau score too low for sector 5."""
    return employer_sector == 5 and bureau_score < limit


@step(output="cc_sector_5_min_income")
def cc_sector_5_min_income(employer_sector: int, net_income: float, limit: float = param(8750.0)) -> bool:
    """Net income too low for sector 5."""
    return employer_sector == 5 and net_income < limit


@step(output="cc_sector_5_max_loan_to_income")
def cc_sector_5_max_loan_to_income(employer_sector: int, requested_amount_to_gross_income: float, limit: float = param(9.8)) -> bool:
    """Loan too large for income in sector 5."""
    return employer_sector == 5 and requested_amount_to_gross_income > limit


@step(output="cc_sector_6_max_debt")
def cc_sector_6_max_debt(employer_sector: int, debt_service_ratio: float, limit: float = param(0.34)) -> bool:
    """Debt repayments too high for sector 6."""
    return employer_sector == 6 and debt_service_ratio > limit


@step(output="cc_sector_6_min_score")
def cc_sector_6_min_score(employer_sector: int, bureau_score: float, limit: float = param(620.0)) -> bool:
    """Bureau score too low for sector 6."""
    return employer_sector == 6 and bureau_score < limit


@step(output="cc_sector_6_min_income")
def cc_sector_6_min_income(employer_sector: int, net_income: float, limit: float = param(7500.0)) -> bool:
    """Net income too low for sector 6."""
    return employer_sector == 6 and net_income < limit


@step(output="cc_sector_6_max_loan_to_income")
def cc_sector_6_max_loan_to_income(employer_sector: int, requested_amount_to_gross_income: float, limit: float = param(5.8)) -> bool:
    """Loan too large for income in sector 6."""
    return employer_sector == 6 and requested_amount_to_gross_income > limit


@step(output="cc_province_gp_max_debt")
def cc_province_gp_max_debt(province: str, debt_service_ratio: float, limit: float = param(0.47)) -> bool:
    """Debt repayments too high for province GP."""
    return province == 'GP' and debt_service_ratio > limit


@step(output="cc_province_gp_min_score")
def cc_province_gp_min_score(province: str, bureau_score: float, limit: float = param(585.0)) -> bool:
    """Bureau score too low for province GP."""
    return province == 'GP' and bureau_score < limit


@step(output="cc_province_gp_min_income")
def cc_province_gp_min_income(province: str, net_income: float, limit: float = param(6500.0)) -> bool:
    """Net income too low for province GP."""
    return province == 'GP' and net_income < limit


@step(output="cc_province_gp_max_loan_to_income")
def cc_province_gp_max_loan_to_income(province: str, requested_amount_to_gross_income: float, limit: float = param(10.4)) -> bool:
    """Loan too large for income in province GP."""
    return province == 'GP' and requested_amount_to_gross_income > limit


@step(output="cc_province_wc_max_debt")
def cc_province_wc_max_debt(province: str, debt_service_ratio: float, limit: float = param(0.42)) -> bool:
    """Debt repayments too high for province WC."""
    return province == 'WC' and debt_service_ratio > limit


@step(output="cc_province_wc_min_score")
def cc_province_wc_min_score(province: str, bureau_score: float, limit: float = param(600.0)) -> bool:
    """Bureau score too low for province WC."""
    return province == 'WC' and bureau_score < limit


@step(output="cc_province_wc_min_income")
def cc_province_wc_min_income(province: str, net_income: float, limit: float = param(4500.0)) -> bool:
    """Net income too low for province WC."""
    return province == 'WC' and net_income < limit


@step(output="cc_province_wc_max_loan_to_income")
def cc_province_wc_max_loan_to_income(province: str, requested_amount_to_gross_income: float, limit: float = param(7.6)) -> bool:
    """Loan too large for income in province WC."""
    return province == 'WC' and requested_amount_to_gross_income > limit


@step(output="cc_province_kzn_max_debt")
def cc_province_kzn_max_debt(province: str, debt_service_ratio: float, limit: float = param(0.39)) -> bool:
    """Debt repayments too high for province KZN."""
    return province == 'KZN' and debt_service_ratio > limit


@step(output="cc_province_kzn_min_score")
def cc_province_kzn_min_score(province: str, bureau_score: float, limit: float = param(655.0)) -> bool:
    """Bureau score too low for province KZN."""
    return province == 'KZN' and bureau_score < limit


@step(output="cc_province_kzn_min_income")
def cc_province_kzn_min_income(province: str, net_income: float, limit: float = param(8750.0)) -> bool:
    """Net income too low for province KZN."""
    return province == 'KZN' and net_income < limit


@step(output="cc_province_kzn_max_loan_to_income")
def cc_province_kzn_max_loan_to_income(province: str, requested_amount_to_gross_income: float, limit: float = param(10.7)) -> bool:
    """Loan too large for income in province KZN."""
    return province == 'KZN' and requested_amount_to_gross_income > limit


@step(output="cc_province_ec_max_debt")
def cc_province_ec_max_debt(province: str, debt_service_ratio: float, limit: float = param(0.41)) -> bool:
    """Debt repayments too high for province EC."""
    return province == 'EC' and debt_service_ratio > limit


@step(output="cc_province_ec_min_score")
def cc_province_ec_min_score(province: str, bureau_score: float, limit: float = param(575.0)) -> bool:
    """Bureau score too low for province EC."""
    return province == 'EC' and bureau_score < limit


@step(output="cc_province_ec_min_income")
def cc_province_ec_min_income(province: str, net_income: float, limit: float = param(7500.0)) -> bool:
    """Net income too low for province EC."""
    return province == 'EC' and net_income < limit


@step(output="cc_province_ec_max_loan_to_income")
def cc_province_ec_max_loan_to_income(province: str, requested_amount_to_gross_income: float, limit: float = param(9.1)) -> bool:
    """Loan too large for income in province EC."""
    return province == 'EC' and requested_amount_to_gross_income > limit


@step(output="cc_province_fs_max_debt")
def cc_province_fs_max_debt(province: str, debt_service_ratio: float, limit: float = param(0.46)) -> bool:
    """Debt repayments too high for province FS."""
    return province == 'FS' and debt_service_ratio > limit


@step(output="cc_province_fs_min_score")
def cc_province_fs_min_score(province: str, bureau_score: float, limit: float = param(640.0)) -> bool:
    """Bureau score too low for province FS."""
    return province == 'FS' and bureau_score < limit


@step(output="cc_province_fs_min_income")
def cc_province_fs_min_income(province: str, net_income: float, limit: float = param(5500.0)) -> bool:
    """Net income too low for province FS."""
    return province == 'FS' and net_income < limit


@step(output="cc_province_fs_max_loan_to_income")
def cc_province_fs_max_loan_to_income(province: str, requested_amount_to_gross_income: float, limit: float = param(9.7)) -> bool:
    """Loan too large for income in province FS."""
    return province == 'FS' and requested_amount_to_gross_income > limit


@step(output="cc_province_lp_max_debt")
def cc_province_lp_max_debt(province: str, debt_service_ratio: float, limit: float = param(0.39)) -> bool:
    """Debt repayments too high for province LP."""
    return province == 'LP' and debt_service_ratio > limit


@step(output="cc_province_lp_min_score")
def cc_province_lp_min_score(province: str, bureau_score: float, limit: float = param(615.0)) -> bool:
    """Bureau score too low for province LP."""
    return province == 'LP' and bureau_score < limit


@step(output="cc_province_lp_min_income")
def cc_province_lp_min_income(province: str, net_income: float, limit: float = param(6000.0)) -> bool:
    """Net income too low for province LP."""
    return province == 'LP' and net_income < limit


@step(output="cc_province_lp_max_loan_to_income")
def cc_province_lp_max_loan_to_income(province: str, requested_amount_to_gross_income: float, limit: float = param(3.0)) -> bool:
    """Loan too large for income in province LP."""
    return province == 'LP' and requested_amount_to_gross_income > limit


@step(output="cc_province_mp_max_debt")
def cc_province_mp_max_debt(province: str, debt_service_ratio: float, limit: float = param(0.45)) -> bool:
    """Debt repayments too high for province MP."""
    return province == 'MP' and debt_service_ratio > limit


@step(output="cc_province_mp_min_score")
def cc_province_mp_min_score(province: str, bureau_score: float, limit: float = param(650.0)) -> bool:
    """Bureau score too low for province MP."""
    return province == 'MP' and bureau_score < limit


@step(output="cc_province_mp_min_income")
def cc_province_mp_min_income(province: str, net_income: float, limit: float = param(8000.0)) -> bool:
    """Net income too low for province MP."""
    return province == 'MP' and net_income < limit


@step(output="cc_province_mp_max_loan_to_income")
def cc_province_mp_max_loan_to_income(province: str, requested_amount_to_gross_income: float, limit: float = param(8.5)) -> bool:
    """Loan too large for income in province MP."""
    return province == 'MP' and requested_amount_to_gross_income > limit


@step(output="cc_province_nw_max_debt")
def cc_province_nw_max_debt(province: str, debt_service_ratio: float, limit: float = param(0.36)) -> bool:
    """Debt repayments too high for province NW."""
    return province == 'NW' and debt_service_ratio > limit


@step(output="cc_province_nw_min_score")
def cc_province_nw_min_score(province: str, bureau_score: float, limit: float = param(655.0)) -> bool:
    """Bureau score too low for province NW."""
    return province == 'NW' and bureau_score < limit


@step(output="cc_province_nw_min_income")
def cc_province_nw_min_income(province: str, net_income: float, limit: float = param(9000.0)) -> bool:
    """Net income too low for province NW."""
    return province == 'NW' and net_income < limit


@step(output="cc_province_nw_max_loan_to_income")
def cc_province_nw_max_loan_to_income(province: str, requested_amount_to_gross_income: float, limit: float = param(9.1)) -> bool:
    """Loan too large for income in province NW."""
    return province == 'NW' and requested_amount_to_gross_income > limit


@step(output="cc_province_nc_max_debt")
def cc_province_nc_max_debt(province: str, debt_service_ratio: float, limit: float = param(0.33)) -> bool:
    """Debt repayments too high for province NC."""
    return province == 'NC' and debt_service_ratio > limit


@step(output="cc_province_nc_min_score")
def cc_province_nc_min_score(province: str, bureau_score: float, limit: float = param(640.0)) -> bool:
    """Bureau score too low for province NC."""
    return province == 'NC' and bureau_score < limit


@step(output="cc_province_nc_min_income")
def cc_province_nc_min_income(province: str, net_income: float, limit: float = param(9000.0)) -> bool:
    """Net income too low for province NC."""
    return province == 'NC' and net_income < limit


@step(output="cc_province_nc_max_loan_to_income")
def cc_province_nc_max_loan_to_income(province: str, requested_amount_to_gross_income: float, limit: float = param(7.4)) -> bool:
    """Loan too large for income in province NC."""
    return province == 'NC' and requested_amount_to_gross_income > limit


@step(output="cc_channel_branch_max_debt")
def cc_channel_branch_max_debt(channel: str, debt_service_ratio: float, limit: float = param(0.42)) -> bool:
    """Debt repayments too high for channel branch."""
    return channel == 'branch' and debt_service_ratio > limit


@step(output="cc_channel_branch_min_score")
def cc_channel_branch_min_score(channel: str, bureau_score: float, limit: float = param(570.0)) -> bool:
    """Bureau score too low for channel branch."""
    return channel == 'branch' and bureau_score < limit


@step(output="cc_channel_branch_min_income")
def cc_channel_branch_min_income(channel: str, net_income: float, limit: float = param(6250.0)) -> bool:
    """Net income too low for channel branch."""
    return channel == 'branch' and net_income < limit


@step(output="cc_channel_branch_max_loan_to_income")
def cc_channel_branch_max_loan_to_income(channel: str, requested_amount_to_gross_income: float, limit: float = param(4.5)) -> bool:
    """Loan too large for income in channel branch."""
    return channel == 'branch' and requested_amount_to_gross_income > limit


@step(output="cc_channel_app_max_debt")
def cc_channel_app_max_debt(channel: str, debt_service_ratio: float, limit: float = param(0.4)) -> bool:
    """Debt repayments too high for channel app."""
    return channel == 'app' and debt_service_ratio > limit


@step(output="cc_channel_app_min_score")
def cc_channel_app_min_score(channel: str, bureau_score: float, limit: float = param(640.0)) -> bool:
    """Bureau score too low for channel app."""
    return channel == 'app' and bureau_score < limit


@step(output="cc_channel_app_min_income")
def cc_channel_app_min_income(channel: str, net_income: float, limit: float = param(4750.0)) -> bool:
    """Net income too low for channel app."""
    return channel == 'app' and net_income < limit


@step(output="cc_channel_app_max_loan_to_income")
def cc_channel_app_max_loan_to_income(channel: str, requested_amount_to_gross_income: float, limit: float = param(6.4)) -> bool:
    """Loan too large for income in channel app."""
    return channel == 'app' and requested_amount_to_gross_income > limit


@step(output="cc_channel_web_max_debt")
def cc_channel_web_max_debt(channel: str, debt_service_ratio: float, limit: float = param(0.34)) -> bool:
    """Debt repayments too high for channel web."""
    return channel == 'web' and debt_service_ratio > limit


@step(output="cc_channel_web_min_score")
def cc_channel_web_min_score(channel: str, bureau_score: float, limit: float = param(575.0)) -> bool:
    """Bureau score too low for channel web."""
    return channel == 'web' and bureau_score < limit


@step(output="cc_channel_web_min_income")
def cc_channel_web_min_income(channel: str, net_income: float, limit: float = param(6750.0)) -> bool:
    """Net income too low for channel web."""
    return channel == 'web' and net_income < limit


@step(output="cc_channel_web_max_loan_to_income")
def cc_channel_web_max_loan_to_income(channel: str, requested_amount_to_gross_income: float, limit: float = param(8.1)) -> bool:
    """Loan too large for income in channel web."""
    return channel == 'web' and requested_amount_to_gross_income > limit


@step(outputs=("cc_policy_declined", "cc_policy_reason"))
def cc_policy_outcome(
    cc_min_age: bool,
    cc_max_age: bool,
    cc_min_gross_income: bool,
    cc_min_net_income: bool,
    cc_max_debt_service: bool,
    cc_min_bureau: bool,
    cc_max_enquiries: bool,
    cc_max_missed: bool,
    cc_max_judgements: bool,
    cc_min_employment: bool,
    cc_min_address: bool,
    cc_max_utilisation: bool,
    cc_max_dependants: bool,
    cc_min_disposable: bool,
    cc_max_requested: bool,
    cc_min_requested: bool,
    cc_sector_1_max_debt: bool,
    cc_sector_1_min_score: bool,
    cc_sector_1_min_income: bool,
    cc_sector_1_max_loan_to_income: bool,
    cc_sector_2_max_debt: bool,
    cc_sector_2_min_score: bool,
    cc_sector_2_min_income: bool,
    cc_sector_2_max_loan_to_income: bool,
    cc_sector_3_max_debt: bool,
    cc_sector_3_min_score: bool,
    cc_sector_3_min_income: bool,
    cc_sector_3_max_loan_to_income: bool,
    cc_sector_4_max_debt: bool,
    cc_sector_4_min_score: bool,
    cc_sector_4_min_income: bool,
    cc_sector_4_max_loan_to_income: bool,
    cc_sector_5_max_debt: bool,
    cc_sector_5_min_score: bool,
    cc_sector_5_min_income: bool,
    cc_sector_5_max_loan_to_income: bool,
    cc_sector_6_max_debt: bool,
    cc_sector_6_min_score: bool,
    cc_sector_6_min_income: bool,
    cc_sector_6_max_loan_to_income: bool,
    cc_province_gp_max_debt: bool,
    cc_province_gp_min_score: bool,
    cc_province_gp_min_income: bool,
    cc_province_gp_max_loan_to_income: bool,
    cc_province_wc_max_debt: bool,
    cc_province_wc_min_score: bool,
    cc_province_wc_min_income: bool,
    cc_province_wc_max_loan_to_income: bool,
    cc_province_kzn_max_debt: bool,
    cc_province_kzn_min_score: bool,
    cc_province_kzn_min_income: bool,
    cc_province_kzn_max_loan_to_income: bool,
    cc_province_ec_max_debt: bool,
    cc_province_ec_min_score: bool,
    cc_province_ec_min_income: bool,
    cc_province_ec_max_loan_to_income: bool,
    cc_province_fs_max_debt: bool,
    cc_province_fs_min_score: bool,
    cc_province_fs_min_income: bool,
    cc_province_fs_max_loan_to_income: bool,
    cc_province_lp_max_debt: bool,
    cc_province_lp_min_score: bool,
    cc_province_lp_min_income: bool,
    cc_province_lp_max_loan_to_income: bool,
    cc_province_mp_max_debt: bool,
    cc_province_mp_min_score: bool,
    cc_province_mp_min_income: bool,
    cc_province_mp_max_loan_to_income: bool,
    cc_province_nw_max_debt: bool,
    cc_province_nw_min_score: bool,
    cc_province_nw_min_income: bool,
    cc_province_nw_max_loan_to_income: bool,
    cc_province_nc_max_debt: bool,
    cc_province_nc_min_score: bool,
    cc_province_nc_min_income: bool,
    cc_province_nc_max_loan_to_income: bool,
    cc_channel_branch_max_debt: bool,
    cc_channel_branch_min_score: bool,
    cc_channel_branch_min_income: bool,
    cc_channel_branch_max_loan_to_income: bool,
    cc_channel_app_max_debt: bool,
    cc_channel_app_min_score: bool,
    cc_channel_app_min_income: bool,
    cc_channel_app_max_loan_to_income: bool,
    cc_channel_web_max_debt: bool,
    cc_channel_web_min_score: bool,
    cc_channel_web_min_income: bool,
    cc_channel_web_max_loan_to_income: bool,
) -> tuple[bool, str]:
    """The first failed rule, in priority order."""
    for failed, reason in (
        (cc_min_age, 'Under the minimum age'),
        (cc_max_age, 'Over the maximum age at maturity'),
        (cc_min_gross_income, 'Income below the minimum'),
        (cc_min_net_income, 'Net income below the minimum'),
        (cc_max_debt_service, 'Debt repayments too high'),
        (cc_min_bureau, 'Bureau score too low'),
        (cc_max_enquiries, 'Too many recent credit enquiries'),
        (cc_max_missed, 'Missed payments in the last year'),
        (cc_max_judgements, 'Judgement on record'),
        (cc_min_employment, 'Employed for too short a time'),
        (cc_min_address, 'Address too recent'),
        (cc_max_utilisation, 'Card limits nearly exhausted'),
        (cc_max_dependants, 'Household too large for declared income'),
        (cc_min_disposable, 'Too little left each month'),
        (cc_max_requested, 'Amount above the product maximum'),
        (cc_min_requested, 'Amount below the product minimum'),
        (cc_sector_1_max_debt, 'Debt repayments too high for sector 1'),
        (cc_sector_1_min_score, 'Bureau score too low for sector 1'),
        (cc_sector_1_min_income, 'Net income too low for sector 1'),
        (cc_sector_1_max_loan_to_income, 'Loan too large for income in sector 1'),
        (cc_sector_2_max_debt, 'Debt repayments too high for sector 2'),
        (cc_sector_2_min_score, 'Bureau score too low for sector 2'),
        (cc_sector_2_min_income, 'Net income too low for sector 2'),
        (cc_sector_2_max_loan_to_income, 'Loan too large for income in sector 2'),
        (cc_sector_3_max_debt, 'Debt repayments too high for sector 3'),
        (cc_sector_3_min_score, 'Bureau score too low for sector 3'),
        (cc_sector_3_min_income, 'Net income too low for sector 3'),
        (cc_sector_3_max_loan_to_income, 'Loan too large for income in sector 3'),
        (cc_sector_4_max_debt, 'Debt repayments too high for sector 4'),
        (cc_sector_4_min_score, 'Bureau score too low for sector 4'),
        (cc_sector_4_min_income, 'Net income too low for sector 4'),
        (cc_sector_4_max_loan_to_income, 'Loan too large for income in sector 4'),
        (cc_sector_5_max_debt, 'Debt repayments too high for sector 5'),
        (cc_sector_5_min_score, 'Bureau score too low for sector 5'),
        (cc_sector_5_min_income, 'Net income too low for sector 5'),
        (cc_sector_5_max_loan_to_income, 'Loan too large for income in sector 5'),
        (cc_sector_6_max_debt, 'Debt repayments too high for sector 6'),
        (cc_sector_6_min_score, 'Bureau score too low for sector 6'),
        (cc_sector_6_min_income, 'Net income too low for sector 6'),
        (cc_sector_6_max_loan_to_income, 'Loan too large for income in sector 6'),
        (cc_province_gp_max_debt, 'Debt repayments too high for province GP'),
        (cc_province_gp_min_score, 'Bureau score too low for province GP'),
        (cc_province_gp_min_income, 'Net income too low for province GP'),
        (cc_province_gp_max_loan_to_income, 'Loan too large for income in province GP'),
        (cc_province_wc_max_debt, 'Debt repayments too high for province WC'),
        (cc_province_wc_min_score, 'Bureau score too low for province WC'),
        (cc_province_wc_min_income, 'Net income too low for province WC'),
        (cc_province_wc_max_loan_to_income, 'Loan too large for income in province WC'),
        (cc_province_kzn_max_debt, 'Debt repayments too high for province KZN'),
        (cc_province_kzn_min_score, 'Bureau score too low for province KZN'),
        (cc_province_kzn_min_income, 'Net income too low for province KZN'),
        (cc_province_kzn_max_loan_to_income, 'Loan too large for income in province KZN'),
        (cc_province_ec_max_debt, 'Debt repayments too high for province EC'),
        (cc_province_ec_min_score, 'Bureau score too low for province EC'),
        (cc_province_ec_min_income, 'Net income too low for province EC'),
        (cc_province_ec_max_loan_to_income, 'Loan too large for income in province EC'),
        (cc_province_fs_max_debt, 'Debt repayments too high for province FS'),
        (cc_province_fs_min_score, 'Bureau score too low for province FS'),
        (cc_province_fs_min_income, 'Net income too low for province FS'),
        (cc_province_fs_max_loan_to_income, 'Loan too large for income in province FS'),
        (cc_province_lp_max_debt, 'Debt repayments too high for province LP'),
        (cc_province_lp_min_score, 'Bureau score too low for province LP'),
        (cc_province_lp_min_income, 'Net income too low for province LP'),
        (cc_province_lp_max_loan_to_income, 'Loan too large for income in province LP'),
        (cc_province_mp_max_debt, 'Debt repayments too high for province MP'),
        (cc_province_mp_min_score, 'Bureau score too low for province MP'),
        (cc_province_mp_min_income, 'Net income too low for province MP'),
        (cc_province_mp_max_loan_to_income, 'Loan too large for income in province MP'),
        (cc_province_nw_max_debt, 'Debt repayments too high for province NW'),
        (cc_province_nw_min_score, 'Bureau score too low for province NW'),
        (cc_province_nw_min_income, 'Net income too low for province NW'),
        (cc_province_nw_max_loan_to_income, 'Loan too large for income in province NW'),
        (cc_province_nc_max_debt, 'Debt repayments too high for province NC'),
        (cc_province_nc_min_score, 'Bureau score too low for province NC'),
        (cc_province_nc_min_income, 'Net income too low for province NC'),
        (cc_province_nc_max_loan_to_income, 'Loan too large for income in province NC'),
        (cc_channel_branch_max_debt, 'Debt repayments too high for channel branch'),
        (cc_channel_branch_min_score, 'Bureau score too low for channel branch'),
        (cc_channel_branch_min_income, 'Net income too low for channel branch'),
        (cc_channel_branch_max_loan_to_income, 'Loan too large for income in channel branch'),
        (cc_channel_app_max_debt, 'Debt repayments too high for channel app'),
        (cc_channel_app_min_score, 'Bureau score too low for channel app'),
        (cc_channel_app_min_income, 'Net income too low for channel app'),
        (cc_channel_app_max_loan_to_income, 'Loan too large for income in channel app'),
        (cc_channel_web_max_debt, 'Debt repayments too high for channel web'),
        (cc_channel_web_min_score, 'Bureau score too low for channel web'),
        (cc_channel_web_min_income, 'Net income too low for channel web'),
        (cc_channel_web_max_loan_to_income, 'Loan too large for income in channel web'),
    ):
        if failed:
            return True, reason
    return False, ""


cc_policy = flow(
    cc_min_age,
    cc_max_age,
    cc_min_gross_income,
    cc_min_net_income,
    cc_max_debt_service,
    cc_min_bureau,
    cc_max_enquiries,
    cc_max_missed,
    cc_max_judgements,
    cc_min_employment,
    cc_min_address,
    cc_max_utilisation,
    cc_max_dependants,
    cc_min_disposable,
    cc_max_requested,
    cc_min_requested,
    cc_sector_1_max_debt,
    cc_sector_1_min_score,
    cc_sector_1_min_income,
    cc_sector_1_max_loan_to_income,
    cc_sector_2_max_debt,
    cc_sector_2_min_score,
    cc_sector_2_min_income,
    cc_sector_2_max_loan_to_income,
    cc_sector_3_max_debt,
    cc_sector_3_min_score,
    cc_sector_3_min_income,
    cc_sector_3_max_loan_to_income,
    cc_sector_4_max_debt,
    cc_sector_4_min_score,
    cc_sector_4_min_income,
    cc_sector_4_max_loan_to_income,
    cc_sector_5_max_debt,
    cc_sector_5_min_score,
    cc_sector_5_min_income,
    cc_sector_5_max_loan_to_income,
    cc_sector_6_max_debt,
    cc_sector_6_min_score,
    cc_sector_6_min_income,
    cc_sector_6_max_loan_to_income,
    cc_province_gp_max_debt,
    cc_province_gp_min_score,
    cc_province_gp_min_income,
    cc_province_gp_max_loan_to_income,
    cc_province_wc_max_debt,
    cc_province_wc_min_score,
    cc_province_wc_min_income,
    cc_province_wc_max_loan_to_income,
    cc_province_kzn_max_debt,
    cc_province_kzn_min_score,
    cc_province_kzn_min_income,
    cc_province_kzn_max_loan_to_income,
    cc_province_ec_max_debt,
    cc_province_ec_min_score,
    cc_province_ec_min_income,
    cc_province_ec_max_loan_to_income,
    cc_province_fs_max_debt,
    cc_province_fs_min_score,
    cc_province_fs_min_income,
    cc_province_fs_max_loan_to_income,
    cc_province_lp_max_debt,
    cc_province_lp_min_score,
    cc_province_lp_min_income,
    cc_province_lp_max_loan_to_income,
    cc_province_mp_max_debt,
    cc_province_mp_min_score,
    cc_province_mp_min_income,
    cc_province_mp_max_loan_to_income,
    cc_province_nw_max_debt,
    cc_province_nw_min_score,
    cc_province_nw_min_income,
    cc_province_nw_max_loan_to_income,
    cc_province_nc_max_debt,
    cc_province_nc_min_score,
    cc_province_nc_min_income,
    cc_province_nc_max_loan_to_income,
    cc_channel_branch_max_debt,
    cc_channel_branch_min_score,
    cc_channel_branch_min_income,
    cc_channel_branch_max_loan_to_income,
    cc_channel_app_max_debt,
    cc_channel_app_min_score,
    cc_channel_app_min_income,
    cc_channel_app_max_loan_to_income,
    cc_channel_web_max_debt,
    cc_channel_web_min_score,
    cc_channel_web_min_income,
    cc_channel_web_max_loan_to_income,
    cc_policy_outcome,
    name="policy",
)
