"""Credit card: revolving limit, rate by grade. Pricing: the base rate by term, a loading by risk grade, fees by amount, capped by regulation.

Generated by make_bank.py; edit the generator, not this file."""
from decider import dag, flow, param, step
from decider.steps.tables import DecisionTableConfig

cc_base_rates = DecisionTableConfig(
    name="cc_base_rates",
    columns={"min_term": "Float64", "max_term": "Float64", "cc_base_rate": "Float64"},
    rows={"table": "cc_base_rates", "shared": True},
    expression={"type": "between", "variable": "requested_term", "lower_bound_column": "min_term", "upper_bound_column": "max_term"},
    outputs=["cc_base_rate"],
)
cc_risk_loadings = DecisionTableConfig(
    name="cc_risk_loadings",
    columns={"grade_key": "Int64", "cc_risk_loading": "Float64"},
    rows={"table": "cc_risk_loadings", "shared": True},
    expression={"type": "eq", "variable": "grade", "value_column": "grade_key"},
    outputs=["cc_risk_loading"],
)
cc_fees = DecisionTableConfig(
    name="cc_fees",
    columns={"min_amount": "Float64", "max_amount": "Float64", "cc_initiation_fee": "Float64", "cc_monthly_fee": "Float64"},
    rows={"table": "cc_fees", "shared": True},
    expression={"type": "between", "variable": "requested_amount", "lower_bound_column": "min_amount", "upper_bound_column": "max_amount"},
    outputs=["cc_initiation_fee", "cc_monthly_fee"],
)


def cc_salary_discount(salary_account: bool, discount: float = param(0.005)) -> float:
    return discount if salary_account else 0.0


def cc_channel_discount(channel_discount: float, weight: float = param(1.0)) -> float:
    return channel_discount * weight


def cc_loyalty_discount(months_at_address: float, discount: float = param(0.001)) -> float:
    return discount if months_at_address > 60 else 0.0


def cc_clean_record_discount(clean_record: bool, discount: float = param(0.002)) -> float:
    return discount if clean_record else 0.0


def cc_fraud_loading(fraud_referral: bool, loading: float = param(0.01)) -> float:
    return loading if fraud_referral else 0.0


def cc_collections_loading(collections_band: int, per_band: float = param(0.0075)) -> float:
    return per_band * (collections_band - 1)


def cc_raw_rate(cc_base_rate: float, cc_risk_loading: float, cc_salary_discount: float, cc_channel_discount: float, cc_loyalty_discount: float, cc_clean_record_discount: float, cc_fraud_loading: float, cc_collections_loading: float) -> float:
    return cc_base_rate + cc_risk_loading - cc_salary_discount - cc_channel_discount - cc_loyalty_discount - cc_clean_record_discount + cc_fraud_loading + cc_collections_loading


@step(output="cc_rate")
def cc_regulated_rate(cc_raw_rate: float, repo_rate: float = param(0.0775, shared_key="repo_rate"),
                        cap_multiple: float = param(2.2), cap_margin: float = param(0.2)) -> float:
    """The National Credit Act cap: repo times a multiple plus a margin."""
    return min(cc_raw_rate, repo_rate * cap_multiple + cap_margin)


def cc_monthly_rate(cc_rate: float) -> float:
    return cc_rate / 12


cc_pricing = flow(
    cc_base_rates,
    cc_risk_loadings,
    cc_fees,
    cc_salary_discount,
    cc_channel_discount,
    cc_loyalty_discount,
    cc_clean_record_discount,
    cc_fraud_loading,
    cc_collections_loading,
    cc_raw_rate,
    cc_regulated_rate,
    cc_monthly_rate,
    name="pricing",
)
