"""Credit card: revolving limit, rate by grade. Pricing: the base rate by term, a loading by risk grade, fees by amount, capped by regulation.

Generated by make_bank.py; edit the generator, not this file."""
from decider import dag, flow, param, step

from bank.lookup import LookupTable

cc_base_rates = LookupTable(
    name="cc_base_rates",
    ranges={"requested_term": ["min_term", "max_term"]},
    returns={"cc_base_rate": "rate"},
    rows=[{"min_term": 1, "max_term": 12, "rate": 0.205}, {"min_term": 13, "max_term": 60, "rate": 0.225}],
)
cc_risk_loadings = LookupTable(
    name="cc_risk_loadings",
    keys={"grade": "grade"},
    returns={"cc_risk_loading": "loading"},
    rows=[{"grade": 1, "loading": 0.0}, {"grade": 2, "loading": 0.015}, {"grade": 3, "loading": 0.03}, {"grade": 4, "loading": 0.045}],
)
cc_fees = LookupTable(
    name="cc_fees",
    ranges={"requested_amount": ["min_amount", "max_amount"]},
    returns={"cc_initiation_fee": "initiation_fee", "cc_monthly_fee": "monthly_fee"},
    rows=[{"min_amount": 0, "max_amount": 10000, "initiation_fee": 165.0, "monthly_fee": 69.0}, {"min_amount": 10001, "max_amount": 50000, "initiation_fee": 690.0, "monthly_fee": 69.0}, {"min_amount": 50001, "max_amount": 10000000, "initiation_fee": 1207.5, "monthly_fee": 69.0}],
)


def cc_salary_discount(salary_account: bool, discount: float = param(0.005)) -> float:
    return discount if salary_account else 0.0


def cc_channel_discount(channel: str, app_discount: float = param(0.0025)) -> float:
    return app_discount if channel == "app" else 0.0


def cc_loyalty_discount(months_at_address: float, discount: float = param(0.001)) -> float:
    return discount if months_at_address > 60 else 0.0


def cc_clean_record_discount(clean_record: bool, discount: float = param(0.002)) -> float:
    return discount if clean_record else 0.0


def cc_fraud_loading(fraud_referral: bool, loading: float = param(0.01)) -> float:
    return loading if fraud_referral else 0.0


def cc_collections_loading(collections_band: int, per_band: float = param(0.0075)) -> float:
    return per_band * (collections_band - 1)


def cc_raw_rate(cc_base_rate: float, cc_risk_loading: float, cc_salary_discount: float, cc_channel_discount: float, cc_loyalty_discount: float, cc_clean_record_discount: float, cc_fraud_loading: float, cc_collections_loading: float) -> float:
    return cc_base_rate + cc_risk_loading - cc_salary_discount - cc_channel_discount - cc_loyalty_discount - cc_clean_record_discount + cc_fraud_loading + cc_collections_loading


@step(output="cc_rate")
def cc_regulated_rate(cc_raw_rate: float, repo_rate: float = param(0.0775, shared_key="repo_rate"),
                        cap_multiple: float = param(2.2), cap_margin: float = param(0.2)) -> float:
    """The National Credit Act cap: repo times a multiple plus a margin."""
    return min(cc_raw_rate, repo_rate * cap_multiple + cap_margin)


def cc_monthly_rate(cc_rate: float) -> float:
    return cc_rate / 12


cc_pricing = flow(
    cc_base_rates,
    cc_risk_loadings,
    cc_fees,
    cc_salary_discount,
    cc_channel_discount,
    cc_loyalty_discount,
    cc_clean_record_discount,
    cc_fraud_loading,
    cc_collections_loading,
    cc_raw_rate,
    cc_regulated_rate,
    cc_monthly_rate,
    name="pricing",
)
