"""Credit card: revolving limit, rate by grade. Application scorecard: points per characteristic, summed into a score.

Generated by make_bank.py; edit the generator, not this file."""
from decider import flow, param, step


def cc_pts_bureau_score(bureau_score: float, cut_1: float = param(0.13), cut_2: float = param(0.83), cut_3: float = param(0.95),
        pts_1: float = param(40.0), pts_2: float = param(-20.0), pts_3: float = param(25.0), pts_4: float = param(15.0)) -> float:
    x = bureau_score
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def cc_pts_months_employed(months_employed: float, cut_1: float = param(0.57), cut_2: float = param(0.81), cut_3: float = param(0.86),
        pts_1: float = param(-15.0), pts_2: float = param(25.0), pts_3: float = param(35.0), pts_4: float = param(-10.0)) -> float:
    x = months_employed
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def cc_pts_months_at_address(months_at_address: float, cut_1: float = param(0.26), cut_2: float = param(0.32), cut_3: float = param(0.72),
        pts_1: float = param(35.0), pts_2: float = param(20.0), pts_3: float = param(-5.0), pts_4: float = param(-10.0)) -> float:
    x = months_at_address
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def cc_pts_age(age: float, cut_1: float = param(0.15), cut_2: float = param(0.17), cut_3: float = param(0.66),
        pts_1: float = param(30.0), pts_2: float = param(-10.0), pts_3: float = param(15.0), pts_4: float = param(5.0)) -> float:
    x = age
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def cc_pts_debt_service_ratio(debt_service_ratio: float, cut_1: float = param(0.1), cut_2: float = param(0.11), cut_3: float = param(0.39),
        pts_1: float = param(40.0), pts_2: float = param(-20.0), pts_3: float = param(-5.0), pts_4: float = param(25.0)) -> float:
    x = debt_service_ratio
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def cc_pts_card_utilisation(card_utilisation: float, cut_1: float = param(0.67), cut_2: float = param(0.73), cut_3: float = param(0.98),
        pts_1: float = param(15.0), pts_2: float = param(30.0), pts_3: float = param(25.0), pts_4: float = param(15.0)) -> float:
    x = card_utilisation
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def cc_pts_enquiries_6m(enquiries_6m: float, cut_1: float = param(0.46), cut_2: float = param(0.75), cut_3: float = param(0.81),
        pts_1: float = param(5.0), pts_2: float = param(30.0), pts_3: float = param(25.0), pts_4: float = param(20.0)) -> float:
    x = enquiries_6m
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def cc_pts_missed_payments_12m(missed_payments_12m: float, cut_1: float = param(0.17), cut_2: float = param(0.21), cut_3: float = param(0.58),
        pts_1: float = param(15.0), pts_2: float = param(10.0), pts_3: float = param(25.0), pts_4: float = param(10.0)) -> float:
    x = missed_payments_12m
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def cc_pts_dependants(dependants: float, cut_1: float = param(0.01), cut_2: float = param(0.12), cut_3: float = param(0.7),
        pts_1: float = param(-15.0), pts_2: float = param(15.0), pts_3: float = param(-10.0), pts_4: float = param(-20.0)) -> float:
    x = dependants
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def cc_pts_disposable_income(disposable_income: float, cut_1: float = param(0.36), cut_2: float = param(0.9), cut_3: float = param(0.94),
        pts_1: float = param(35.0), pts_2: float = param(15.0), pts_3: float = param(20.0), pts_4: float = param(5.0)) -> float:
    x = disposable_income
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def cc_pts_expenses_to_net_income(expenses_to_net_income: float, cut_1: float = param(0.09), cut_2: float = param(0.17), cut_3: float = param(0.37),
        pts_1: float = param(15.0), pts_2: float = param(40.0), pts_3: float = param(10.0), pts_4: float = param(40.0)) -> float:
    x = expenses_to_net_income
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def cc_pts_requested_amount_to_gross_income(requested_amount_to_gross_income: float, cut_1: float = param(0.14), cut_2: float = param(0.45), cut_3: float = param(0.58),
        pts_1: float = param(10.0), pts_2: float = param(40.0), pts_3: float = param(40.0), pts_4: float = param(-5.0)) -> float:
    x = requested_amount_to_gross_income
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def cc_pts_existing_instalments_to_net_income(existing_instalments_to_net_income: float, cut_1: float = param(0.5), cut_2: float = param(0.69), cut_3: float = param(0.78),
        pts_1: float = param(40.0), pts_2: float = param(30.0), pts_3: float = param(0.0), pts_4: float = param(0.0)) -> float:
    x = existing_instalments_to_net_income
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def cc_pts_net_income(net_income: float, cut_1: float = param(0.36), cut_2: float = param(0.64), cut_3: float = param(0.75),
        pts_1: float = param(-10.0), pts_2: float = param(40.0), pts_3: float = param(25.0), pts_4: float = param(-20.0)) -> float:
    x = net_income
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def cc_pts_gross_income(gross_income: float, cut_1: float = param(0.22), cut_2: float = param(0.35), cut_3: float = param(0.64),
        pts_1: float = param(-15.0), pts_2: float = param(-20.0), pts_3: float = param(10.0), pts_4: float = param(-10.0)) -> float:
    x = gross_income
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def cc_pts_judgements(judgements: float, cut_1: float = param(0.45), cut_2: float = param(0.68), cut_3: float = param(0.98),
        pts_1: float = param(-20.0), pts_2: float = param(25.0), pts_3: float = param(20.0), pts_4: float = param(15.0)) -> float:
    x = judgements
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def cc_pts_months_employed_to_age(months_employed_to_age: float, cut_1: float = param(0.15), cut_2: float = param(0.21), cut_3: float = param(0.32),
        pts_1: float = param(-10.0), pts_2: float = param(30.0), pts_3: float = param(35.0), pts_4: float = param(-5.0)) -> float:
    x = months_employed_to_age
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def cc_pts_enquiries_6m_to_months_at_address(enquiries_6m_to_months_at_address: float, cut_1: float = param(0.61), cut_2: float = param(0.77), cut_3: float = param(0.8),
        pts_1: float = param(40.0), pts_2: float = param(5.0), pts_3: float = param(25.0), pts_4: float = param(35.0)) -> float:
    x = enquiries_6m_to_months_at_address
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def cc_pts_card_utilisation_to_bureau_score(card_utilisation_to_bureau_score: float, cut_1: float = param(0.8), cut_2: float = param(0.88), cut_3: float = param(0.92),
        pts_1: float = param(10.0), pts_2: float = param(-5.0), pts_3: float = param(-5.0), pts_4: float = param(35.0)) -> float:
    x = card_utilisation_to_bureau_score
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def cc_pts_expenses_to_gross_income(expenses_to_gross_income: float, cut_1: float = param(0.38), cut_2: float = param(0.73), cut_3: float = param(0.87),
        pts_1: float = param(35.0), pts_2: float = param(40.0), pts_3: float = param(40.0), pts_4: float = param(20.0)) -> float:
    x = expenses_to_gross_income
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def cc_pts_net_income_zscore(net_income_zscore: float, cut_1: float = param(0.3), cut_2: float = param(0.35), cut_3: float = param(0.41),
        pts_1: float = param(25.0), pts_2: float = param(35.0), pts_3: float = param(20.0), pts_4: float = param(0.0)) -> float:
    x = net_income_zscore
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def cc_pts_bureau_score_zscore(bureau_score_zscore: float, cut_1: float = param(0.12), cut_2: float = param(0.43), cut_3: float = param(0.53),
        pts_1: float = param(-10.0), pts_2: float = param(15.0), pts_3: float = param(-10.0), pts_4: float = param(-5.0)) -> float:
    x = bureau_score_zscore
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def cc_score(cc_pts_bureau_score: float, cc_pts_months_employed: float, cc_pts_months_at_address: float, cc_pts_age: float, cc_pts_debt_service_ratio: float, cc_pts_card_utilisation: float, cc_pts_enquiries_6m: float, cc_pts_missed_payments_12m: float, cc_pts_dependants: float, cc_pts_disposable_income: float, cc_pts_expenses_to_net_income: float, cc_pts_requested_amount_to_gross_income: float, cc_pts_existing_instalments_to_net_income: float, cc_pts_net_income: float, cc_pts_gross_income: float, cc_pts_judgements: float, cc_pts_months_employed_to_age: float, cc_pts_enquiries_6m_to_months_at_address: float, cc_pts_card_utilisation_to_bureau_score: float, cc_pts_expenses_to_gross_income: float, cc_pts_net_income_zscore: float, cc_pts_bureau_score_zscore: float, intercept: float = param(600.0)) -> float:
    return intercept + cc_pts_bureau_score + cc_pts_months_employed + cc_pts_months_at_address + cc_pts_age + cc_pts_debt_service_ratio + cc_pts_card_utilisation + cc_pts_enquiries_6m + cc_pts_missed_payments_12m + cc_pts_dependants + cc_pts_disposable_income + cc_pts_expenses_to_net_income + cc_pts_requested_amount_to_gross_income + cc_pts_existing_instalments_to_net_income + cc_pts_net_income + cc_pts_gross_income + cc_pts_judgements + cc_pts_months_employed_to_age + cc_pts_enquiries_6m_to_months_at_address + cc_pts_card_utilisation_to_bureau_score + cc_pts_expenses_to_gross_income + cc_pts_net_income_zscore + cc_pts_bureau_score_zscore


def cc_score_band(cc_score: float, low: float = param(580.0), high: float = param(680.0)) -> int:
    return 3 if cc_score < low else (2 if cc_score < high else 1)


cc_scorecard = flow(
    cc_pts_bureau_score,
    cc_pts_months_employed,
    cc_pts_months_at_address,
    cc_pts_age,
    cc_pts_debt_service_ratio,
    cc_pts_card_utilisation,
    cc_pts_enquiries_6m,
    cc_pts_missed_payments_12m,
    cc_pts_dependants,
    cc_pts_disposable_income,
    cc_pts_expenses_to_net_income,
    cc_pts_requested_amount_to_gross_income,
    cc_pts_existing_instalments_to_net_income,
    cc_pts_net_income,
    cc_pts_gross_income,
    cc_pts_judgements,
    cc_pts_months_employed_to_age,
    cc_pts_enquiries_6m_to_months_at_address,
    cc_pts_card_utilisation_to_bureau_score,
    cc_pts_expenses_to_gross_income,
    cc_pts_net_income_zscore,
    cc_pts_bureau_score_zscore,
    cc_score,
    cc_score_band,
    name="scorecard",
)
