"""The final decision: referrals, the reason code and the channel message.

Generated by make_bank.py; edit the generator, not this file."""
from decider import flow, param, step


def product_arm(product_code: int) -> int:
    return product_code


@step(output="refer")
def refer_to_underwriter(fraud_referral: bool, offer_amount: float, referral_amount: float = param(250000.0)) -> bool:
    """Large offers and fraud referrals go to a person."""
    return fraud_referral or offer_amount > referral_amount


@step(output="decision")
def final_decision(declined: bool, refer: bool) -> str:
    return "decline" if declined else ("refer" if refer else "approve")


@step(output="reason_code")
def reason_code(decision: str, decline_reason: str) -> str:
    return decline_reason if decision == "decline" else ("Referred for review" if decision == "refer" else "Approved")


@step(output="total_cost")
def total_cost_of_credit(monthly_instalment: float, offer_term: float, offer_amount: float) -> float:
    return monthly_instalment * offer_term - offer_amount


decision = flow(refer_to_underwriter, final_decision, reason_code, total_cost_of_credit, name="decision")
