"""Credit origination: features, trees, one arm per product, then the decision.

Generated by make_bank.py; edit the generator, not this file."""
import json
from pathlib import Path

from decider import branch, flow

from bank.decision import decision, product_arm
from bank.features import behaviour, debt, derived, household, income, stability
from bank.products.credit_card import credit_card
from bank.products.home_loan import home_loan
from bank.products.overdraft import overdraft
from bank.products.personal_loan import personal_loan
from bank.trees import bureau_grade, collections_risk, fraud_screen

features = flow(income, debt, stability, behaviour, household, derived, name="features")
risk = flow(bureau_grade, fraud_screen, collections_risk, name="risk")
product = branch(
    product_arm, personal_loan, credit_card, overdraft, home_loan,
    modifies=["offer_amount", "offer_term", "offer_rate", "monthly_instalment", "declined", "decline_reason"],
    name="product",
)
origination = flow(features, risk, product, decision, name="origination")

SAMPLE = json.loads((Path(__file__).parent / "applications.json").read_text())
