"""Tables every product reads: the channel discount and the credit life premium by age.

Generated by make_bank.py; edit the generator, not this file."""
from decider.steps.tables import DecisionTableConfig

channel_discounts = DecisionTableConfig(
    name="channel_discounts",
    columns={"channel_key": "String", "channel_discount": "Float64"},
    rows={"table": "channel_discounts", "shared": True},
    expression={"type": "eq", "variable": "channel", "value_column": "channel_key"},
    outputs=["channel_discount"],
    default=[0.0],
)
credit_life_rates = DecisionTableConfig(
    name="credit_life_rates",
    columns={"min_age": "Float64", "max_age": "Float64", "credit_life_rate": "Float64"},
    rows={"table": "credit_life_rates", "shared": True},
    expression={"type": "between", "variable": "age", "lower_bound_column": "min_age", "upper_bound_column": "max_age"},
    outputs=["credit_life_rate"],
    default=[0.0098],
)
