"""Overdraft on a salary account.

Generated by make_bank.py; edit the generator, not this file."""
from decider import flow

from bank.products.overdraft.affordability import od_affordability
from bank.products.overdraft.limits import od_limits
from bank.products.overdraft.policy import od_policy
from bank.products.overdraft.pricing import od_pricing
from bank.products.overdraft.scorecard import od_scorecard
from bank.products.overdraft.stress import od_stress

overdraft = flow(od_scorecard, od_policy, od_pricing, od_affordability, od_stress, od_limits, name="overdraft")
