"""Overdraft on a salary account. Affordability: the instalment at the offered and a stressed rate against disposable income.

Generated by make_bank.py; edit the generator, not this file."""
from decider import flow, param, step


def od_instalment(requested_amount: float, requested_term: float, od_monthly_rate: float, od_monthly_fee: float) -> float:
    return requested_amount * od_monthly_rate / (1 - (1 + od_monthly_rate) ** -requested_term) + od_monthly_fee


def od_stress_rate(od_rate: float, buffer: float = param(0.03)) -> float:
    return od_rate + buffer


def od_stress_instalment(requested_amount: float, requested_term: float, od_stress_rate: float) -> float:
    return requested_amount * (od_stress_rate / 12) / (1 - (1 + od_stress_rate / 12) ** -requested_term)


def od_affordable_instalment(disposable_income_buffered: float, share: float = param(0.5)) -> float:
    return max(disposable_income_buffered * share, 0.0)


def od_instalment_fits(od_stress_instalment: float, od_affordable_instalment: float) -> bool:
    return od_stress_instalment <= od_affordable_instalment


def od_max_affordable_amount(od_affordable_instalment: float, requested_term: float, od_stress_rate: float) -> float:
    return od_affordable_instalment * (1 - (1 + od_stress_rate / 12) ** -requested_term) / (od_stress_rate / 12)


def od_dti_band_0(debt_service_ratio: float, lo: float = param(0), hi: float = param(0.2)) -> bool:
    return lo <= debt_service_ratio < hi


def od_dti_band_1(debt_service_ratio: float, lo: float = param(0.2), hi: float = param(0.35)) -> bool:
    return lo <= debt_service_ratio < hi


def od_dti_band_2(debt_service_ratio: float, lo: float = param(0.35), hi: float = param(0.5)) -> bool:
    return lo <= debt_service_ratio < hi


def od_dti_band_3(debt_service_ratio: float, lo: float = param(0.5), hi: float = param(1.0)) -> bool:
    return lo <= debt_service_ratio < hi


def od_grade_1_share(grade: int, share: float = param(1.0)) -> float:
    return share if grade == 1 else 0.0


def od_grade_2_share(grade: int, share: float = param(0.85)) -> float:
    return share if grade == 2 else 0.0


def od_grade_3_share(grade: int, share: float = param(0.7)) -> float:
    return share if grade == 3 else 0.0


def od_grade_4_share(grade: int, share: float = param(0.55)) -> float:
    return share if grade == 4 else 0.0


def od_grade_share(od_grade_1_share: float, od_grade_2_share: float, od_grade_3_share: float, od_grade_4_share: float) -> float:
    return od_grade_1_share + od_grade_2_share + od_grade_3_share + od_grade_4_share


od_affordability = flow(
    od_instalment,
    od_stress_rate,
    od_stress_instalment,
    od_affordable_instalment,
    od_instalment_fits,
    od_max_affordable_amount,
    od_dti_band_0,
    od_dti_band_1,
    od_dti_band_2,
    od_dti_band_3,
    od_grade_1_share,
    od_grade_2_share,
    od_grade_3_share,
    od_grade_4_share,
    od_grade_share,
    name="affordability",
)
