"""Overdraft on a salary account. Limits: product caps and the offer.

Generated by make_bank.py; edit the generator, not this file."""
from decider import flow, param, step


def od_product_cap(grade: int, cap: float = param(50000.0)) -> float:
    return cap * (1.0 if grade <= 2 else 0.6)


def od_ltv_cap(requested_amount: float) -> float:
    return requested_amount


def od_income_cap(gross_income: float, multiple: float = param(1.0)) -> float:
    return gross_income * multiple


def od_max_amount(od_product_cap: float, od_ltv_cap: float, od_income_cap: float, od_max_affordable_amount: float, od_grade_share: float) -> float:
    return min(od_product_cap, od_ltv_cap, od_income_cap, od_max_affordable_amount) * od_grade_share


@step(output="offer_amount")
def od_offer_amount(requested_amount: float, od_max_amount: float, rounding: float = param(500.0)) -> float:
    return max(min(requested_amount, od_max_amount) // rounding * rounding, 0.0)


@step(output="offer_term")
def od_offer_term(requested_term: float) -> float:
    return requested_term


@step(output="offer_rate")
def od_offer_rate(od_rate: float) -> float:
    return od_rate


@step(output="monthly_instalment")
def od_offer_instalment(offer_amount: float, offer_term: float, od_monthly_rate: float, od_monthly_fee: float) -> float:
    return offer_amount * od_monthly_rate / (1 - (1 + od_monthly_rate) ** -offer_term) + od_monthly_fee if offer_amount > 0 else 0.0


@step(output="declined")
def od_declined(od_policy_declined: bool, od_instalment_fits: bool, offer_amount: float, minimum: float = param(2000.0)) -> bool:
    return od_policy_declined or offer_amount < minimum


@step(output="decline_reason")
def od_decline_reason(od_policy_reason: str, od_policy_declined: bool, declined: bool) -> str:
    return od_policy_reason if od_policy_declined else ("Offer below the product minimum" if declined else "")


od_limits = flow(
    od_product_cap,
    od_ltv_cap,
    od_income_cap,
    od_max_amount,
    od_offer_amount,
    od_offer_term,
    od_offer_rate,
    od_offer_instalment,
    od_declined,
    od_decline_reason,
    name="limits",
)
