"""Overdraft on a salary account. Pricing: the base rate by term, a loading by risk grade, fees by amount, capped by regulation.

Generated by make_bank.py; edit the generator, not this file."""
from decider import dag, flow, param, step
from decider.steps.tables import DecisionTableConfig

od_base_rates = DecisionTableConfig(
    name="od_base_rates",
    columns={"min_term": "Float64", "max_term": "Float64", "od_base_rate": "Float64"},
    rows={"table": "od_base_rates", "shared": True},
    expression={"type": "between", "variable": "requested_term", "lower_bound_column": "min_term", "upper_bound_column": "max_term"},
    outputs=["od_base_rate"],
)
od_risk_loadings = DecisionTableConfig(
    name="od_risk_loadings",
    columns={"grade_key": "Int64", "od_risk_loading": "Float64"},
    rows={"table": "od_risk_loadings", "shared": True},
    expression={"type": "eq", "variable": "grade", "value_column": "grade_key"},
    outputs=["od_risk_loading"],
)
od_fees = DecisionTableConfig(
    name="od_fees",
    columns={"min_amount": "Float64", "max_amount": "Float64", "od_initiation_fee": "Float64", "od_monthly_fee": "Float64"},
    rows={"table": "od_fees", "shared": True},
    expression={"type": "between", "variable": "requested_amount", "lower_bound_column": "min_amount", "upper_bound_column": "max_amount"},
    outputs=["od_initiation_fee", "od_monthly_fee"],
)


def od_salary_discount(salary_account: bool, discount: float = param(0.005)) -> float:
    return discount if salary_account else 0.0


def od_channel_discount(channel_discount: float, weight: float = param(1.0)) -> float:
    return channel_discount * weight


def od_loyalty_discount(months_at_address: float, discount: float = param(0.001)) -> float:
    return discount if months_at_address > 60 else 0.0


def od_clean_record_discount(clean_record: bool, discount: float = param(0.002)) -> float:
    return discount if clean_record else 0.0


def od_fraud_loading(fraud_referral: bool, loading: float = param(0.01)) -> float:
    return loading if fraud_referral else 0.0


def od_collections_loading(collections_band: int, per_band: float = param(0.0075)) -> float:
    return per_band * (collections_band - 1)


def od_raw_rate(od_base_rate: float, od_risk_loading: float, od_salary_discount: float, od_channel_discount: float, od_loyalty_discount: float, od_clean_record_discount: float, od_fraud_loading: float, od_collections_loading: float) -> float:
    return od_base_rate + od_risk_loading - od_salary_discount - od_channel_discount - od_loyalty_discount - od_clean_record_discount + od_fraud_loading + od_collections_loading


@step(output="od_rate")
def od_regulated_rate(od_raw_rate: float, repo_rate: float = param(0.0775, shared_key="repo_rate"),
                        cap_multiple: float = param(2.2), cap_margin: float = param(0.2)) -> float:
    """The National Credit Act cap: repo times a multiple plus a margin."""
    return min(od_raw_rate, repo_rate * cap_multiple + cap_margin)


def od_monthly_rate(od_rate: float) -> float:
    return od_rate / 12


od_pricing = flow(
    od_base_rates,
    od_risk_loadings,
    od_fees,
    od_salary_discount,
    od_channel_discount,
    od_loyalty_discount,
    od_clean_record_discount,
    od_fraud_loading,
    od_collections_loading,
    od_raw_rate,
    od_regulated_rate,
    od_monthly_rate,
    name="pricing",
)
