"""Overdraft on a salary account. Pricing: the base rate by term, a loading by risk grade, fees by amount, capped by regulation.

Generated by make_bank.py; edit the generator, not this file."""
from decider import dag, flow, param, step

from bank.lookup import LookupTable

od_base_rates = LookupTable(
    name="od_base_rates",
    ranges={"requested_term": ["min_term", "max_term"]},
    returns={"od_base_rate": "rate"},
    rows=[{"min_term": 1, "max_term": 12, "rate": 0.195}],
)
od_risk_loadings = LookupTable(
    name="od_risk_loadings",
    keys={"grade": "grade"},
    returns={"od_risk_loading": "loading"},
    rows=[{"grade": 1, "loading": 0.0}, {"grade": 2, "loading": 0.015}, {"grade": 3, "loading": 0.03}, {"grade": 4, "loading": 0.045}],
)
od_fees = LookupTable(
    name="od_fees",
    ranges={"requested_amount": ["min_amount", "max_amount"]},
    returns={"od_initiation_fee": "initiation_fee", "od_monthly_fee": "monthly_fee"},
    rows=[{"min_amount": 0, "max_amount": 10000, "initiation_fee": 165.0, "monthly_fee": 69.0}, {"min_amount": 10001, "max_amount": 50000, "initiation_fee": 690.0, "monthly_fee": 69.0}, {"min_amount": 50001, "max_amount": 10000000, "initiation_fee": 1207.5, "monthly_fee": 69.0}],
)


def od_salary_discount(salary_account: bool, discount: float = param(0.005)) -> float:
    return discount if salary_account else 0.0


def od_channel_discount(channel: str, app_discount: float = param(0.0025)) -> float:
    return app_discount if channel == "app" else 0.0


def od_loyalty_discount(months_at_address: float, discount: float = param(0.001)) -> float:
    return discount if months_at_address > 60 else 0.0


def od_clean_record_discount(clean_record: bool, discount: float = param(0.002)) -> float:
    return discount if clean_record else 0.0


def od_fraud_loading(fraud_referral: bool, loading: float = param(0.01)) -> float:
    return loading if fraud_referral else 0.0


def od_collections_loading(collections_band: int, per_band: float = param(0.0075)) -> float:
    return per_band * (collections_band - 1)


def od_raw_rate(od_base_rate: float, od_risk_loading: float, od_salary_discount: float, od_channel_discount: float, od_loyalty_discount: float, od_clean_record_discount: float, od_fraud_loading: float, od_collections_loading: float) -> float:
    return od_base_rate + od_risk_loading - od_salary_discount - od_channel_discount - od_loyalty_discount - od_clean_record_discount + od_fraud_loading + od_collections_loading


@step(output="od_rate")
def od_regulated_rate(od_raw_rate: float, repo_rate: float = param(0.0775, shared_key="repo_rate"),
                        cap_multiple: float = param(2.2), cap_margin: float = param(0.2)) -> float:
    """The National Credit Act cap: repo times a multiple plus a margin."""
    return min(od_raw_rate, repo_rate * cap_multiple + cap_margin)


def od_monthly_rate(od_rate: float) -> float:
    return od_rate / 12


od_pricing = flow(
    od_base_rates,
    od_risk_loadings,
    od_fees,
    od_salary_discount,
    od_channel_discount,
    od_loyalty_discount,
    od_clean_record_discount,
    od_fraud_loading,
    od_collections_loading,
    od_raw_rate,
    od_regulated_rate,
    od_monthly_rate,
    name="pricing",
)
