"""Overdraft on a salary account. Application scorecard: points per characteristic, summed into a score.

Generated by make_bank.py; edit the generator, not this file."""
from decider import flow, param, step


def od_pts_bureau_score(bureau_score: float, cut_1: float = param(0.03), cut_2: float = param(0.09), cut_3: float = param(0.36),
        pts_1: float = param(30.0), pts_2: float = param(-20.0), pts_3: float = param(-15.0), pts_4: float = param(0.0)) -> float:
    x = bureau_score
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def od_pts_months_employed(months_employed: float, cut_1: float = param(0.34), cut_2: float = param(0.48), cut_3: float = param(0.73),
        pts_1: float = param(30.0), pts_2: float = param(30.0), pts_3: float = param(40.0), pts_4: float = param(-20.0)) -> float:
    x = months_employed
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def od_pts_months_at_address(months_at_address: float, cut_1: float = param(0.41), cut_2: float = param(0.8), cut_3: float = param(0.83),
        pts_1: float = param(-5.0), pts_2: float = param(35.0), pts_3: float = param(0.0), pts_4: float = param(35.0)) -> float:
    x = months_at_address
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def od_pts_age(age: float, cut_1: float = param(0.11), cut_2: float = param(0.77), cut_3: float = param(0.83),
        pts_1: float = param(-5.0), pts_2: float = param(-20.0), pts_3: float = param(10.0), pts_4: float = param(20.0)) -> float:
    x = age
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def od_pts_debt_service_ratio(debt_service_ratio: float, cut_1: float = param(0.32), cut_2: float = param(0.41), cut_3: float = param(0.7),
        pts_1: float = param(-10.0), pts_2: float = param(-15.0), pts_3: float = param(10.0), pts_4: float = param(20.0)) -> float:
    x = debt_service_ratio
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def od_pts_card_utilisation(card_utilisation: float, cut_1: float = param(0.17), cut_2: float = param(0.49), cut_3: float = param(0.86),
        pts_1: float = param(35.0), pts_2: float = param(10.0), pts_3: float = param(25.0), pts_4: float = param(-20.0)) -> float:
    x = card_utilisation
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def od_pts_enquiries_6m(enquiries_6m: float, cut_1: float = param(0.01), cut_2: float = param(0.5), cut_3: float = param(0.89),
        pts_1: float = param(-10.0), pts_2: float = param(0.0), pts_3: float = param(20.0), pts_4: float = param(10.0)) -> float:
    x = enquiries_6m
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def od_pts_missed_payments_12m(missed_payments_12m: float, cut_1: float = param(0.2), cut_2: float = param(0.22), cut_3: float = param(0.65),
        pts_1: float = param(25.0), pts_2: float = param(30.0), pts_3: float = param(-10.0), pts_4: float = param(20.0)) -> float:
    x = missed_payments_12m
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def od_pts_dependants(dependants: float, cut_1: float = param(0.24), cut_2: float = param(0.59), cut_3: float = param(0.9),
        pts_1: float = param(-15.0), pts_2: float = param(25.0), pts_3: float = param(5.0), pts_4: float = param(25.0)) -> float:
    x = dependants
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def od_pts_disposable_income(disposable_income: float, cut_1: float = param(0.26), cut_2: float = param(0.82), cut_3: float = param(0.86),
        pts_1: float = param(-20.0), pts_2: float = param(-5.0), pts_3: float = param(30.0), pts_4: float = param(30.0)) -> float:
    x = disposable_income
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def od_pts_expenses_to_net_income(expenses_to_net_income: float, cut_1: float = param(0.22), cut_2: float = param(0.3), cut_3: float = param(0.41),
        pts_1: float = param(10.0), pts_2: float = param(30.0), pts_3: float = param(10.0), pts_4: float = param(40.0)) -> float:
    x = expenses_to_net_income
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def od_pts_requested_amount_to_gross_income(requested_amount_to_gross_income: float, cut_1: float = param(0.39), cut_2: float = param(0.49), cut_3: float = param(0.71),
        pts_1: float = param(-15.0), pts_2: float = param(40.0), pts_3: float = param(40.0), pts_4: float = param(15.0)) -> float:
    x = requested_amount_to_gross_income
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def od_pts_existing_instalments_to_net_income(existing_instalments_to_net_income: float, cut_1: float = param(0.4), cut_2: float = param(0.88), cut_3: float = param(0.91),
        pts_1: float = param(10.0), pts_2: float = param(0.0), pts_3: float = param(15.0), pts_4: float = param(10.0)) -> float:
    x = existing_instalments_to_net_income
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def od_pts_net_income(net_income: float, cut_1: float = param(0.69), cut_2: float = param(0.82), cut_3: float = param(0.84),
        pts_1: float = param(30.0), pts_2: float = param(20.0), pts_3: float = param(35.0), pts_4: float = param(10.0)) -> float:
    x = net_income
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def od_pts_gross_income(gross_income: float, cut_1: float = param(0.38), cut_2: float = param(0.52), cut_3: float = param(0.73),
        pts_1: float = param(-10.0), pts_2: float = param(-10.0), pts_3: float = param(35.0), pts_4: float = param(40.0)) -> float:
    x = gross_income
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def od_pts_judgements(judgements: float, cut_1: float = param(0.23), cut_2: float = param(0.74), cut_3: float = param(0.82),
        pts_1: float = param(10.0), pts_2: float = param(-10.0), pts_3: float = param(-10.0), pts_4: float = param(10.0)) -> float:
    x = judgements
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def od_pts_months_employed_to_age(months_employed_to_age: float, cut_1: float = param(0.35), cut_2: float = param(0.47), cut_3: float = param(0.67),
        pts_1: float = param(40.0), pts_2: float = param(15.0), pts_3: float = param(-15.0), pts_4: float = param(0.0)) -> float:
    x = months_employed_to_age
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def od_pts_enquiries_6m_to_months_at_address(enquiries_6m_to_months_at_address: float, cut_1: float = param(0.75), cut_2: float = param(0.83), cut_3: float = param(0.89),
        pts_1: float = param(30.0), pts_2: float = param(-5.0), pts_3: float = param(40.0), pts_4: float = param(5.0)) -> float:
    x = enquiries_6m_to_months_at_address
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def od_pts_card_utilisation_to_bureau_score(card_utilisation_to_bureau_score: float, cut_1: float = param(0.09), cut_2: float = param(0.2), cut_3: float = param(0.35),
        pts_1: float = param(25.0), pts_2: float = param(-5.0), pts_3: float = param(-20.0), pts_4: float = param(35.0)) -> float:
    x = card_utilisation_to_bureau_score
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def od_pts_expenses_to_gross_income(expenses_to_gross_income: float, cut_1: float = param(0.45), cut_2: float = param(0.54), cut_3: float = param(0.83),
        pts_1: float = param(-15.0), pts_2: float = param(25.0), pts_3: float = param(15.0), pts_4: float = param(20.0)) -> float:
    x = expenses_to_gross_income
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def od_pts_net_income_zscore(net_income_zscore: float, cut_1: float = param(0.02), cut_2: float = param(0.59), cut_3: float = param(0.61),
        pts_1: float = param(-5.0), pts_2: float = param(-20.0), pts_3: float = param(30.0), pts_4: float = param(-20.0)) -> float:
    x = net_income_zscore
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def od_pts_bureau_score_zscore(bureau_score_zscore: float, cut_1: float = param(0.44), cut_2: float = param(0.77), cut_3: float = param(0.87),
        pts_1: float = param(30.0), pts_2: float = param(-15.0), pts_3: float = param(5.0), pts_4: float = param(-15.0)) -> float:
    x = bureau_score_zscore
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def od_score(od_pts_bureau_score: float, od_pts_months_employed: float, od_pts_months_at_address: float, od_pts_age: float, od_pts_debt_service_ratio: float, od_pts_card_utilisation: float, od_pts_enquiries_6m: float, od_pts_missed_payments_12m: float, od_pts_dependants: float, od_pts_disposable_income: float, od_pts_expenses_to_net_income: float, od_pts_requested_amount_to_gross_income: float, od_pts_existing_instalments_to_net_income: float, od_pts_net_income: float, od_pts_gross_income: float, od_pts_judgements: float, od_pts_months_employed_to_age: float, od_pts_enquiries_6m_to_months_at_address: float, od_pts_card_utilisation_to_bureau_score: float, od_pts_expenses_to_gross_income: float, od_pts_net_income_zscore: float, od_pts_bureau_score_zscore: float, intercept: float = param(600.0)) -> float:
    return intercept + od_pts_bureau_score + od_pts_months_employed + od_pts_months_at_address + od_pts_age + od_pts_debt_service_ratio + od_pts_card_utilisation + od_pts_enquiries_6m + od_pts_missed_payments_12m + od_pts_dependants + od_pts_disposable_income + od_pts_expenses_to_net_income + od_pts_requested_amount_to_gross_income + od_pts_existing_instalments_to_net_income + od_pts_net_income + od_pts_gross_income + od_pts_judgements + od_pts_months_employed_to_age + od_pts_enquiries_6m_to_months_at_address + od_pts_card_utilisation_to_bureau_score + od_pts_expenses_to_gross_income + od_pts_net_income_zscore + od_pts_bureau_score_zscore


def od_score_band(od_score: float, low: float = param(580.0), high: float = param(680.0)) -> int:
    return 3 if od_score < low else (2 if od_score < high else 1)


od_scorecard = flow(
    od_pts_bureau_score,
    od_pts_months_employed,
    od_pts_months_at_address,
    od_pts_age,
    od_pts_debt_service_ratio,
    od_pts_card_utilisation,
    od_pts_enquiries_6m,
    od_pts_missed_payments_12m,
    od_pts_dependants,
    od_pts_disposable_income,
    od_pts_expenses_to_net_income,
    od_pts_requested_amount_to_gross_income,
    od_pts_existing_instalments_to_net_income,
    od_pts_net_income,
    od_pts_gross_income,
    od_pts_judgements,
    od_pts_months_employed_to_age,
    od_pts_enquiries_6m_to_months_at_address,
    od_pts_card_utilisation_to_bureau_score,
    od_pts_expenses_to_gross_income,
    od_pts_net_income_zscore,
    od_pts_bureau_score_zscore,
    od_score,
    od_score_band,
    name="scorecard",
)
