"""Overdraft on a salary account. Stress tests: the instalment under rate shocks, and whether it still fits.

Generated by make_bank.py; edit the generator, not this file."""
from decider import flow, param, step


def od_shock_25bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.0025)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_25bp_fits(od_shock_25bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_25bp_instalment <= od_affordable_instalment


def od_shock_50bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.005)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_50bp_fits(od_shock_50bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_50bp_instalment <= od_affordable_instalment


def od_shock_75bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.0075)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_75bp_fits(od_shock_75bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_75bp_instalment <= od_affordable_instalment


def od_shock_100bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.01)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_100bp_fits(od_shock_100bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_100bp_instalment <= od_affordable_instalment


def od_shock_125bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.0125)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_125bp_fits(od_shock_125bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_125bp_instalment <= od_affordable_instalment


def od_shock_150bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.015)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_150bp_fits(od_shock_150bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_150bp_instalment <= od_affordable_instalment


def od_shock_175bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.0175)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_175bp_fits(od_shock_175bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_175bp_instalment <= od_affordable_instalment


def od_shock_200bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.02)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_200bp_fits(od_shock_200bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_200bp_instalment <= od_affordable_instalment


def od_shock_225bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.0225)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_225bp_fits(od_shock_225bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_225bp_instalment <= od_affordable_instalment


def od_shock_250bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.025)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_250bp_fits(od_shock_250bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_250bp_instalment <= od_affordable_instalment


def od_shock_275bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.0275)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_275bp_fits(od_shock_275bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_275bp_instalment <= od_affordable_instalment


def od_shock_300bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.03)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_300bp_fits(od_shock_300bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_300bp_instalment <= od_affordable_instalment


def od_shock_325bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.0325)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_325bp_fits(od_shock_325bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_325bp_instalment <= od_affordable_instalment


def od_shock_350bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.035)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_350bp_fits(od_shock_350bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_350bp_instalment <= od_affordable_instalment


def od_shock_375bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.0375)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_375bp_fits(od_shock_375bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_375bp_instalment <= od_affordable_instalment


def od_shock_400bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.04)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_400bp_fits(od_shock_400bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_400bp_instalment <= od_affordable_instalment


def od_shock_425bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.0425)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_425bp_fits(od_shock_425bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_425bp_instalment <= od_affordable_instalment


def od_shock_450bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.045)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_450bp_fits(od_shock_450bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_450bp_instalment <= od_affordable_instalment


def od_shock_475bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.0475)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_475bp_fits(od_shock_475bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_475bp_instalment <= od_affordable_instalment


def od_shock_500bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.05)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_500bp_fits(od_shock_500bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_500bp_instalment <= od_affordable_instalment


def od_shock_525bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.0525)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_525bp_fits(od_shock_525bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_525bp_instalment <= od_affordable_instalment


def od_shock_550bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.055)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_550bp_fits(od_shock_550bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_550bp_instalment <= od_affordable_instalment


def od_shock_575bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.0575)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_575bp_fits(od_shock_575bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_575bp_instalment <= od_affordable_instalment


def od_shock_600bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.06)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_600bp_fits(od_shock_600bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_600bp_instalment <= od_affordable_instalment


def od_shock_625bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.0625)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_625bp_fits(od_shock_625bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_625bp_instalment <= od_affordable_instalment


def od_shock_650bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.065)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_650bp_fits(od_shock_650bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_650bp_instalment <= od_affordable_instalment


def od_shock_675bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.0675)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_675bp_fits(od_shock_675bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_675bp_instalment <= od_affordable_instalment


def od_shock_700bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.07)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_700bp_fits(od_shock_700bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_700bp_instalment <= od_affordable_instalment


def od_shock_725bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.0725)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_725bp_fits(od_shock_725bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_725bp_instalment <= od_affordable_instalment


def od_shock_750bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.075)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_750bp_fits(od_shock_750bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_750bp_instalment <= od_affordable_instalment


def od_shock_775bp_instalment(requested_amount: float, requested_term: float, od_rate: float, shock: float = param(0.0775)) -> float:
    r = (od_rate + shock) / 12
    return requested_amount * r / (1 - (1 + r) ** -requested_term)


def od_shock_775bp_fits(od_shock_775bp_instalment: float, od_affordable_instalment: float) -> bool:
    return od_shock_775bp_instalment <= od_affordable_instalment


od_stress = flow(
    od_shock_25bp_instalment,
    od_shock_25bp_fits,
    od_shock_50bp_instalment,
    od_shock_50bp_fits,
    od_shock_75bp_instalment,
    od_shock_75bp_fits,
    od_shock_100bp_instalment,
    od_shock_100bp_fits,
    od_shock_125bp_instalment,
    od_shock_125bp_fits,
    od_shock_150bp_instalment,
    od_shock_150bp_fits,
    od_shock_175bp_instalment,
    od_shock_175bp_fits,
    od_shock_200bp_instalment,
    od_shock_200bp_fits,
    od_shock_225bp_instalment,
    od_shock_225bp_fits,
    od_shock_250bp_instalment,
    od_shock_250bp_fits,
    od_shock_275bp_instalment,
    od_shock_275bp_fits,
    od_shock_300bp_instalment,
    od_shock_300bp_fits,
    od_shock_325bp_instalment,
    od_shock_325bp_fits,
    od_shock_350bp_instalment,
    od_shock_350bp_fits,
    od_shock_375bp_instalment,
    od_shock_375bp_fits,
    od_shock_400bp_instalment,
    od_shock_400bp_fits,
    od_shock_425bp_instalment,
    od_shock_425bp_fits,
    od_shock_450bp_instalment,
    od_shock_450bp_fits,
    od_shock_475bp_instalment,
    od_shock_475bp_fits,
    od_shock_500bp_instalment,
    od_shock_500bp_fits,
    od_shock_525bp_instalment,
    od_shock_525bp_fits,
    od_shock_550bp_instalment,
    od_shock_550bp_fits,
    od_shock_575bp_instalment,
    od_shock_575bp_fits,
    od_shock_600bp_instalment,
    od_shock_600bp_fits,
    od_shock_625bp_instalment,
    od_shock_625bp_fits,
    od_shock_650bp_instalment,
    od_shock_650bp_fits,
    od_shock_675bp_instalment,
    od_shock_675bp_fits,
    od_shock_700bp_instalment,
    od_shock_700bp_fits,
    od_shock_725bp_instalment,
    od_shock_725bp_fits,
    od_shock_750bp_instalment,
    od_shock_750bp_fits,
    od_shock_775bp_instalment,
    od_shock_775bp_fits,
    name="stress_tests",
)
