"""Decision trees, loaded from their JSON documents.

Generated by make_bank.py; edit the generator, not this file."""
from pathlib import Path

from decider.steps.trees import TreeConfig

_HERE = Path(__file__).parent
bureau_grade = TreeConfig.load((_HERE / "bureau_grade.json").read_text())
fraud_screen = TreeConfig.load((_HERE / "fraud_screen.json").read_text())
collections_risk = TreeConfig.load((_HERE / "collections_risk.json").read_text())
