"""Suppressions — spec §5.2, and the answer to §13 Q13.

Thirty-four suppressions, three scopes (all campaigns / one campaign / one
channel of one campaign), two classes (absolute / measurement-relevant), and the
requirement that **every** suppression that applied is attributable, not the
first one.

The shape: a `ruleset` interior (doc 08 §3) whose writes are **bitmasks**, not
booleans.

    supp_mask_global   uint64   bit i set  <=>  suppression with bit_index i applied
    supp_mask_sms      uint32
    supp_mask_call     uint32
    supp_mask_email    uint32
    supp_mask_inapp    uint32

One int64 column carries all 34 answers for a client, which is what makes "a
client suppressed by four rules shows four" free rather than four times the
storage.  The warehouse explodes it against a bit dictionary published from the
registry — the same trick as `route_node`, and deliberately the same trick, so
the analytics team learns one pattern:

    SELECT b.suppression_code, count(*)
    FROM   suppression_facts f
    JOIN   suppression_bit b
           ON  b.registry_version = f.registry_version
           AND (f.supp_mask_global >> b.bit_index) & 1 = 1
    GROUP  BY b.suppression_code;

THE ABSOLUTE / MEASUREMENT SPLIT IS A PARAMS VALUE, NOT A STRUCTURE
--------------------------------------------------------------------
Spec §5.2 req 3: absolute suppressions (S01 deceased, S11 fraud, S14 do-not-target)
skip evaluation entirely; measurement-relevant ones (S07 opt-out, S23 already
held, S30 fatigue) must still be evaluated through the tree and path-recorded,
because the analytics team reports the population that *would* have been
targeted.  Which class a suppression is in is an attribute of the registry,
changeable by Compliance.

We express the gate as one comparison against a mask:

    if supp_mask_global & params.absolute_mask:  skip the tree

`absolute_mask` is a uint64 **params value** derived from the registry.  So
Compliance reclassifying S23 from measurement to absolute is a values change:
no compile, no staged swap, no engineer, bounded by a validator, and the value
lands in the params digest so "which suppressions were absolute in the March
cycle" is answerable from the audit record (doc 08 §8).  This is doc 03 §4
working exactly as advertised on a requirement it was not designed for, and it
is the cleanest win in this sketch.
"""

from __future__ import annotations

import polars as pl

from decider2 import Branch, param, ruleset, step

from .steps import ScopedSuppressions, in_cooling_off, product_held_at_or_above_tier


# --- the registry-driven part: 34 predicates, authored by Compliance ---------
GlobalSuppressions = ruleset(
    name="suppressions_global",
    reads=["feature:*", "consent:*", "eligibility:*"],
    writes=["supp_mask_global"],
    interior="registries/suppressions.json",
    output_kind="flags",              # int64 + a published bit dictionary; DEMANDS #20
    flag_dictionary="warehouse/suppression_bit.csv",
    partition="record",
)

ChannelSuppressions = ruleset(
    name="suppressions_channel",
    reads=["feature:*", "consent:*"],
    writes=["supp_mask_sms", "supp_mask_call", "supp_mask_email", "supp_mask_inapp"],
    interior="registries/suppressions.json",
    output_kind="flags",
    partition="record",
)


# --- the gate.  Declared in the skeleton, valued from the registry. ----------
def is_absolutely_suppressed(
    supp_mask_global: int,
    absolute_mask: int = param(
        0x0000_0000_0000_2411,
        description="Bitmask of suppressions that stop evaluation. Owner: Compliance. "
                    "Derived from registries/suppressions.json; regenerated by "
                    "`decider registry masks`.",
    ),
) -> bool:
    """True when the client must not be evaluated at all for this campaign."""
    pass  # return (supp_mask_global & absolute_mask) != 0


NoEvaluation = ...   # a module writing the tree's outputs as "not evaluated" sentinels

EvaluationGate = Branch(
    is_absolutely_suppressed,
    NoEvaluation,                       # arm for True  — S01, S11, S14: no path exists
    "CampaignTreeStage",                # arm for False — everything else evaluates
    modifies=["leaf_key", "route_digest", "leaf_outcome_code", "offer_tier_code",
              "advertised_amount_cents", "priority_weight", "reason_label"],
)
