"""Personal loan: unsecured, 6 to 84 months.

Generated by make_bank.py; edit the generator, not this file."""
from decider import flow

from bank.products.personal_loan.affordability import pl_affordability
from bank.products.personal_loan.limits import pl_limits
from bank.products.personal_loan.policy import pl_policy
from bank.products.personal_loan.pricing import pl_pricing
from bank.products.personal_loan.scorecard import pl_scorecard
from bank.products.personal_loan.stress import pl_stress

personal_loan = flow(pl_scorecard, pl_policy, pl_pricing, pl_affordability, pl_stress, pl_limits, name="personal_loan")
