"""Personal loan: unsecured, 6 to 84 months. Affordability: the instalment at the offered and a stressed rate against disposable income.

Generated by make_bank.py; edit the generator, not this file."""
from decider import flow, param, step


def pl_instalment(requested_amount: float, requested_term: float, pl_monthly_rate: float, pl_monthly_fee: float) -> float:
    return requested_amount * pl_monthly_rate / (1 - (1 + pl_monthly_rate) ** -requested_term) + pl_monthly_fee


def pl_stress_rate(pl_rate: float, buffer: float = param(0.03)) -> float:
    return pl_rate + buffer


def pl_stress_instalment(requested_amount: float, requested_term: float, pl_stress_rate: float) -> float:
    return requested_amount * (pl_stress_rate / 12) / (1 - (1 + pl_stress_rate / 12) ** -requested_term)


def pl_affordable_instalment(disposable_income_buffered: float, share: float = param(0.5)) -> float:
    return max(disposable_income_buffered * share, 0.0)


def pl_instalment_fits(pl_stress_instalment: float, pl_affordable_instalment: float) -> bool:
    return pl_stress_instalment <= pl_affordable_instalment


def pl_max_affordable_amount(pl_affordable_instalment: float, requested_term: float, pl_stress_rate: float) -> float:
    return pl_affordable_instalment * (1 - (1 + pl_stress_rate / 12) ** -requested_term) / (pl_stress_rate / 12)


def pl_dti_band_0(debt_service_ratio: float, lo: float = param(0), hi: float = param(0.2)) -> bool:
    return lo <= debt_service_ratio < hi


def pl_dti_band_1(debt_service_ratio: float, lo: float = param(0.2), hi: float = param(0.35)) -> bool:
    return lo <= debt_service_ratio < hi


def pl_dti_band_2(debt_service_ratio: float, lo: float = param(0.35), hi: float = param(0.5)) -> bool:
    return lo <= debt_service_ratio < hi


def pl_dti_band_3(debt_service_ratio: float, lo: float = param(0.5), hi: float = param(1.0)) -> bool:
    return lo <= debt_service_ratio < hi


def pl_grade_1_share(grade: int, share: float = param(1.0)) -> float:
    return share if grade == 1 else 0.0


def pl_grade_2_share(grade: int, share: float = param(0.85)) -> float:
    return share if grade == 2 else 0.0


def pl_grade_3_share(grade: int, share: float = param(0.7)) -> float:
    return share if grade == 3 else 0.0


def pl_grade_4_share(grade: int, share: float = param(0.55)) -> float:
    return share if grade == 4 else 0.0


def pl_grade_share(pl_grade_1_share: float, pl_grade_2_share: float, pl_grade_3_share: float, pl_grade_4_share: float) -> float:
    return pl_grade_1_share + pl_grade_2_share + pl_grade_3_share + pl_grade_4_share


pl_affordability = flow(
    pl_instalment,
    pl_stress_rate,
    pl_stress_instalment,
    pl_affordable_instalment,
    pl_instalment_fits,
    pl_max_affordable_amount,
    pl_dti_band_0,
    pl_dti_band_1,
    pl_dti_band_2,
    pl_dti_band_3,
    pl_grade_1_share,
    pl_grade_2_share,
    pl_grade_3_share,
    pl_grade_4_share,
    pl_grade_share,
    name="affordability",
)
