"""Personal loan: unsecured, 6 to 84 months. Limits: product caps and the offer.

Generated by make_bank.py; edit the generator, not this file."""
from decider import flow, param, step


def pl_product_cap(grade: int, cap: float = param(350000.0)) -> float:
    return cap * (1.0 if grade <= 2 else 0.6)


def pl_ltv_cap(requested_amount: float) -> float:
    return requested_amount


def pl_income_cap(gross_income: float, multiple: float = param(4.0)) -> float:
    return gross_income * multiple


def pl_max_amount(pl_product_cap: float, pl_ltv_cap: float, pl_income_cap: float, pl_max_affordable_amount: float, pl_grade_share: float) -> float:
    return min(pl_product_cap, pl_ltv_cap, pl_income_cap, pl_max_affordable_amount) * pl_grade_share


@step(output="offer_amount")
def pl_offer_amount(requested_amount: float, pl_max_amount: float, rounding: float = param(500.0)) -> float:
    return max(min(requested_amount, pl_max_amount) // rounding * rounding, 0.0)


@step(output="offer_term")
def pl_offer_term(requested_term: float) -> float:
    return requested_term


@step(output="offer_rate")
def pl_offer_rate(pl_rate: float) -> float:
    return pl_rate


@step(output="monthly_instalment")
def pl_offer_instalment(offer_amount: float, offer_term: float, pl_monthly_rate: float, pl_monthly_fee: float) -> float:
    return offer_amount * pl_monthly_rate / (1 - (1 + pl_monthly_rate) ** -offer_term) + pl_monthly_fee if offer_amount > 0 else 0.0


@step(output="declined")
def pl_declined(pl_policy_declined: bool, pl_instalment_fits: bool, offer_amount: float, minimum: float = param(2000.0)) -> bool:
    return pl_policy_declined or offer_amount < minimum


@step(output="decline_reason")
def pl_decline_reason(pl_policy_reason: str, pl_policy_declined: bool, declined: bool) -> str:
    return pl_policy_reason if pl_policy_declined else ("Offer below the product minimum" if declined else "")


pl_limits = flow(
    pl_product_cap,
    pl_ltv_cap,
    pl_income_cap,
    pl_max_amount,
    pl_offer_amount,
    pl_offer_term,
    pl_offer_rate,
    pl_offer_instalment,
    pl_declined,
    pl_decline_reason,
    name="limits",
)
