"""Personal loan: unsecured, 6 to 84 months. Pricing: the base rate by term, a loading by risk grade, fees by amount, capped by regulation.

Generated by make_bank.py; edit the generator, not this file."""
from decider import dag, flow, param, step
from decider.steps.tables import DecisionTableConfig

pl_base_rates = DecisionTableConfig(
    name="pl_base_rates",
    columns={"min_term": "Float64", "max_term": "Float64", "pl_base_rate": "Float64"},
    rows={"table": "pl_base_rates", "shared": True},
    expression={"type": "between", "variable": "requested_term", "lower_bound_column": "min_term", "upper_bound_column": "max_term"},
    outputs=["pl_base_rate"],
)
pl_risk_loadings = DecisionTableConfig(
    name="pl_risk_loadings",
    columns={"grade_key": "Int64", "pl_risk_loading": "Float64"},
    rows={"table": "pl_risk_loadings", "shared": True},
    expression={"type": "eq", "variable": "grade", "value_column": "grade_key"},
    outputs=["pl_risk_loading"],
)
pl_fees = DecisionTableConfig(
    name="pl_fees",
    columns={"min_amount": "Float64", "max_amount": "Float64", "pl_initiation_fee": "Float64", "pl_monthly_fee": "Float64"},
    rows={"table": "pl_fees", "shared": True},
    expression={"type": "between", "variable": "requested_amount", "lower_bound_column": "min_amount", "upper_bound_column": "max_amount"},
    outputs=["pl_initiation_fee", "pl_monthly_fee"],
)


def pl_salary_discount(salary_account: bool, discount: float = param(0.005)) -> float:
    return discount if salary_account else 0.0


def pl_channel_discount(channel_discount: float, weight: float = param(1.0)) -> float:
    return channel_discount * weight


def pl_loyalty_discount(months_at_address: float, discount: float = param(0.001)) -> float:
    return discount if months_at_address > 60 else 0.0


def pl_clean_record_discount(clean_record: bool, discount: float = param(0.002)) -> float:
    return discount if clean_record else 0.0


def pl_fraud_loading(fraud_referral: bool, loading: float = param(0.01)) -> float:
    return loading if fraud_referral else 0.0


def pl_collections_loading(collections_band: int, per_band: float = param(0.0075)) -> float:
    return per_band * (collections_band - 1)


def pl_raw_rate(pl_base_rate: float, pl_risk_loading: float, pl_salary_discount: float, pl_channel_discount: float, pl_loyalty_discount: float, pl_clean_record_discount: float, pl_fraud_loading: float, pl_collections_loading: float) -> float:
    return pl_base_rate + pl_risk_loading - pl_salary_discount - pl_channel_discount - pl_loyalty_discount - pl_clean_record_discount + pl_fraud_loading + pl_collections_loading


@step(output="pl_rate")
def pl_regulated_rate(pl_raw_rate: float, repo_rate: float = param(0.0775, shared_key="repo_rate"),
                        cap_multiple: float = param(1.0), cap_margin: float = param(0.21)) -> float:
    """The National Credit Act cap: repo plus 21% for unsecured credit, 12% for mortgages."""
    return min(pl_raw_rate, repo_rate * cap_multiple + cap_margin)


@step(output="pl_rate")
def pl_rate_floor(pl_rate: float, repo_rate: float = param(0.0775, shared_key="repo_rate"),
                  margin: float = param(0.03)) -> float:
    """Never price below repo plus a margin."""
    return max(pl_rate, repo_rate + margin)


def pl_monthly_rate(pl_rate: float) -> float:
    return pl_rate / 12


pl_pricing = flow(
    pl_base_rates,
    pl_risk_loadings,
    pl_fees,
    pl_salary_discount,
    pl_channel_discount,
    pl_loyalty_discount,
    pl_clean_record_discount,
    pl_fraud_loading,
    pl_collections_loading,
    pl_raw_rate,
    pl_regulated_rate,
    pl_rate_floor,
    pl_monthly_rate,
    name="pricing",
)
