"""Personal loan: unsecured, 6 to 84 months. Pricing: the base rate by term, a loading by risk grade, fees by amount, capped by regulation.

Generated by make_bank.py; edit the generator, not this file."""
from decider import dag, flow, param, step

from bank.lookup import LookupTable

pl_base_rates = LookupTable(
    name="pl_base_rates",
    ranges={"requested_term": ["min_term", "max_term"]},
    returns={"pl_base_rate": "rate"},
    rows=[{"min_term": 6, "max_term": 24, "rate": 0.215}, {"min_term": 25, "max_term": 48, "rate": 0.235}, {"min_term": 49, "max_term": 84, "rate": 0.255}],
)
pl_risk_loadings = LookupTable(
    name="pl_risk_loadings",
    keys={"grade": "grade"},
    returns={"pl_risk_loading": "loading"},
    rows=[{"grade": 1, "loading": 0.0}, {"grade": 2, "loading": 0.015}, {"grade": 3, "loading": 0.03}, {"grade": 4, "loading": 0.045}],
)
pl_fees = LookupTable(
    name="pl_fees",
    ranges={"requested_amount": ["min_amount", "max_amount"]},
    returns={"pl_initiation_fee": "initiation_fee", "pl_monthly_fee": "monthly_fee"},
    rows=[{"min_amount": 0, "max_amount": 10000, "initiation_fee": 165.0, "monthly_fee": 69.0}, {"min_amount": 10001, "max_amount": 50000, "initiation_fee": 690.0, "monthly_fee": 69.0}, {"min_amount": 50001, "max_amount": 10000000, "initiation_fee": 1207.5, "monthly_fee": 69.0}],
)


def pl_salary_discount(salary_account: bool, discount: float = param(0.005)) -> float:
    return discount if salary_account else 0.0


def pl_channel_discount(channel: str, app_discount: float = param(0.0025)) -> float:
    return app_discount if channel == "app" else 0.0


def pl_loyalty_discount(months_at_address: float, discount: float = param(0.001)) -> float:
    return discount if months_at_address > 60 else 0.0


def pl_clean_record_discount(clean_record: bool, discount: float = param(0.002)) -> float:
    return discount if clean_record else 0.0


def pl_fraud_loading(fraud_referral: bool, loading: float = param(0.01)) -> float:
    return loading if fraud_referral else 0.0


def pl_collections_loading(collections_band: int, per_band: float = param(0.0075)) -> float:
    return per_band * (collections_band - 1)


def pl_raw_rate(pl_base_rate: float, pl_risk_loading: float, pl_salary_discount: float, pl_channel_discount: float, pl_loyalty_discount: float, pl_clean_record_discount: float, pl_fraud_loading: float, pl_collections_loading: float) -> float:
    return pl_base_rate + pl_risk_loading - pl_salary_discount - pl_channel_discount - pl_loyalty_discount - pl_clean_record_discount + pl_fraud_loading + pl_collections_loading


@step(output="pl_rate")
def pl_regulated_rate(pl_raw_rate: float, repo_rate: float = param(0.0775, shared_key="repo_rate"),
                        cap_multiple: float = param(2.2), cap_margin: float = param(0.2)) -> float:
    """The National Credit Act cap: repo times a multiple plus a margin."""
    return min(pl_raw_rate, repo_rate * cap_multiple + cap_margin)


def pl_monthly_rate(pl_rate: float) -> float:
    return pl_rate / 12


pl_pricing = flow(
    pl_base_rates,
    pl_risk_loadings,
    pl_fees,
    pl_salary_discount,
    pl_channel_discount,
    pl_loyalty_discount,
    pl_clean_record_discount,
    pl_fraud_loading,
    pl_collections_loading,
    pl_raw_rate,
    pl_regulated_rate,
    pl_monthly_rate,
    name="pricing",
)
