"""Personal loan: unsecured, 6 to 84 months. Application scorecard: points per characteristic, summed into a score.

Generated by make_bank.py; edit the generator, not this file."""
from decider import flow, param, step


def pl_pts_bureau_score(bureau_score: float, cut_1: float = param(0.34), cut_2: float = param(0.64), cut_3: float = param(0.72),
        pts_1: float = param(-10.0), pts_2: float = param(-15.0), pts_3: float = param(-5.0), pts_4: float = param(0.0)) -> float:
    x = bureau_score
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def pl_pts_months_employed(months_employed: float, cut_1: float = param(0.07), cut_2: float = param(0.48), cut_3: float = param(0.54),
        pts_1: float = param(40.0), pts_2: float = param(15.0), pts_3: float = param(-20.0), pts_4: float = param(0.0)) -> float:
    x = months_employed
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def pl_pts_months_at_address(months_at_address: float, cut_1: float = param(0.14), cut_2: float = param(0.26), cut_3: float = param(0.32),
        pts_1: float = param(0.0), pts_2: float = param(-10.0), pts_3: float = param(25.0), pts_4: float = param(20.0)) -> float:
    x = months_at_address
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def pl_pts_age(age: float, cut_1: float = param(0.23), cut_2: float = param(0.7), cut_3: float = param(0.98),
        pts_1: float = param(15.0), pts_2: float = param(0.0), pts_3: float = param(30.0), pts_4: float = param(15.0)) -> float:
    x = age
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def pl_pts_debt_service_ratio(debt_service_ratio: float, cut_1: float = param(0.08), cut_2: float = param(0.29), cut_3: float = param(0.94),
        pts_1: float = param(10.0), pts_2: float = param(-10.0), pts_3: float = param(-10.0), pts_4: float = param(0.0)) -> float:
    x = debt_service_ratio
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def pl_pts_card_utilisation(card_utilisation: float, cut_1: float = param(0.4), cut_2: float = param(0.85), cut_3: float = param(0.98),
        pts_1: float = param(0.0), pts_2: float = param(-20.0), pts_3: float = param(5.0), pts_4: float = param(-20.0)) -> float:
    x = card_utilisation
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def pl_pts_enquiries_6m(enquiries_6m: float, cut_1: float = param(0.07), cut_2: float = param(0.43), cut_3: float = param(0.71),
        pts_1: float = param(30.0), pts_2: float = param(35.0), pts_3: float = param(5.0), pts_4: float = param(40.0)) -> float:
    x = enquiries_6m
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def pl_pts_missed_payments_12m(missed_payments_12m: float, cut_1: float = param(0.27), cut_2: float = param(0.45), cut_3: float = param(0.78),
        pts_1: float = param(25.0), pts_2: float = param(35.0), pts_3: float = param(30.0), pts_4: float = param(-20.0)) -> float:
    x = missed_payments_12m
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def pl_pts_dependants(dependants: float, cut_1: float = param(0.39), cut_2: float = param(0.62), cut_3: float = param(0.69),
        pts_1: float = param(5.0), pts_2: float = param(40.0), pts_3: float = param(25.0), pts_4: float = param(0.0)) -> float:
    x = dependants
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def pl_pts_disposable_income(disposable_income: float, cut_1: float = param(0.21), cut_2: float = param(0.37), cut_3: float = param(0.45),
        pts_1: float = param(-10.0), pts_2: float = param(-5.0), pts_3: float = param(15.0), pts_4: float = param(35.0)) -> float:
    x = disposable_income
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def pl_pts_expenses_to_net_income(expenses_to_net_income: float, cut_1: float = param(0.18), cut_2: float = param(0.39), cut_3: float = param(0.41),
        pts_1: float = param(10.0), pts_2: float = param(-20.0), pts_3: float = param(-5.0), pts_4: float = param(-5.0)) -> float:
    x = expenses_to_net_income
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def pl_pts_requested_amount_to_gross_income(requested_amount_to_gross_income: float, cut_1: float = param(0.23), cut_2: float = param(0.27), cut_3: float = param(0.81),
        pts_1: float = param(-15.0), pts_2: float = param(15.0), pts_3: float = param(-20.0), pts_4: float = param(30.0)) -> float:
    x = requested_amount_to_gross_income
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def pl_pts_existing_instalments_to_net_income(existing_instalments_to_net_income: float, cut_1: float = param(0.14), cut_2: float = param(0.19), cut_3: float = param(0.24),
        pts_1: float = param(-5.0), pts_2: float = param(0.0), pts_3: float = param(5.0), pts_4: float = param(-20.0)) -> float:
    x = existing_instalments_to_net_income
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def pl_pts_net_income(net_income: float, cut_1: float = param(0.22), cut_2: float = param(0.53), cut_3: float = param(0.73),
        pts_1: float = param(20.0), pts_2: float = param(20.0), pts_3: float = param(-15.0), pts_4: float = param(5.0)) -> float:
    x = net_income
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def pl_pts_gross_income(gross_income: float, cut_1: float = param(0.27), cut_2: float = param(0.55), cut_3: float = param(0.93),
        pts_1: float = param(-15.0), pts_2: float = param(40.0), pts_3: float = param(20.0), pts_4: float = param(-20.0)) -> float:
    x = gross_income
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def pl_pts_judgements(judgements: float, cut_1: float = param(0.44), cut_2: float = param(0.48), cut_3: float = param(0.52),
        pts_1: float = param(5.0), pts_2: float = param(-10.0), pts_3: float = param(5.0), pts_4: float = param(-15.0)) -> float:
    x = judgements
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def pl_pts_months_employed_to_age(months_employed_to_age: float, cut_1: float = param(0.22), cut_2: float = param(0.41), cut_3: float = param(0.81),
        pts_1: float = param(40.0), pts_2: float = param(10.0), pts_3: float = param(-20.0), pts_4: float = param(-15.0)) -> float:
    x = months_employed_to_age
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def pl_pts_enquiries_6m_to_months_at_address(enquiries_6m_to_months_at_address: float, cut_1: float = param(0.66), cut_2: float = param(0.68), cut_3: float = param(0.92),
        pts_1: float = param(30.0), pts_2: float = param(-20.0), pts_3: float = param(-5.0), pts_4: float = param(-5.0)) -> float:
    x = enquiries_6m_to_months_at_address
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def pl_pts_card_utilisation_to_bureau_score(card_utilisation_to_bureau_score: float, cut_1: float = param(0.29), cut_2: float = param(0.87), cut_3: float = param(0.92),
        pts_1: float = param(-10.0), pts_2: float = param(30.0), pts_3: float = param(-15.0), pts_4: float = param(-5.0)) -> float:
    x = card_utilisation_to_bureau_score
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def pl_pts_expenses_to_gross_income(expenses_to_gross_income: float, cut_1: float = param(0.49), cut_2: float = param(0.76), cut_3: float = param(0.92),
        pts_1: float = param(0.0), pts_2: float = param(30.0), pts_3: float = param(-15.0), pts_4: float = param(35.0)) -> float:
    x = expenses_to_gross_income
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def pl_pts_net_income_zscore(net_income_zscore: float, cut_1: float = param(0.35), cut_2: float = param(0.62), cut_3: float = param(0.93),
        pts_1: float = param(-10.0), pts_2: float = param(10.0), pts_3: float = param(30.0), pts_4: float = param(-20.0)) -> float:
    x = net_income_zscore
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def pl_pts_bureau_score_zscore(bureau_score_zscore: float, cut_1: float = param(0.44), cut_2: float = param(0.69), cut_3: float = param(0.81),
        pts_1: float = param(35.0), pts_2: float = param(5.0), pts_3: float = param(-15.0), pts_4: float = param(0.0)) -> float:
    x = bureau_score_zscore
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def pl_score(pl_pts_bureau_score: float, pl_pts_months_employed: float, pl_pts_months_at_address: float, pl_pts_age: float, pl_pts_debt_service_ratio: float, pl_pts_card_utilisation: float, pl_pts_enquiries_6m: float, pl_pts_missed_payments_12m: float, pl_pts_dependants: float, pl_pts_disposable_income: float, pl_pts_expenses_to_net_income: float, pl_pts_requested_amount_to_gross_income: float, pl_pts_existing_instalments_to_net_income: float, pl_pts_net_income: float, pl_pts_gross_income: float, pl_pts_judgements: float, pl_pts_months_employed_to_age: float, pl_pts_enquiries_6m_to_months_at_address: float, pl_pts_card_utilisation_to_bureau_score: float, pl_pts_expenses_to_gross_income: float, pl_pts_net_income_zscore: float, pl_pts_bureau_score_zscore: float, intercept: float = param(600.0)) -> float:
    return intercept + pl_pts_bureau_score + pl_pts_months_employed + pl_pts_months_at_address + pl_pts_age + pl_pts_debt_service_ratio + pl_pts_card_utilisation + pl_pts_enquiries_6m + pl_pts_missed_payments_12m + pl_pts_dependants + pl_pts_disposable_income + pl_pts_expenses_to_net_income + pl_pts_requested_amount_to_gross_income + pl_pts_existing_instalments_to_net_income + pl_pts_net_income + pl_pts_gross_income + pl_pts_judgements + pl_pts_months_employed_to_age + pl_pts_enquiries_6m_to_months_at_address + pl_pts_card_utilisation_to_bureau_score + pl_pts_expenses_to_gross_income + pl_pts_net_income_zscore + pl_pts_bureau_score_zscore


def pl_score_band(pl_score: float, low: float = param(580.0), high: float = param(680.0)) -> int:
    return 3 if pl_score < low else (2 if pl_score < high else 1)


pl_scorecard = flow(
    pl_pts_bureau_score,
    pl_pts_months_employed,
    pl_pts_months_at_address,
    pl_pts_age,
    pl_pts_debt_service_ratio,
    pl_pts_card_utilisation,
    pl_pts_enquiries_6m,
    pl_pts_missed_payments_12m,
    pl_pts_dependants,
    pl_pts_disposable_income,
    pl_pts_expenses_to_net_income,
    pl_pts_requested_amount_to_gross_income,
    pl_pts_existing_instalments_to_net_income,
    pl_pts_net_income,
    pl_pts_gross_income,
    pl_pts_judgements,
    pl_pts_months_employed_to_age,
    pl_pts_enquiries_6m_to_months_at_address,
    pl_pts_card_utilisation_to_bureau_score,
    pl_pts_expenses_to_gross_income,
    pl_pts_net_income_zscore,
    pl_pts_bureau_score_zscore,
    pl_score,
    pl_score_band,
    name="scorecard",
)
