"""Generate `bank/`: a credit origination flow at realistic scale, for the extension's tests and demos.

About a thousand steps across a dozen modules: derived features, three
decision trees, and one arm per product (personal loan, credit card,
overdraft, home loan), each with policy rules, pricing from lookup tables,
affordability and limits, then a final decision. Hundreds of params, fourteen
lookup tables and forty applications. Deterministic: rerunning writes the same files.

    uv run python tools/vscode-decider/examples/make_bank.py
"""
from __future__ import annotations

import json
import random
import shutil
from pathlib import Path

HERE = Path(__file__).parent
OUT = HERE / "bank"
rnd = random.Random(20260923)
shutil.rmtree(OUT, ignore_errors=True)
OUT.mkdir()
TABLE_ROWS: dict[str, list] = {}

HEADER = '"""{doc}\n\nGenerated by make_bank.py; edit the generator, not this file."""\n'


def write(path: str, text: str) -> None:
    p = OUT / path
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text)


def fmt(v):
    return repr(v)


# ---------------------------------------------------------------- inputs

INPUTS = {
    "gross_income": float, "net_income": float, "expenses": float, "existing_instalments": float,
    "bureau_score": float, "age": float, "months_employed": float, "months_at_address": float,
    "dependants": float, "requested_amount": float, "requested_term": float, "collateral_value": float,
    "card_utilisation": float, "missed_payments_12m": float, "enquiries_6m": float, "judgements": float,
    "salary_account": bool, "channel": str, "province": str, "product_code": int, "employer_sector": int,
}

# ---------------------------------------------------------------- features

FEATURE_MODULES = {
    "income": "Income: bands, stability and what is left each month.",
    "debt": "Debt: repayment load, utilisation and ratios.",
    "stability": "Stability: employment, address and age.",
    "behaviour": "Behaviour on the bureau: arrears, enquiries, judgements.",
    "household": "Household: dependants and living costs.",
    "derived": "Composite indicators built from the other features.",
}

NUMERIC = [k for k, t in INPUTS.items() if t is float]
features: dict[str, list[str]] = {m: [] for m in FEATURE_MODULES}
feature_names: list[str] = []


def feature(module: str, name: str, args: list[tuple[str, str]], params: list[tuple[str, float]], body: str, ret: str = "float") -> None:
    sig = ", ".join([f"{a}: {t}" for a, t in args] + [f"{p}: float = param({v})" for p, v in params])
    features[module].append(f"def {name}({sig}) -> {ret}:\n    return {body}\n")
    feature_names.append(name)


def module_of(field: str) -> str:
    if field in ("gross_income", "net_income"):
        return "income"
    if field in ("existing_instalments", "card_utilisation", "requested_amount", "collateral_value"):
        return "debt"
    if field in ("months_employed", "months_at_address", "age"):
        return "stability"
    if field in ("missed_payments_12m", "enquiries_6m", "judgements", "bureau_score"):
        return "behaviour"
    return "household"


for f in NUMERIC:
    m = module_of(f)
    base = sorted(rnd.sample(range(1, 90), 3))
    scale = {"gross_income": 6000, "net_income": 5000, "requested_amount": 20000, "collateral_value": 60000,
             "bureau_score": 10, "expenses": 3000, "existing_instalments": 1200}.get(f, 1)
    t = [round(b * scale / (10 if scale > 1 else 4), 1) for b in base]
    feature(m, f"{f}_band", [(f, "float")], [("low", t[0]), ("mid", t[1]), ("high", t[2])],
            f"float(({f} > low) + ({f} > mid) + ({f} > high))")
    feature(m, f"{f}_high", [(f, "float")], [("threshold", t[2])], f"{f} > threshold", "bool")
    feature(m, f"{f}_capped", [(f, "float")], [("cap", t[2] * 3)], f"min({f}, cap)")
    feature(m, f"{f}_log", [(f, "float")], [], f"math.log1p(max({f}, 0.0))")
    feature(m, f"{f}_zscore", [(f, "float")], [("mean", t[1]), ("std", max(t[2] - t[0], 1.0))], f"({f} - mean) / std")
    feature(m, f"{f}_above_median", [(f, "float")], [("median", t[1])], f"{f} > median", "bool")
    feature(m, f"{f}_floor", [(f, "float")], [("floor", t[0])], f"max({f}, floor)")

PAIRS = [("existing_instalments", "net_income"), ("expenses", "net_income"), ("requested_amount", "gross_income"),
         ("requested_amount", "collateral_value"), ("existing_instalments", "gross_income"), ("expenses", "gross_income"),
         ("months_employed", "age"), ("months_at_address", "age"), ("dependants", "net_income"),
         ("missed_payments_12m", "months_employed"), ("enquiries_6m", "months_at_address"), ("card_utilisation", "bureau_score")]
AMOUNTS = ["gross_income", "net_income", "expenses", "existing_instalments", "requested_amount", "collateral_value"]
PAIRS += [(a, b) for i, a in enumerate(AMOUNTS) for b in AMOUNTS[i + 1:] if (a, b) not in PAIRS and (b, a) not in PAIRS]
for a, b in PAIRS:
    feature("derived", f"{a}_to_{b}", [(a, "float"), (b, "float")], [], f"{a} / max({b}, 1.0)")
    feature("derived", f"{a}_to_{b}_flag", [(a, "float"), (b, "float")], [("limit", round(rnd.uniform(0.2, 0.8), 2))],
            f"{a} / max({b}, 1.0) > limit", "bool")

feature("income", "disposable_income", [("net_income", "float"), ("expenses", "float"), ("existing_instalments", "float")], [],
        "net_income - expenses - existing_instalments")
feature("income", "disposable_income_buffered", [("disposable_income", "float")], [("buffer", 0.1)], "disposable_income * (1 - buffer)")
feature("household", "living_cost_floor", [("dependants", "float")], [("per_adult", 3200.0), ("per_dependant", 1450.0)],
        "per_adult + per_dependant * dependants")
feature("household", "expenses_declared_low", [("expenses", "float"), ("living_cost_floor", "float")], [], "expenses < living_cost_floor", "bool")
feature("household", "expenses_used", [("expenses", "float"), ("living_cost_floor", "float")], [], "max(expenses, living_cost_floor)")
feature("debt", "debt_service_ratio", [("existing_instalments", "float"), ("gross_income", "float")], [], "existing_instalments / max(gross_income, 1.0)")
feature("behaviour", "clean_record", [("missed_payments_12m", "float"), ("judgements", "float")], [], "missed_payments_12m == 0 and judgements == 0", "bool")
feature("stability", "age_years_band", [("age", "float")], [("young", 25.0), ("mature", 55.0)], "0.0 if age < young else (2.0 if age >= mature else 1.0)")

for m, doc in FEATURE_MODULES.items():
    names = [s.split("(")[0][4:] for s in features[m]]
    body = HEADER.format(doc=doc) + "import math  # noqa: F401\n\nfrom decider import dag, param, step  # noqa: F401\n\n\n" + "\n\n".join(features[m])
    body += f"\n\n{m} = dag(\n" + "".join(f"    {n},\n" for n in names) + f'    name="{m}",\n)\n'
    write(f"features/{m}.py", body)
write("features/__init__.py", HEADER.format(doc="Derived features, one module per theme.") + "".join(f"from bank.features.{m} import {m}\n" for m in FEATURE_MODULES))

# ---------------------------------------------------------------- trees


def tree_doc(name: str, feature: str, splits: list[tuple[str, str, float, int]], outputs: list[dict], default: dict, dtypes: list) -> dict:
    """A small v3 tree: a chain of `feature op threshold` tests, each leading to a leaf or the next test."""
    nodes, edges = [], []
    for i, (nid, op, threshold, leaf) in enumerate(splits):
        nodes.append({"id": nid, "data": {"type": "unary", "condition": {"op": op, "feature": feature if isinstance(feature, str) else feature[i],
                                                                          "threshold": {"param": f"{nid}_threshold", "default": threshold}}}})
        nodes.append({"id": f"{nid}_leaf", "data": {"type": "leaf", "result_idx": leaf}})
        edges.append({"source": nid, "target": f"{nid}_leaf", "data": {"sourceIndex": 0}})
        if i + 1 < len(splits):
            edges.append({"source": nid, "target": splits[i + 1][0], "data": {"sourceIndex": 1}})
    return {"type": "tree", "name": name, "tree": {"nodes": nodes, "edges": edges,
                                                  "output": {"data": outputs, "default": default, "dtypes": dtypes}}}


TREES = {
    "bureau_grade": tree_doc("bureau_grade", "bureau_score",
                             [("excellent", ">=", 720.0, 0), ("good", ">=", 660.0, 1), ("fair", ">=", 600.0, 2)],
                             [{"grade": 1}, {"grade": 2}, {"grade": 3}], {"grade": 4}, [["grade", "Int64"]]),
    "fraud_screen": tree_doc("fraud_screen", ["enquiries_6m", "months_at_address"],
                             [("enquiry_burst", ">", 6.0, 0), ("new_address", "<", 3.0, 1)],
                             [{"fraud_referral": True}, {"fraud_referral": True}], {"fraud_referral": False}, [["fraud_referral", "Boolean"]]),
    "collections_risk": tree_doc("collections_risk", ["missed_payments_12m", "judgements"],
                                 [("chronic_arrears", ">", 2.0, 0), ("has_judgement", ">", 0.0, 1)],
                                 [{"collections_band": 3}, {"collections_band": 2}], {"collections_band": 1}, [["collections_band", "Int64"]]),
}
for n, d in TREES.items():
    write(f"trees/{n}.json", json.dumps(d, indent=1) + "\n")
write("trees/__init__.py", HEADER.format(doc="Decision trees, loaded from their JSON documents.") + '''from pathlib import Path

from decider.steps.trees import TreeConfig

_HERE = Path(__file__).parent
bureau_grade = TreeConfig.load((_HERE / "bureau_grade.json").read_text())
fraud_screen = TreeConfig.load((_HERE / "fraud_screen.json").read_text())
collections_risk = TreeConfig.load((_HERE / "collections_risk.json").read_text())
''')

# ---------------------------------------------------------------- products

PRODUCTS = {
    "personal_loan": ("pl", 0, "Personal loan: unsecured, 6 to 84 months."),
    "credit_card": ("cc", 1, "Credit card: revolving limit, rate by grade."),
    "overdraft": ("od", 2, "Overdraft on a salary account."),
    "home_loan": ("hl", 3, "Home loan: secured, 60 to 360 months, loan-to-value limits."),
}
TERMS = {"pl": [(6, 24), (25, 48), (49, 84)], "cc": [(1, 12), (13, 60)], "od": [(1, 12)], "hl": [(60, 180), (181, 240), (241, 360)]}
BASE_RATES = {"pl": [0.215, 0.235, 0.255], "cc": [0.205, 0.225], "od": [0.195], "hl": [0.1175, 0.1225, 0.1275]}
PROVINCES = ["GP", "WC", "KZN", "EC", "FS", "LP", "MP", "NW", "NC"]
CHANNELS = ["branch", "app", "web"]

RULES = [  # (name, input, op, default threshold, reason)
    ("min_age", "age", "<", 18.0, "Under the minimum age"),
    ("max_age", "age", ">", 70.0, "Over the maximum age at maturity"),
    ("min_gross_income", "gross_income", "<", 4500.0, "Income below the minimum"),
    ("min_net_income", "net_income", "<", 3500.0, "Net income below the minimum"),
    ("max_debt_service", "debt_service_ratio", ">", 0.45, "Debt repayments too high"),
    ("min_bureau", "bureau_score", "<", 560.0, "Bureau score too low"),
    ("max_enquiries", "enquiries_6m", ">", 8.0, "Too many recent credit enquiries"),
    ("max_missed", "missed_payments_12m", ">", 3.0, "Missed payments in the last year"),
    ("max_judgements", "judgements", ">", 0.0, "Judgement on record"),
    ("min_employment", "months_employed", "<", 3.0, "Employed for too short a time"),
    ("min_address", "months_at_address", "<", 1.0, "Address too recent"),
    ("max_utilisation", "card_utilisation", ">", 0.95, "Card limits nearly exhausted"),
    ("max_dependants", "dependants", ">", 8.0, "Household too large for declared income"),
    ("min_disposable", "disposable_income", "<", 1500.0, "Too little left each month"),
    ("max_requested", "requested_amount", ">", 350000.0, "Amount above the product maximum"),
    ("min_requested", "requested_amount", "<", 2000.0, "Amount below the product minimum"),
]
SEGMENT_RULES = [("sector", "employer_sector", range(1, 7)), ("province", "province", PROVINCES), ("channel", "channel", CHANNELS)]


def product_files(product: str, p: str, code: int, doc: str) -> tuple[list[str], int]:
    """Write one product's package; return its policy output names and step count."""
    count = 0
    # Policy: the shared rules, then segment overrides for sectors, provinces and channels.
    rules, flags, reasons = [], [], []
    for name, field, op, thr, reason in RULES:
        thr = thr * (1.0 + rnd.choice([-0.1, 0.0, 0.0, 0.1])) if field not in ("age", "judgements") else thr
        fn = f"{p}_{name}"
        rules.append(f'@step(output="{fn}")\ndef {fn}({field}: float, limit: float = param({round(thr, 2)})) -> bool:\n'
                     f'    """{reason}."""\n    return {field} {op} limit\n')
        flags.append(fn)
        reasons.append(reason)
    for seg, field, values in SEGMENT_RULES:
        for v in values:
            key = str(v).lower()
            fn = f"{p}_{seg}_{key}_max_debt"
            vt = "int" if seg == "sector" else "str"
            rules.append(f'@step(output="{fn}")\ndef {fn}({field}: {vt}, debt_service_ratio: float, limit: float = param({round(rnd.uniform(0.3, 0.55), 2)})) -> bool:\n'
                         f'    """Debt repayments too high for {seg} {v}."""\n    return {field} == {v!r} and debt_service_ratio > limit\n')
            flags.append(fn)
            reasons.append(f"Debt repayments too high for {seg} {v}")
            fn2 = f"{p}_{seg}_{key}_min_score"
            rules.append(f'@step(output="{fn2}")\ndef {fn2}({field}: {vt}, bureau_score: float, limit: float = param({float(rnd.choice(range(560, 660, 5)))})) -> bool:\n'
                         f'    """Bureau score too low for {seg} {v}."""\n    return {field} == {v!r} and bureau_score < limit\n')
            flags.append(fn2)
            reasons.append(f"Bureau score too low for {seg} {v}")
            fn3 = f"{p}_{seg}_{key}_min_income"
            rules.append(f'@step(output="{fn3}")\ndef {fn3}({field}: {vt}, net_income: float, limit: float = param({float(rnd.choice(range(3500, 9001, 250)))})) -> bool:\n'
                         f'    """Net income too low for {seg} {v}."""\n    return {field} == {v!r} and net_income < limit\n')
            flags.append(fn3)
            reasons.append(f"Net income too low for {seg} {v}")
            fn4 = f"{p}_{seg}_{key}_max_loan_to_income"
            rules.append(f'@step(output="{fn4}")\ndef {fn4}({field}: {vt}, requested_amount_to_gross_income: float, limit: float = param({round(rnd.uniform(3, 12), 1) if p != "hl" else 60.0})) -> bool:\n'
                         f'    """Loan too large for income in {seg} {v}."""\n    return {field} == {v!r} and requested_amount_to_gross_income > limit\n')
            flags.append(fn4)
            reasons.append(f"Loan too large for income in {seg} {v}")
    count += len(rules)
    agg_args = ",\n    ".join(f"{f}: bool" for f in flags)
    reason_list = ",\n        ".join(f"({f}, {r!r})" for f, r in zip(flags, reasons))
    policy = (HEADER.format(doc=f"{doc} Policy rules: each rule declines an application for one reason.") +
              "from decider import flow, param, step\n\n\n" + "\n\n".join(rules) +
              f'\n\n@step(outputs=("{p}_policy_declined", "{p}_policy_reason"))\ndef {p}_policy_outcome(\n    {agg_args},\n) -> tuple[bool, str]:\n'
              f'    """The first failed rule, in priority order."""\n    for failed, reason in (\n        {reason_list},\n    ):\n'
              f'        if failed:\n            return True, reason\n    return False, ""\n\n\n'
              f'{p}_policy = flow(\n' + "".join(f"    {f},\n" for f in flags) + f'    {p}_policy_outcome,\n    name="policy",\n)\n')
    count += 1
    write(f"products/{product}/policy.py", policy)

    # Pricing: decision tables whose rows live in the params document, then the rate build-up.
    lo_hi = [(lo, hi + 1) for lo, hi in TERMS[p]]
    TABLE_ROWS[f"{p}_base_rates"] = [{"min_term": float(lo), "max_term": float(hi), f"{p}_base_rate": r} for (lo, hi), r in zip(lo_hi, BASE_RATES[p])]
    TABLE_ROWS[f"{p}_risk_loadings"] = [{"grade_key": g, f"{p}_risk_loading": round(0.01 * (g - 1) * (2.0 if p != "hl" else 0.5), 4)} for g in range(1, 5)]
    bands = [(0, 10001, 165.0), (10001, 50001, 690.0), (50001, 1e9, 1207.5)] if p != "hl" else [(0, 1_000_001, 6037.5), (1_000_001, 1e9, 6037.5)]
    TABLE_ROWS[f"{p}_fees"] = [{"min_amount": float(lo), "max_amount": float(hi), f"{p}_initiation_fee": fee, f"{p}_monthly_fee": 69.0} for lo, hi, fee in bands]
    tables = [f"{p}_base_rates", f"{p}_risk_loadings", f"{p}_fees"]
    pricing_steps = []
    pricing = HEADER.format(doc=f"{doc} Pricing: the base rate by term, a loading by risk grade, fees by amount, capped by regulation.")
    pricing += "from decider import dag, flow, param, step\nfrom decider.steps.tables import DecisionTableConfig\n\n"
    pricing += (f'{p}_base_rates = DecisionTableConfig(\n    name="{p}_base_rates",\n'
                f'    columns={{"min_term": "Float64", "max_term": "Float64", "{p}_base_rate": "Float64"}},\n'
                f'    rows={{"table": "{p}_base_rates", "shared": True}},\n'
                f'    expression={{"type": "between", "variable": "requested_term", "lower_bound_column": "min_term", "upper_bound_column": "max_term"}},\n'
                f'    outputs=["{p}_base_rate"],\n)\n'
                f'{p}_risk_loadings = DecisionTableConfig(\n    name="{p}_risk_loadings",\n'
                f'    columns={{"grade_key": "Int64", "{p}_risk_loading": "Float64"}},\n'
                f'    rows={{"table": "{p}_risk_loadings", "shared": True}},\n'
                f'    expression={{"type": "eq", "variable": "grade", "value_column": "grade_key"}},\n'
                f'    outputs=["{p}_risk_loading"],\n)\n'
                f'{p}_fees = DecisionTableConfig(\n    name="{p}_fees",\n'
                f'    columns={{"min_amount": "Float64", "max_amount": "Float64", "{p}_initiation_fee": "Float64", "{p}_monthly_fee": "Float64"}},\n'
                f'    rows={{"table": "{p}_fees", "shared": True}},\n'
                f'    expression={{"type": "between", "variable": "requested_amount", "lower_bound_column": "min_amount", "upper_bound_column": "max_amount"}},\n'
                f'    outputs=["{p}_initiation_fee", "{p}_monthly_fee"],\n)\n\n\n')
    extra = [
        (f"{p}_salary_discount", "salary_account: bool", "discount: float = param(0.005)", "discount if salary_account else 0.0"),
        (f"{p}_channel_discount", "channel_discount: float", "weight: float = param(1.0)", "channel_discount * weight"),
        (f"{p}_loyalty_discount", "months_at_address: float", "discount: float = param(0.001)", "discount if months_at_address > 60 else 0.0"),
        (f"{p}_clean_record_discount", "clean_record: bool", "discount: float = param(0.002)", "discount if clean_record else 0.0"),
        (f"{p}_fraud_loading", "fraud_referral: bool", "loading: float = param(0.01)", "loading if fraud_referral else 0.0"),
        (f"{p}_collections_loading", "collections_band: int", "per_band: float = param(0.0075)", "per_band * (collections_band - 1)"),
    ]
    for name, arg, par, body in extra:
        pricing_steps.append(name)
        pricing += f"def {name}({arg}, {par}) -> float:\n    return {body}\n\n\n"
    discounts = [e[0] for e in extra[:4]]
    loadings = [e[0] for e in extra[4:]]
    pricing += (f'def {p}_raw_rate({p}_base_rate: float, {p}_risk_loading: float, ' + ", ".join(f"{d}: float" for d in discounts + loadings) +
                f') -> float:\n    return {p}_base_rate + {p}_risk_loading - ' + " - ".join(discounts) + " + " + " + ".join(loadings) + "\n\n\n")
    pricing += (f'@step(output="{p}_rate")\ndef {p}_regulated_rate({p}_raw_rate: float, repo_rate: float = param(0.0775, shared_key="repo_rate"),\n'
                f'                        cap_multiple: float = param(1.0), cap_margin: float = param({0.21 if p != "hl" else 0.12})) -> float:\n'
                f'    """The National Credit Act cap: repo plus 21% for unsecured credit, 12% for mortgages."""\n'
                f'    return min({p}_raw_rate, repo_rate * cap_multiple + cap_margin)\n\n\n')
    pricing += (f'@step(output="{p}_rate")\ndef {p}_rate_floor({p}_rate: float, repo_rate: float = param(0.0775, shared_key="repo_rate"),\n'
                f'                  margin: float = param(0.03)) -> float:\n'
                f'    """Never price below repo plus a margin."""\n'
                f'    return max({p}_rate, repo_rate + margin)\n\n\n')
    pricing += (f'def {p}_monthly_rate({p}_rate: float) -> float:\n    return {p}_rate / 12\n\n\n')
    pricing_steps += [f"{p}_raw_rate", f"{p}_regulated_rate", f"{p}_rate_floor", f"{p}_monthly_rate"]
    pricing += f"{p}_pricing = flow(\n    {p}_base_rates,\n    {p}_risk_loadings,\n    {p}_fees,\n" + "".join(f"    {s},\n" for s in pricing_steps) + '    name="pricing",\n)\n'
    count += 3 + len(pricing_steps)
    write(f"products/{product}/pricing.py", pricing)

    # Affordability: the instalment for the requested amount, a stressed rate, and what fits.
    afford = HEADER.format(doc=f"{doc} Affordability: the instalment at the offered and a stressed rate against disposable income.")
    afford += "from decider import flow, param, step\n\n\n"
    asteps = []

    def a(name, sig, body, ret="float"):
        nonlocal afford
        afford += f"def {name}({sig}) -> {ret}:\n    return {body}\n\n\n"
        asteps.append(name)

    a(f"{p}_instalment", f"requested_amount: float, requested_term: float, {p}_monthly_rate: float, {p}_monthly_fee: float",
      f"requested_amount * {p}_monthly_rate / (1 - (1 + {p}_monthly_rate) ** -requested_term) + {p}_monthly_fee")
    a(f"{p}_stress_rate", f"{p}_rate: float, buffer: float = param({0.02 if p == 'hl' else 0.03})", f"{p}_rate + buffer")
    a(f"{p}_stress_instalment", f"requested_amount: float, requested_term: float, {p}_stress_rate: float",
      f"requested_amount * ({p}_stress_rate / 12) / (1 - (1 + {p}_stress_rate / 12) ** -requested_term)")
    a(f"{p}_affordable_instalment", f"disposable_income_buffered: float, share: float = param({0.35 if p == 'hl' else 0.5})",
      "max(disposable_income_buffered * share, 0.0)")
    a(f"{p}_instalment_fits", f"{p}_stress_instalment: float, {p}_affordable_instalment: float", f"{p}_stress_instalment <= {p}_affordable_instalment", "bool")
    a(f"{p}_max_affordable_amount", f"{p}_affordable_instalment: float, requested_term: float, {p}_stress_rate: float",
      f"{p}_affordable_instalment * (1 - (1 + {p}_stress_rate / 12) ** -requested_term) / ({p}_stress_rate / 12)")
    for i, (lo, hi) in enumerate([(0, 0.2), (0.2, 0.35), (0.35, 0.5), (0.5, 1.0)]):
        a(f"{p}_dti_band_{i}", f"debt_service_ratio: float, lo: float = param({lo}), hi: float = param({hi})", "lo <= debt_service_ratio < hi", "bool")
    for g in range(1, 5):
        a(f"{p}_grade_{g}_share", f"grade: int, share: float = param({round(1.0 - 0.15 * (g - 1), 2)})", f"share if grade == {g} else 0.0")
    a(f"{p}_grade_share", ", ".join(f"{p}_grade_{g}_share: float" for g in range(1, 5)), " + ".join(f"{p}_grade_{g}_share" for g in range(1, 5)))
    afford += f"{p}_affordability = flow(\n" + "".join(f"    {s},\n" for s in asteps) + '    name="affordability",\n)\n'
    count += len(asteps)
    write(f"products/{product}/affordability.py", afford)

    # Limits and the arm's outputs.
    limits = HEADER.format(doc=f"{doc} Limits: product caps and the offer.")
    limits += "from decider import flow, param, step\n\n\n"
    lsteps = []

    def l(name, sig, body, ret="float", output=None):
        nonlocal limits
        deco = f'@step(output="{output}")\n' if output else ""
        limits += f"{deco}def {name}({sig}) -> {ret}:\n    return {body}\n\n\n"
        lsteps.append(name)

    cap = {"pl": 350000.0, "cc": 150000.0, "od": 50000.0, "hl": 5000000.0}[p]
    l(f"{p}_product_cap", f"grade: int, cap: float = param({cap})", "cap * (1.0 if grade <= 2 else 0.6)")
    if p == "hl":
        l(f"{p}_ltv_cap", "collateral_value: float, max_ltv: float = param(0.9)", "collateral_value * max_ltv")
    else:
        l(f"{p}_ltv_cap", "requested_amount: float", "requested_amount")
    l(f"{p}_income_cap", f"gross_income: float, multiple: float = param({ {'pl': 4.0, 'cc': 2.0, 'od': 1.0, 'hl': 60.0}[p] })", "gross_income * multiple")
    l(f"{p}_max_amount", f"{p}_product_cap: float, {p}_ltv_cap: float, {p}_income_cap: float, {p}_max_affordable_amount: float, {p}_grade_share: float",
      f"min({p}_product_cap, {p}_ltv_cap, {p}_income_cap, {p}_max_affordable_amount) * {p}_grade_share")
    l(f"{p}_offer_amount", f"requested_amount: float, {p}_max_amount: float, rounding: float = param(500.0)",
      f"max(min(requested_amount, {p}_max_amount) // rounding * rounding, 0.0)", output="offer_amount")
    l(f"{p}_offer_term", "requested_term: float", "requested_term", output="offer_term")
    l(f"{p}_offer_rate", f"{p}_rate: float", f"{p}_rate", output="offer_rate")
    l(f"{p}_offer_instalment", f"offer_amount: float, offer_term: float, {p}_monthly_rate: float, {p}_monthly_fee: float",
      f"offer_amount * {p}_monthly_rate / (1 - (1 + {p}_monthly_rate) ** -offer_term) + {p}_monthly_fee if offer_amount > 0 else 0.0", output="monthly_instalment")
    l(f"{p}_declined", f"{p}_policy_declined: bool, {p}_instalment_fits: bool, offer_amount: float, minimum: float = param({ {'hl': 100000.0}.get(p, 2000.0) })",
      f"{p}_policy_declined or offer_amount < minimum", "bool", output="declined")
    l(f"{p}_decline_reason", f"{p}_policy_reason: str, {p}_policy_declined: bool, declined: bool",
      f'{p}_policy_reason if {p}_policy_declined else ("Offer below the product minimum" if declined else "")', "str", output="decline_reason")
    limits += f"{p}_limits = flow(\n" + "".join(f"    {s},\n" for s in lsteps) + '    name="limits",\n)\n'
    count += len(lsteps)
    write(f"products/{product}/limits.py", limits)

    chars = ["bureau_score", "months_employed", "months_at_address", "age", "debt_service_ratio", "card_utilisation",
             "enquiries_6m", "missed_payments_12m", "dependants", "disposable_income", "expenses_to_net_income",
             "requested_amount_to_gross_income", "existing_instalments_to_net_income", "net_income", "gross_income",
             "judgements", "months_employed_to_age", "enquiries_6m_to_months_at_address", "card_utilisation_to_bureau_score",
             "expenses_to_gross_income", "net_income_zscore", "bureau_score_zscore"]
    sc = HEADER.format(doc=f"{doc} Application scorecard: points per characteristic, summed into a score.")
    sc += "from decider import flow, param, step\n\n\n"
    names = []
    for c in chars:
        cuts = sorted(round(rnd.uniform(0, 1), 2) for _ in range(3))
        pts = [rnd.choice(range(-20, 41, 5)) for _ in range(4)]
        n = f"{p}_pts_{c}"
        sc += (f"def {n}({c}: float, cut_1: float = param({cuts[0]}), cut_2: float = param({cuts[1]}), cut_3: float = param({cuts[2]}),\n"
               f"        pts_1: float = param({float(pts[0])}), pts_2: float = param({float(pts[1])}), pts_3: float = param({float(pts[2])}), pts_4: float = param({float(pts[3])})) -> float:\n"
               f"    x = {c}\n    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))\n\n\n")
        names.append(n)
    sc += f"def {p}_score(" + ", ".join(f"{n}: float" for n in names) + f", intercept: float = param(600.0)) -> float:\n    return intercept + " + " + ".join(names) + "\n\n\n"
    sc += f"def {p}_score_band({p}_score: float, low: float = param(580.0), high: float = param(680.0)) -> int:\n    return 3 if {p}_score < low else (2 if {p}_score < high else 1)\n\n\n"
    sc += f"{p}_scorecard = flow(\n" + "".join(f"    {n},\n" for n in names) + f'    {p}_score,\n    {p}_score_band,\n    name="scorecard",\n)\n'
    count += len(names) + 2
    write(f"products/{product}/scorecard.py", sc)

    st = HEADER.format(doc=f"{doc} Stress tests: the instalment under rate shocks, and whether it still fits.")
    st += "from decider import flow, param, step\n\n\n"
    snames = []
    for bp in range(25, 776, 25):
        n = f"{p}_shock_{bp}bp_instalment"
        st += (f"def {n}(requested_amount: float, requested_term: float, {p}_rate: float, shock: float = param({bp / 10000})) -> float:\n"
               f"    r = ({p}_rate + shock) / 12\n    return requested_amount * r / (1 - (1 + r) ** -requested_term)\n\n\n")
        f2 = f"{p}_shock_{bp}bp_fits"
        st += f"def {f2}({n}: float, {p}_affordable_instalment: float) -> bool:\n    return {n} <= {p}_affordable_instalment\n\n\n"
        snames += [n, f2]
    st += f"{p}_stress = flow(\n" + "".join(f"    {n},\n" for n in snames) + '    name="stress_tests",\n)\n'
    count += len(snames)
    write(f"products/{product}/stress.py", st)

    write(f"products/{product}/__init__.py", HEADER.format(doc=doc) +
          f"from decider import flow\n\nfrom bank.products.{product}.affordability import {p}_affordability\n"
          f"from bank.products.{product}.limits import {p}_limits\nfrom bank.products.{product}.policy import {p}_policy\n"
          f"from bank.products.{product}.pricing import {p}_pricing\nfrom bank.products.{product}.scorecard import {p}_scorecard\n"
          f"from bank.products.{product}.stress import {p}_stress\n\n"
          f'{product} = flow({p}_scorecard, {p}_policy, {p}_pricing, {p}_affordability, {p}_stress, {p}_limits, name="{product}")\n')
    return tables, count


# ---------------------------------------------------------------- write it all

write("__init__.py", HEADER.format(doc="A credit origination flow at realistic scale."))
total = len(feature_names)
for product, (p, code, doc) in PRODUCTS.items():
    _, n = product_files(product, p, code, doc)
    total += n

write("decision.py", HEADER.format(doc="The final decision: referrals, the reason code and the channel message.") + '''from decider import flow, param, step


def product_arm(product_code: int) -> int:
    return product_code


@step(output="refer")
def refer_to_underwriter(fraud_referral: bool, offer_amount: float, referral_amount: float = param(250000.0)) -> bool:
    """Large offers and fraud referrals go to a person."""
    return fraud_referral or offer_amount > referral_amount


@step(output="decision")
def final_decision(declined: bool, refer: bool) -> str:
    return "decline" if declined else ("refer" if refer else "approve")


@step(output="reason_code")
def reason_code(decision: str, decline_reason: str) -> str:
    return decline_reason if decision == "decline" else ("Referred for review" if decision == "refer" else "Approved")


@step(output="total_cost")
def total_cost_of_credit(monthly_instalment: float, offer_term: float, offer_amount: float) -> float:
    return monthly_instalment * offer_term - offer_amount


decision = flow(refer_to_underwriter, final_decision, reason_code, total_cost_of_credit, name="decision")
''')
total += 4 + 3
write("pipeline.py", HEADER.format(doc="Credit origination: features, trees, one arm per product, then the decision.") + '''import json
from pathlib import Path

from decider import branch, flow

from bank.decision import decision, product_arm
from bank.features import behaviour, debt, derived, household, income, stability
from bank.products.credit_card import credit_card
from bank.products.home_loan import home_loan
from bank.products.overdraft import overdraft
from bank.products.personal_loan import personal_loan
from bank.shared_tables import channel_discounts, credit_life_rates
from bank.trees import bureau_grade, collections_risk, fraud_screen

features = flow(income, debt, stability, behaviour, household, derived, name="features")
risk = flow(bureau_grade, fraud_screen, collections_risk, name="risk")
pricing_inputs = flow(channel_discounts, credit_life_rates, name="pricing_inputs")
product = branch(
    product_arm, personal_loan, credit_card, overdraft, home_loan,
    modifies=["offer_amount", "offer_term", "offer_rate", "monthly_instalment", "declined", "decline_reason"],
    name="product",
)
origination = flow(features, risk, pricing_inputs, product, decision, name="origination").emit("decision", "offer_amount")

SAMPLE = json.loads((Path(__file__).parent / "applications.json").read_text())
# The rate, fee and discount tables, as the config store holds them.
PARAMS = json.loads((Path(__file__).parent / "params.json").read_text())
''')

TABLE_ROWS["channel_discounts"] = [{"channel_key": c, "channel_discount": d} for c, d in (("branch", 0.0), ("app", 0.0025), ("web", 0.001))]
TABLE_ROWS["credit_life_rates"] = [{"min_age": float(lo), "max_age": float(hi), "credit_life_rate": r}
                                   for lo, hi, r in ((18, 30, 0.0021), (30, 45, 0.0032), (45, 60, 0.0055), (60, 120, 0.0098))]
write("shared_tables.py", HEADER.format(doc="Tables every product reads: the channel discount and the credit life premium by age.") + '''from decider.steps.tables import DecisionTableConfig

channel_discounts = DecisionTableConfig(
    name="channel_discounts",
    columns={"channel_key": "String", "channel_discount": "Float64"},
    rows={"table": "channel_discounts", "shared": True},
    expression={"type": "eq", "variable": "channel", "value_column": "channel_key"},
    outputs=["channel_discount"],
    default=[0.0],
)
credit_life_rates = DecisionTableConfig(
    name="credit_life_rates",
    columns={"min_age": "Float64", "max_age": "Float64", "credit_life_rate": "Float64"},
    rows={"table": "credit_life_rates", "shared": True},
    expression={"type": "between", "variable": "age", "lower_bound_column": "min_age", "upper_bound_column": "max_age"},
    outputs=["credit_life_rate"],
    default=[0.0098],
)
''')
write("params.json", json.dumps({"shared": TABLE_ROWS}, indent=1) + "\n")

# Forty applications from a morning's queue.
FIRST = ["Nomsa", "Pieter", "Ayesha", "Sipho", "Lerato", "Johan", "Fatima", "Thabo", "Anele", "Ruan", "Zanele", "Kagiso",
         "Megan", "Themba", "Priya", "Mandla", "Chantal", "Bongani", "Naledi", "Wian"]
apps = []
for i in range(40):
    product_code = rnd.choice([0, 0, 0, 1, 1, 2, 3])
    gross = round(rnd.uniform(9000, 95000), -2)
    net = round(gross * rnd.uniform(0.68, 0.8), -2)
    amount = {0: rnd.choice(range(15000, 300001, 5000)), 1: rnd.choice(range(5000, 80001, 5000)),
              2: rnd.choice(range(2000, 40001, 1000)), 3: rnd.choice(range(450000, 3500001, 50000))}[product_code]
    term = {0: rnd.choice([12, 24, 36, 48, 60, 72, 84]), 1: rnd.choice([12, 24, 36]), 2: 12, 3: rnd.choice([180, 240, 360])}[product_code]
    apps.append({
        "client_id": 20400 + i * 7, "applicant": f"{FIRST[i % len(FIRST)]}", "product_code": product_code,
        "gross_income": gross, "net_income": net, "expenses": round(net * rnd.uniform(0.35, 0.7), -2),
        "existing_instalments": round(net * rnd.uniform(0.0, 0.35), -2), "bureau_score": float(rnd.choice(range(540, 790, 5))),
        "age": float(rnd.choice(range(19, 66))), "months_employed": float(rnd.choice(range(1, 240))),
        "months_at_address": float(rnd.choice(range(1, 180))), "dependants": float(rnd.choice([0, 0, 1, 2, 3, 4])),
        "requested_amount": float(amount), "requested_term": float(term),
        "collateral_value": float(round(amount * rnd.uniform(1.05, 1.4), -3)) if product_code == 3 else 0.0,
        "card_utilisation": round(rnd.uniform(0, 1), 2), "missed_payments_12m": float(rnd.choice([0, 0, 0, 1, 2, 4])),
        "enquiries_6m": float(rnd.choice([0, 0, 1, 1, 2, 3, 4, 9])), "judgements": float(rnd.choice([0, 0, 0, 0, 0, 0, 1])),
        "salary_account": rnd.random() < 0.6, "channel": rnd.choice(CHANNELS), "province": rnd.choice(PROVINCES),
        "employer_sector": rnd.choice(range(1, 7)),
    })
write("applications.json", json.dumps(apps, indent=1) + "\n")
print(f"wrote {OUT}: about {total} steps")
