"""Stage 5.5 -- classify ONE adverse event. Event grain.

This is the innermost work and the file to read if you read only one. Every
function here takes one event and returns one value. There is no collection in
this file, no index, no length, no loop. The collection exists in
`pipelines/business_facility.py` as `Each(Event, ...)` and nowhere else.

That is the claim the whole sketch rests on: **logic for one element of a
collection is written exactly as logic for one record, because a grain makes it
one record.**

Worst case this file runs 600 times for one application and 6 700 000 times in
the monthly batch. In batch it is one kernel over a 6.7 M-row frame. In the
realtime path it is one kernel over a capacity-60 array per entity. Same steps,
same numerics, checked by the equivalence ladder (doc 02 s3.1) -- which this
project needs extended to cover the fold, see FRAMEWORK-DEMANDS D06.
"""

from decider2 import module, step, param, table, overlay, missing_as
from grains import Event, IMMATERIAL, MINOR, MATERIAL, DISQUALIFYING

# --------------------------------------------------------------------------
# The threshold table: 14 event types x 3 criticality classes x 2 severities.
# s6.2 gives it 84 cells, Policy-owned, quarterly.
#
# Two keys, from two different grains. `event_type_code` is an Event value;
# `criticality_class` is an Entity value, broadcast down. That single fact is
# spec s13 Q3 in its entirety -- "where does the parameterisation of a shared
# capability by its context live?" -- and the answer this sketch gives is: it is
# an ordinary input, broadcast from the parent grain, and the library capability
# takes the thresholds rather than owning the table.
#
# `overlay=` is stack position 1 (s5.10). It is declared on the *table*, not at
# the call site, because s5.5 requires the overlay to be applied before any
# event is classified -- it changes the classification rather than a value
# derived from it. A call-site overlay could not guarantee that ordering.
# --------------------------------------------------------------------------
EVENT_THRESHOLDS = table(
    "event_amount_thresholds",
    key=("event_type_code", "criticality_class"),
    columns=("material_threshold", "disqualifying_threshold"),
    source="tables/event_thresholds.csv",
    effective_dated=True,
    owner="Business Credit Risk Policy",
    cadence="quarterly",
    overlay=overlay.position(1, scopes=("sector_code", "criticality_class")),
)

# 14 types x 6 age bands, with a per-type floor. s5.5: "Severity decay is a
# table, not an expression". Types 8 (prior Bank write-off) and 14 (confirmed
# fraud) have a floor equal to their initial severity and never decay.
EVENT_AGEING = table(
    "event_ageing_decay",
    key=("event_type_code", "age_band_index"),
    columns=("decay_classes", "severity_floor"),
    source="tables/event_ageing.csv",
    effective_dated=True,
)


# --------------------------------------------------------------------------
# Threshold resolution. THREE outputs, always: the value used, the value the
# base table holds, and the overlay that moved it. s5.5's three requirements
# are this step's three outputs and nothing else.
#
# A two-output version -- "the threshold" and "was it overlaid" -- is what gets
# written if the framework does not force the shape, and it cannot satisfy the
# s5.5 requirement that the decline reason read as a complete chain:
#   "...against a threshold of R25 000, which is the base threshold of R50 000
#    halved by overlay ADJ-05-014 (sector 412, approved by Credit Committee on
#    2026-02-11, expiring 2026-08-31)"
# --------------------------------------------------------------------------
def material_threshold(
    event_type_code: int,
    criticality_class: int,          # <- broadcast from the Entity grain
    sector_code: int,                # <- broadcast from the Application grain
    decision_date: int,
) -> float:
    """The material threshold in force for this event type and entity class."""
    pass  # EVENT_THRESHOLDS[event_type_code, criticality_class].material_threshold


def disqualifying_threshold(
    event_type_code: int,
    criticality_class: int,
    sector_code: int,
    decision_date: int,
) -> float:
    """The disqualifying threshold in force. Overlay position 1 applies here."""
    pass


# `material_threshold_base`, `material_threshold_overlay_id`,
# `disqualifying_threshold_base` and `disqualifying_threshold_overlay_id` are
# generated by `overlay.position(1, ...)` on the table declaration. The author
# does not write them and cannot forget them. FRAMEWORK-DEMANDS D16.


def litigation_turnover_threshold(
    trailing_turnover: float,        # <- broadcast from the Application grain
    litigation_turnover_pct: float = param(
        25.0, ge=0.0, le=100.0,
        description="s5.5: litigation above this share of trailing turnover is "
                    "disqualifying irrespective of the rand thresholds"),
) -> float:
    """Litigation amount above this is disqualifying regardless of rand value."""
    pass


# --------------------------------------------------------------------------
# Age. One value, used by half the classification rules and by the ageing table.
# --------------------------------------------------------------------------
def event_age_months(event_date: int, decision_date: int) -> float:
    """Whole months between the event and decision_date. Never 'today'."""
    pass


def age_band_index(event_age_months: float) -> int:
    """0-6, 6-12, 12-24, 24-36, 36-60, 60+ -> 0..5."""
    pass


def months_since_satisfaction(
    satisfaction_date: int | None,
    decision_date: int,
) -> float | None:
    """None where unsatisfied.

    s4.4: "Required non-null where is_satisfied; a satisfied event with no date
    is a data-quality failure, not an old event." So this is tier-3 Optional
    (doc 03 s1) rather than `missing_as(999.0)`, and the data-quality rule is a
    separate validation step. Filling it would silently turn a data defect into
    a favourable classification.
    """
    pass


def unsatisfied_amount(
    amount: float | None,
    is_satisfied: bool,
) -> float | None:
    """The amount still outstanding, or None.

    None is load-bearing twice over: s4.4's "a judgment with no recorded amount
    is not a judgment for R0", and AE-C-07's `amount_unknown` flag. A
    `missing_as(0.0)` here would classify every amountless judgment as
    immaterial, which is the exact wrong answer.
    """
    pass


# --------------------------------------------------------------------------
# The thirty-four classification rules. Each is one step returning a severity.
# Shown: the seven load-bearing judgment rules plus the three that are
# structurally different. The rest follow the same shape.
#
# These are steps and not a `verdict(...)` because s5.5 is a *classification*:
# exactly one rule applies to each event, selected by type and state, and the
# selection is a branch rather than a collect-all. s5.6 is the roll-up and is
# the one that collects.
# --------------------------------------------------------------------------

def ae_c_03_fires(
    event_type_code: int,
    is_satisfied: bool,
    unsatisfied_amount: float | None,
    disqualifying_threshold: float,
) -> bool:
    """AE-C-03: judgment, unsatisfied, amount above the disqualifying threshold."""
    pass


def ae_c_04_fires(
    event_type_code: int,
    is_satisfied: bool,
    unsatisfied_amount: float | None,
    material_threshold: float,
    disqualifying_threshold: float,
    event_age_months: float,
    recent_judgment_months: float = param(36.0, ge=0.0, le=120.0),
) -> bool:
    """AE-C-04: judgment, unsatisfied, between the thresholds, age <= 36 months."""
    pass


def ae_c_06_fires(
    event_type_code: int,
    is_satisfied: bool,
    event_age_months: float,
    unsatisfied_amount: float | None,
    disqualifying_threshold: float,
    stale_judgment_months: float = param(60.0, ge=0.0, le=240.0),
) -> bool:
    """AE-C-06: unsatisfied judgment over 60 months old, below the disqualifying
    threshold. Minor -- an unsatisfied judgment never reaches immaterial."""
    pass


def ae_c_07_fires(
    event_type_code: int,
    is_satisfied: bool,
    amount: float | None,
) -> bool:
    """AE-C-07: judgment with a null amount, unsatisfied. Material, amount_unknown."""
    pass


def ae_c_17_fires(
    event_type_code: int,
    has_filed_plea: bool,
) -> bool:
    """AE-C-17: litigation, summons served, defended with a filed plea.

    Structurally different: it does not give a severity, it gives a *shift* --
    "one severity class lower than the amount implies". Modelled as a modifier,
    not a classifier, because composing a shift with AE-C-21's two-class
    downgrade and AE-C-22's one-class downgrade needs a declared order.
    """
    pass


def ae_c_21_fires(linked_rehabilitation_order: bool) -> bool:
    """AE-C-21: rehabilitation downgrades the linked sequestration by two classes,
    never below minor within 12 months of the order."""
    pass


def ae_c_22_fires(is_disputed: bool) -> bool:
    """AE-C-22: any disputed event is classified one class lower, never below
    minor, and flagged `classification_provisional`.

    This flag is what `evidence/counterfactual.py`'s DisputeShadow keys on. A
    disputed event may never be the sole cause of a decline, so the whole flow
    is evaluated a second time with every provisional classification removed --
    always, not on request.
    """
    pass


def event_severity_base(
    ae_c_03_fires: bool, ae_c_04_fires: bool, ae_c_06_fires: bool,
    ae_c_07_fires: bool,
    # ... the other thirty classification predicates
) -> int:
    """The severity before ageing and before the three modifiers.

    Exactly one classifier applies. The build asserts mutual exclusivity over
    the corpus (doc 03 s1.2's boundary-value requirement applies here: the
    corpus must include amounts exactly on both thresholds).
    """
    pass


def event_severity_aged(
    event_severity_base: int,
    event_type_code: int,
    age_band_index: int,
) -> int:
    """Apply the 14 x 6 ageing decay with its per-type floor."""
    pass


def event_severity_code(
    event_severity_aged: int,
    ae_c_17_fires: bool,
    ae_c_21_fires: bool,
    ae_c_22_fires: bool,
) -> int:
    """Apply the three modifiers in the declared order: plea, rehabilitation,
    dispute. Floors at MINOR where the modifier's own floor says so."""
    pass


def classifying_rule_id(
    ae_c_03_fires: bool, ae_c_04_fires: bool, ae_c_06_fires: bool,
    ae_c_07_fires: bool,
) -> int:
    """Which of the thirty-four rules classified this event.

    An output, not a tap. s5.5's "Emits" requires it per event including the
    immaterial ones: "An event classified immaterial is still an event a
    committee will ask about."
    """
    pass


def classification_provisional(ae_c_22_fires: bool) -> bool:
    """Set where a contributing classification rests on a disputed record."""
    pass


def amount_unknown(ae_c_07_fires: bool) -> bool:
    """AE-C-07's flag, carried all the way to the caller's data-quality set."""
    pass


ClassifyEvent = module(
    material_threshold, disqualifying_threshold, litigation_turnover_threshold,
    event_age_months, age_band_index, months_since_satisfaction,
    unsatisfied_amount,
    ae_c_03_fires, ae_c_04_fires, ae_c_06_fires, ae_c_07_fires,
    ae_c_17_fires, ae_c_21_fires, ae_c_22_fires,
    event_severity_base, event_severity_aged, event_severity_code,
    classifying_rule_id, classification_provisional, amount_unknown,
    name="classify_event",
    grain=Event,
    taps=["event_severity_code", "classifying_rule_id",
          "material_threshold", "material_threshold_base",
          "material_threshold_overlay_id",
          "disqualifying_threshold", "disqualifying_threshold_base",
          "disqualifying_threshold_overlay_id",
          "criticality_class",              # which entity class supplied them
          "classification_provisional", "branch_path"],
    contract="contracts/classify_event.json",
)
