"""Home loan: secured, 60 to 360 months, loan-to-value limits.

Generated by make_bank.py; edit the generator, not this file."""
from decider import flow

from bank.products.home_loan.affordability import hl_affordability
from bank.products.home_loan.limits import hl_limits
from bank.products.home_loan.policy import hl_policy
from bank.products.home_loan.pricing import hl_pricing
from bank.products.home_loan.scorecard import hl_scorecard
from bank.products.home_loan.stress import hl_stress

home_loan = flow(hl_scorecard, hl_policy, hl_pricing, hl_affordability, hl_stress, hl_limits, name="home_loan")
