"""Home loan: secured, 60 to 360 months, loan-to-value limits. Affordability: the instalment at the offered and a stressed rate against disposable income.

Generated by make_bank.py; edit the generator, not this file."""
from decider import flow, param, step


def hl_instalment(requested_amount: float, requested_term: float, hl_monthly_rate: float, hl_monthly_fee: float) -> float:
    return requested_amount * hl_monthly_rate / (1 - (1 + hl_monthly_rate) ** -requested_term) + hl_monthly_fee


def hl_stress_rate(hl_rate: float, buffer: float = param(0.02)) -> float:
    return hl_rate + buffer


def hl_stress_instalment(requested_amount: float, requested_term: float, hl_stress_rate: float) -> float:
    return requested_amount * (hl_stress_rate / 12) / (1 - (1 + hl_stress_rate / 12) ** -requested_term)


def hl_affordable_instalment(disposable_income_buffered: float, share: float = param(0.35)) -> float:
    return max(disposable_income_buffered * share, 0.0)


def hl_instalment_fits(hl_stress_instalment: float, hl_affordable_instalment: float) -> bool:
    return hl_stress_instalment <= hl_affordable_instalment


def hl_max_affordable_amount(hl_affordable_instalment: float, requested_term: float, hl_stress_rate: float) -> float:
    return hl_affordable_instalment * (1 - (1 + hl_stress_rate / 12) ** -requested_term) / (hl_stress_rate / 12)


def hl_dti_band_0(debt_service_ratio: float, lo: float = param(0), hi: float = param(0.2)) -> bool:
    return lo <= debt_service_ratio < hi


def hl_dti_band_1(debt_service_ratio: float, lo: float = param(0.2), hi: float = param(0.35)) -> bool:
    return lo <= debt_service_ratio < hi


def hl_dti_band_2(debt_service_ratio: float, lo: float = param(0.35), hi: float = param(0.5)) -> bool:
    return lo <= debt_service_ratio < hi


def hl_dti_band_3(debt_service_ratio: float, lo: float = param(0.5), hi: float = param(1.0)) -> bool:
    return lo <= debt_service_ratio < hi


def hl_grade_1_share(grade: int, share: float = param(1.0)) -> float:
    return share if grade == 1 else 0.0


def hl_grade_2_share(grade: int, share: float = param(0.85)) -> float:
    return share if grade == 2 else 0.0


def hl_grade_3_share(grade: int, share: float = param(0.7)) -> float:
    return share if grade == 3 else 0.0


def hl_grade_4_share(grade: int, share: float = param(0.55)) -> float:
    return share if grade == 4 else 0.0


def hl_grade_share(hl_grade_1_share: float, hl_grade_2_share: float, hl_grade_3_share: float, hl_grade_4_share: float) -> float:
    return hl_grade_1_share + hl_grade_2_share + hl_grade_3_share + hl_grade_4_share


hl_affordability = flow(
    hl_instalment,
    hl_stress_rate,
    hl_stress_instalment,
    hl_affordable_instalment,
    hl_instalment_fits,
    hl_max_affordable_amount,
    hl_dti_band_0,
    hl_dti_band_1,
    hl_dti_band_2,
    hl_dti_band_3,
    hl_grade_1_share,
    hl_grade_2_share,
    hl_grade_3_share,
    hl_grade_4_share,
    hl_grade_share,
    name="affordability",
)
