"""Home loan: secured, 60 to 360 months, loan-to-value limits. Limits: product caps and the offer.

Generated by make_bank.py; edit the generator, not this file."""
from decider import flow, param, step


def hl_product_cap(grade: int, cap: float = param(5000000.0)) -> float:
    return cap * (1.0 if grade <= 2 else 0.6)


def hl_ltv_cap(collateral_value: float, max_ltv: float = param(0.9)) -> float:
    return collateral_value * max_ltv


def hl_income_cap(gross_income: float, multiple: float = param(60.0)) -> float:
    return gross_income * multiple


def hl_max_amount(hl_product_cap: float, hl_ltv_cap: float, hl_income_cap: float, hl_max_affordable_amount: float, hl_grade_share: float) -> float:
    return min(hl_product_cap, hl_ltv_cap, hl_income_cap, hl_max_affordable_amount) * hl_grade_share


@step(output="offer_amount")
def hl_offer_amount(requested_amount: float, hl_max_amount: float, rounding: float = param(500.0)) -> float:
    return max(min(requested_amount, hl_max_amount) // rounding * rounding, 0.0)


@step(output="offer_term")
def hl_offer_term(requested_term: float) -> float:
    return requested_term


@step(output="offer_rate")
def hl_offer_rate(hl_rate: float) -> float:
    return hl_rate


@step(output="monthly_instalment")
def hl_offer_instalment(offer_amount: float, offer_term: float, hl_monthly_rate: float, hl_monthly_fee: float) -> float:
    return offer_amount * hl_monthly_rate / (1 - (1 + hl_monthly_rate) ** -offer_term) + hl_monthly_fee if offer_amount > 0 else 0.0


@step(output="declined")
def hl_declined(hl_policy_declined: bool, hl_instalment_fits: bool, offer_amount: float, minimum: float = param(100000.0)) -> bool:
    return hl_policy_declined or offer_amount < minimum


@step(output="decline_reason")
def hl_decline_reason(hl_policy_reason: str, hl_policy_declined: bool, declined: bool) -> str:
    return hl_policy_reason if hl_policy_declined else ("Offer below the product minimum" if declined else "")


hl_limits = flow(
    hl_product_cap,
    hl_ltv_cap,
    hl_income_cap,
    hl_max_amount,
    hl_offer_amount,
    hl_offer_term,
    hl_offer_rate,
    hl_offer_instalment,
    hl_declined,
    hl_decline_reason,
    name="limits",
)
