"""Home loan: secured, 60 to 360 months, loan-to-value limits. Pricing: the base rate by term, a loading by risk grade, fees by amount, capped by regulation.

Generated by make_bank.py; edit the generator, not this file."""
from decider import dag, flow, param, step

from bank.lookup import LookupTable

hl_base_rates = LookupTable(
    name="hl_base_rates",
    ranges={"requested_term": ["min_term", "max_term"]},
    returns={"hl_base_rate": "rate"},
    rows=[{"min_term": 60, "max_term": 180, "rate": 0.1175}, {"min_term": 181, "max_term": 240, "rate": 0.1225}, {"min_term": 241, "max_term": 360, "rate": 0.1275}],
)
hl_risk_loadings = LookupTable(
    name="hl_risk_loadings",
    keys={"grade": "grade"},
    returns={"hl_risk_loading": "loading"},
    rows=[{"grade": 1, "loading": 0.0}, {"grade": 2, "loading": 0.005}, {"grade": 3, "loading": 0.01}, {"grade": 4, "loading": 0.015}],
)
hl_fees = LookupTable(
    name="hl_fees",
    ranges={"requested_amount": ["min_amount", "max_amount"]},
    returns={"hl_initiation_fee": "initiation_fee", "hl_monthly_fee": "monthly_fee"},
    rows=[{"min_amount": 0, "max_amount": 1000000, "initiation_fee": 6037.5, "monthly_fee": 69.0}, {"min_amount": 1000001, "max_amount": 100000000, "initiation_fee": 6037.5, "monthly_fee": 69.0}],
)


def hl_salary_discount(salary_account: bool, discount: float = param(0.005)) -> float:
    return discount if salary_account else 0.0


def hl_channel_discount(channel: str, app_discount: float = param(0.0025)) -> float:
    return app_discount if channel == "app" else 0.0


def hl_loyalty_discount(months_at_address: float, discount: float = param(0.001)) -> float:
    return discount if months_at_address > 60 else 0.0


def hl_clean_record_discount(clean_record: bool, discount: float = param(0.002)) -> float:
    return discount if clean_record else 0.0


def hl_fraud_loading(fraud_referral: bool, loading: float = param(0.01)) -> float:
    return loading if fraud_referral else 0.0


def hl_collections_loading(collections_band: int, per_band: float = param(0.0075)) -> float:
    return per_band * (collections_band - 1)


def hl_raw_rate(hl_base_rate: float, hl_risk_loading: float, hl_salary_discount: float, hl_channel_discount: float, hl_loyalty_discount: float, hl_clean_record_discount: float, hl_fraud_loading: float, hl_collections_loading: float) -> float:
    return hl_base_rate + hl_risk_loading - hl_salary_discount - hl_channel_discount - hl_loyalty_discount - hl_clean_record_discount + hl_fraud_loading + hl_collections_loading


@step(output="hl_rate")
def hl_regulated_rate(hl_raw_rate: float, repo_rate: float = param(0.0775, shared_key="repo_rate"),
                        cap_multiple: float = param(1.0), cap_margin: float = param(0.12)) -> float:
    """The National Credit Act cap: repo times a multiple plus a margin."""
    return min(hl_raw_rate, repo_rate * cap_multiple + cap_margin)


def hl_monthly_rate(hl_rate: float) -> float:
    return hl_rate / 12


hl_pricing = flow(
    hl_base_rates,
    hl_risk_loadings,
    hl_fees,
    hl_salary_discount,
    hl_channel_discount,
    hl_loyalty_discount,
    hl_clean_record_discount,
    hl_fraud_loading,
    hl_collections_loading,
    hl_raw_rate,
    hl_regulated_rate,
    hl_monthly_rate,
    name="pricing",
)
