"""Home loan: secured, 60 to 360 months, loan-to-value limits. Pricing: the base rate by term, a loading by risk grade, fees by amount, capped by regulation.

Generated by make_bank.py; edit the generator, not this file."""
from decider import dag, flow, param, step
from decider.steps.tables import DecisionTableConfig

hl_base_rates = DecisionTableConfig(
    name="hl_base_rates",
    columns={"min_term": "Float64", "max_term": "Float64", "hl_base_rate": "Float64"},
    rows={"table": "hl_base_rates", "shared": True},
    expression={"type": "between", "variable": "requested_term", "lower_bound_column": "min_term", "upper_bound_column": "max_term"},
    outputs=["hl_base_rate"],
)
hl_risk_loadings = DecisionTableConfig(
    name="hl_risk_loadings",
    columns={"grade_key": "Int64", "hl_risk_loading": "Float64"},
    rows={"table": "hl_risk_loadings", "shared": True},
    expression={"type": "eq", "variable": "grade", "value_column": "grade_key"},
    outputs=["hl_risk_loading"],
)
hl_fees = DecisionTableConfig(
    name="hl_fees",
    columns={"min_amount": "Float64", "max_amount": "Float64", "hl_initiation_fee": "Float64", "hl_monthly_fee": "Float64"},
    rows={"table": "hl_fees", "shared": True},
    expression={"type": "between", "variable": "requested_amount", "lower_bound_column": "min_amount", "upper_bound_column": "max_amount"},
    outputs=["hl_initiation_fee", "hl_monthly_fee"],
)


def hl_salary_discount(salary_account: bool, discount: float = param(0.005)) -> float:
    return discount if salary_account else 0.0


def hl_channel_discount(channel_discount: float, weight: float = param(1.0)) -> float:
    return channel_discount * weight


def hl_loyalty_discount(months_at_address: float, discount: float = param(0.001)) -> float:
    return discount if months_at_address > 60 else 0.0


def hl_clean_record_discount(clean_record: bool, discount: float = param(0.002)) -> float:
    return discount if clean_record else 0.0


def hl_fraud_loading(fraud_referral: bool, loading: float = param(0.01)) -> float:
    return loading if fraud_referral else 0.0


def hl_collections_loading(collections_band: int, per_band: float = param(0.0075)) -> float:
    return per_band * (collections_band - 1)


def hl_raw_rate(hl_base_rate: float, hl_risk_loading: float, hl_salary_discount: float, hl_channel_discount: float, hl_loyalty_discount: float, hl_clean_record_discount: float, hl_fraud_loading: float, hl_collections_loading: float) -> float:
    return hl_base_rate + hl_risk_loading - hl_salary_discount - hl_channel_discount - hl_loyalty_discount - hl_clean_record_discount + hl_fraud_loading + hl_collections_loading


@step(output="hl_rate")
def hl_regulated_rate(hl_raw_rate: float, repo_rate: float = param(0.0775, shared_key="repo_rate"),
                        cap_multiple: float = param(1.0), cap_margin: float = param(0.12)) -> float:
    """The National Credit Act cap: repo times a multiple plus a margin."""
    return min(hl_raw_rate, repo_rate * cap_multiple + cap_margin)


def hl_monthly_rate(hl_rate: float) -> float:
    return hl_rate / 12


hl_pricing = flow(
    hl_base_rates,
    hl_risk_loadings,
    hl_fees,
    hl_salary_discount,
    hl_channel_discount,
    hl_loyalty_discount,
    hl_clean_record_discount,
    hl_fraud_loading,
    hl_collections_loading,
    hl_raw_rate,
    hl_regulated_rate,
    hl_monthly_rate,
    name="pricing",
)
