"""Home loan: secured, 60 to 360 months, loan-to-value limits. Application scorecard: points per characteristic, summed into a score.

Generated by make_bank.py; edit the generator, not this file."""
from decider import flow, param, step


def hl_pts_bureau_score(bureau_score: float, cut_1: float = param(0.36), cut_2: float = param(0.54), cut_3: float = param(0.58),
        pts_1: float = param(20.0), pts_2: float = param(-10.0), pts_3: float = param(-15.0), pts_4: float = param(20.0)) -> float:
    x = bureau_score
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def hl_pts_months_employed(months_employed: float, cut_1: float = param(0.67), cut_2: float = param(0.87), cut_3: float = param(0.91),
        pts_1: float = param(-15.0), pts_2: float = param(5.0), pts_3: float = param(20.0), pts_4: float = param(40.0)) -> float:
    x = months_employed
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def hl_pts_months_at_address(months_at_address: float, cut_1: float = param(0.09), cut_2: float = param(0.69), cut_3: float = param(0.85),
        pts_1: float = param(20.0), pts_2: float = param(-15.0), pts_3: float = param(5.0), pts_4: float = param(-20.0)) -> float:
    x = months_at_address
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def hl_pts_age(age: float, cut_1: float = param(0.21), cut_2: float = param(0.89), cut_3: float = param(0.9),
        pts_1: float = param(35.0), pts_2: float = param(-5.0), pts_3: float = param(25.0), pts_4: float = param(30.0)) -> float:
    x = age
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def hl_pts_debt_service_ratio(debt_service_ratio: float, cut_1: float = param(0.23), cut_2: float = param(0.31), cut_3: float = param(0.69),
        pts_1: float = param(-5.0), pts_2: float = param(25.0), pts_3: float = param(-10.0), pts_4: float = param(-15.0)) -> float:
    x = debt_service_ratio
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def hl_pts_card_utilisation(card_utilisation: float, cut_1: float = param(0.04), cut_2: float = param(0.39), cut_3: float = param(0.55),
        pts_1: float = param(-5.0), pts_2: float = param(0.0), pts_3: float = param(30.0), pts_4: float = param(-10.0)) -> float:
    x = card_utilisation
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def hl_pts_enquiries_6m(enquiries_6m: float, cut_1: float = param(0.17), cut_2: float = param(0.63), cut_3: float = param(0.76),
        pts_1: float = param(-10.0), pts_2: float = param(5.0), pts_3: float = param(10.0), pts_4: float = param(-15.0)) -> float:
    x = enquiries_6m
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def hl_pts_missed_payments_12m(missed_payments_12m: float, cut_1: float = param(0.1), cut_2: float = param(0.29), cut_3: float = param(0.4),
        pts_1: float = param(-10.0), pts_2: float = param(25.0), pts_3: float = param(-20.0), pts_4: float = param(30.0)) -> float:
    x = missed_payments_12m
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def hl_pts_dependants(dependants: float, cut_1: float = param(0.45), cut_2: float = param(0.52), cut_3: float = param(0.62),
        pts_1: float = param(-5.0), pts_2: float = param(-15.0), pts_3: float = param(-15.0), pts_4: float = param(25.0)) -> float:
    x = dependants
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def hl_pts_disposable_income(disposable_income: float, cut_1: float = param(0.51), cut_2: float = param(0.67), cut_3: float = param(0.86),
        pts_1: float = param(10.0), pts_2: float = param(-20.0), pts_3: float = param(40.0), pts_4: float = param(35.0)) -> float:
    x = disposable_income
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def hl_pts_expenses_to_net_income(expenses_to_net_income: float, cut_1: float = param(0.06), cut_2: float = param(0.32), cut_3: float = param(0.47),
        pts_1: float = param(35.0), pts_2: float = param(0.0), pts_3: float = param(20.0), pts_4: float = param(0.0)) -> float:
    x = expenses_to_net_income
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def hl_pts_requested_amount_to_gross_income(requested_amount_to_gross_income: float, cut_1: float = param(0.33), cut_2: float = param(0.6), cut_3: float = param(0.93),
        pts_1: float = param(25.0), pts_2: float = param(30.0), pts_3: float = param(15.0), pts_4: float = param(-10.0)) -> float:
    x = requested_amount_to_gross_income
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def hl_pts_existing_instalments_to_net_income(existing_instalments_to_net_income: float, cut_1: float = param(0.11), cut_2: float = param(0.27), cut_3: float = param(0.86),
        pts_1: float = param(-15.0), pts_2: float = param(0.0), pts_3: float = param(30.0), pts_4: float = param(5.0)) -> float:
    x = existing_instalments_to_net_income
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def hl_pts_net_income(net_income: float, cut_1: float = param(0.29), cut_2: float = param(0.79), cut_3: float = param(0.8),
        pts_1: float = param(0.0), pts_2: float = param(10.0), pts_3: float = param(10.0), pts_4: float = param(0.0)) -> float:
    x = net_income
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def hl_pts_gross_income(gross_income: float, cut_1: float = param(0.36), cut_2: float = param(0.63), cut_3: float = param(0.84),
        pts_1: float = param(25.0), pts_2: float = param(15.0), pts_3: float = param(5.0), pts_4: float = param(25.0)) -> float:
    x = gross_income
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def hl_pts_judgements(judgements: float, cut_1: float = param(0.1), cut_2: float = param(0.41), cut_3: float = param(0.88),
        pts_1: float = param(-20.0), pts_2: float = param(-10.0), pts_3: float = param(-10.0), pts_4: float = param(30.0)) -> float:
    x = judgements
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def hl_pts_months_employed_to_age(months_employed_to_age: float, cut_1: float = param(0.13), cut_2: float = param(0.47), cut_3: float = param(0.75),
        pts_1: float = param(30.0), pts_2: float = param(-10.0), pts_3: float = param(20.0), pts_4: float = param(-20.0)) -> float:
    x = months_employed_to_age
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def hl_pts_enquiries_6m_to_months_at_address(enquiries_6m_to_months_at_address: float, cut_1: float = param(0.23), cut_2: float = param(0.47), cut_3: float = param(0.51),
        pts_1: float = param(0.0), pts_2: float = param(-10.0), pts_3: float = param(25.0), pts_4: float = param(0.0)) -> float:
    x = enquiries_6m_to_months_at_address
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def hl_pts_card_utilisation_to_bureau_score(card_utilisation_to_bureau_score: float, cut_1: float = param(0.37), cut_2: float = param(0.61), cut_3: float = param(0.78),
        pts_1: float = param(25.0), pts_2: float = param(30.0), pts_3: float = param(-10.0), pts_4: float = param(35.0)) -> float:
    x = card_utilisation_to_bureau_score
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def hl_pts_expenses_to_gross_income(expenses_to_gross_income: float, cut_1: float = param(0.06), cut_2: float = param(0.21), cut_3: float = param(0.34),
        pts_1: float = param(15.0), pts_2: float = param(-20.0), pts_3: float = param(30.0), pts_4: float = param(-10.0)) -> float:
    x = expenses_to_gross_income
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def hl_pts_net_income_zscore(net_income_zscore: float, cut_1: float = param(0.05), cut_2: float = param(0.32), cut_3: float = param(0.7),
        pts_1: float = param(0.0), pts_2: float = param(40.0), pts_3: float = param(-10.0), pts_4: float = param(5.0)) -> float:
    x = net_income_zscore
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def hl_pts_bureau_score_zscore(bureau_score_zscore: float, cut_1: float = param(0.38), cut_2: float = param(0.76), cut_3: float = param(0.88),
        pts_1: float = param(0.0), pts_2: float = param(-10.0), pts_3: float = param(-10.0), pts_4: float = param(15.0)) -> float:
    x = bureau_score_zscore
    return pts_1 if x < cut_1 else (pts_2 if x < cut_2 else (pts_3 if x < cut_3 else pts_4))


def hl_score(hl_pts_bureau_score: float, hl_pts_months_employed: float, hl_pts_months_at_address: float, hl_pts_age: float, hl_pts_debt_service_ratio: float, hl_pts_card_utilisation: float, hl_pts_enquiries_6m: float, hl_pts_missed_payments_12m: float, hl_pts_dependants: float, hl_pts_disposable_income: float, hl_pts_expenses_to_net_income: float, hl_pts_requested_amount_to_gross_income: float, hl_pts_existing_instalments_to_net_income: float, hl_pts_net_income: float, hl_pts_gross_income: float, hl_pts_judgements: float, hl_pts_months_employed_to_age: float, hl_pts_enquiries_6m_to_months_at_address: float, hl_pts_card_utilisation_to_bureau_score: float, hl_pts_expenses_to_gross_income: float, hl_pts_net_income_zscore: float, hl_pts_bureau_score_zscore: float, intercept: float = param(600.0)) -> float:
    return intercept + hl_pts_bureau_score + hl_pts_months_employed + hl_pts_months_at_address + hl_pts_age + hl_pts_debt_service_ratio + hl_pts_card_utilisation + hl_pts_enquiries_6m + hl_pts_missed_payments_12m + hl_pts_dependants + hl_pts_disposable_income + hl_pts_expenses_to_net_income + hl_pts_requested_amount_to_gross_income + hl_pts_existing_instalments_to_net_income + hl_pts_net_income + hl_pts_gross_income + hl_pts_judgements + hl_pts_months_employed_to_age + hl_pts_enquiries_6m_to_months_at_address + hl_pts_card_utilisation_to_bureau_score + hl_pts_expenses_to_gross_income + hl_pts_net_income_zscore + hl_pts_bureau_score_zscore


def hl_score_band(hl_score: float, low: float = param(580.0), high: float = param(680.0)) -> int:
    return 3 if hl_score < low else (2 if hl_score < high else 1)


hl_scorecard = flow(
    hl_pts_bureau_score,
    hl_pts_months_employed,
    hl_pts_months_at_address,
    hl_pts_age,
    hl_pts_debt_service_ratio,
    hl_pts_card_utilisation,
    hl_pts_enquiries_6m,
    hl_pts_missed_payments_12m,
    hl_pts_dependants,
    hl_pts_disposable_income,
    hl_pts_expenses_to_net_income,
    hl_pts_requested_amount_to_gross_income,
    hl_pts_existing_instalments_to_net_income,
    hl_pts_net_income,
    hl_pts_gross_income,
    hl_pts_judgements,
    hl_pts_months_employed_to_age,
    hl_pts_enquiries_6m_to_months_at_address,
    hl_pts_card_utilisation_to_bureau_score,
    hl_pts_expenses_to_gross_income,
    hl_pts_net_income_zscore,
    hl_pts_bureau_score_zscore,
    hl_score,
    hl_score_band,
    name="scorecard",
)
