"""Behaviour on the bureau: arrears, enquiries, judgements.

Generated by make_bank.py; edit the generator, not this file."""
import math  # noqa: F401

from decider import dag, param, step  # noqa: F401


def bureau_score_band(bureau_score: float, low: float = param(27.0), mid: float = param(67.0), high: float = param(75.0)) -> float:
    return float((bureau_score > low) + (bureau_score > mid) + (bureau_score > high))


def bureau_score_high(bureau_score: float, threshold: float = param(75.0)) -> bool:
    return bureau_score > threshold


def bureau_score_capped(bureau_score: float, cap: float = param(225.0)) -> float:
    return min(bureau_score, cap)


def bureau_score_log(bureau_score: float) -> float:
    return math.log1p(max(bureau_score, 0.0))


def bureau_score_zscore(bureau_score: float, mean: float = param(67.0), std: float = param(48.0)) -> float:
    return (bureau_score - mean) / std


def bureau_score_above_median(bureau_score: float, median: float = param(67.0)) -> bool:
    return bureau_score > median


def bureau_score_floor(bureau_score: float, floor: float = param(27.0)) -> float:
    return max(bureau_score, floor)


def missed_payments_12m_band(missed_payments_12m: float, low: float = param(3.5), mid: float = param(8.5), high: float = param(9.8)) -> float:
    return float((missed_payments_12m > low) + (missed_payments_12m > mid) + (missed_payments_12m > high))


def missed_payments_12m_high(missed_payments_12m: float, threshold: float = param(9.8)) -> bool:
    return missed_payments_12m > threshold


def missed_payments_12m_capped(missed_payments_12m: float, cap: float = param(29.400000000000002)) -> float:
    return min(missed_payments_12m, cap)


def missed_payments_12m_log(missed_payments_12m: float) -> float:
    return math.log1p(max(missed_payments_12m, 0.0))


def missed_payments_12m_zscore(missed_payments_12m: float, mean: float = param(8.5), std: float = param(6.300000000000001)) -> float:
    return (missed_payments_12m - mean) / std


def missed_payments_12m_above_median(missed_payments_12m: float, median: float = param(8.5)) -> bool:
    return missed_payments_12m > median


def missed_payments_12m_floor(missed_payments_12m: float, floor: float = param(3.5)) -> float:
    return max(missed_payments_12m, floor)


def enquiries_6m_band(enquiries_6m: float, low: float = param(11.0), mid: float = param(16.2), high: float = param(16.5)) -> float:
    return float((enquiries_6m > low) + (enquiries_6m > mid) + (enquiries_6m > high))


def enquiries_6m_high(enquiries_6m: float, threshold: float = param(16.5)) -> bool:
    return enquiries_6m > threshold


def enquiries_6m_capped(enquiries_6m: float, cap: float = param(49.5)) -> float:
    return min(enquiries_6m, cap)


def enquiries_6m_log(enquiries_6m: float) -> float:
    return math.log1p(max(enquiries_6m, 0.0))


def enquiries_6m_zscore(enquiries_6m: float, mean: float = param(16.2), std: float = param(5.5)) -> float:
    return (enquiries_6m - mean) / std


def enquiries_6m_above_median(enquiries_6m: float, median: float = param(16.2)) -> bool:
    return enquiries_6m > median


def enquiries_6m_floor(enquiries_6m: float, floor: float = param(11.0)) -> float:
    return max(enquiries_6m, floor)


def judgements_band(judgements: float, low: float = param(2.0), mid: float = param(4.8), high: float = param(8.8)) -> float:
    return float((judgements > low) + (judgements > mid) + (judgements > high))


def judgements_high(judgements: float, threshold: float = param(8.8)) -> bool:
    return judgements > threshold


def judgements_capped(judgements: float, cap: float = param(26.400000000000002)) -> float:
    return min(judgements, cap)


def judgements_log(judgements: float) -> float:
    return math.log1p(max(judgements, 0.0))


def judgements_zscore(judgements: float, mean: float = param(4.8), std: float = param(6.800000000000001)) -> float:
    return (judgements - mean) / std


def judgements_above_median(judgements: float, median: float = param(4.8)) -> bool:
    return judgements > median


def judgements_floor(judgements: float, floor: float = param(2.0)) -> float:
    return max(judgements, floor)


def clean_record(missed_payments_12m: float, judgements: float) -> bool:
    return missed_payments_12m == 0 and judgements == 0


behaviour = dag(
    bureau_score_band,
    bureau_score_high,
    bureau_score_capped,
    bureau_score_log,
    bureau_score_zscore,
    bureau_score_above_median,
    bureau_score_floor,
    missed_payments_12m_band,
    missed_payments_12m_high,
    missed_payments_12m_capped,
    missed_payments_12m_log,
    missed_payments_12m_zscore,
    missed_payments_12m_above_median,
    missed_payments_12m_floor,
    enquiries_6m_band,
    enquiries_6m_high,
    enquiries_6m_capped,
    enquiries_6m_log,
    enquiries_6m_zscore,
    enquiries_6m_above_median,
    enquiries_6m_floor,
    judgements_band,
    judgements_high,
    judgements_capped,
    judgements_log,
    judgements_zscore,
    judgements_above_median,
    judgements_floor,
    clean_record,
    name="behaviour",
)
