"""Debt: repayment load, utilisation and ratios.

Generated by make_bank.py; edit the generator, not this file."""
import math  # noqa: F401

from decider import dag, param, step  # noqa: F401


def existing_instalments_band(existing_instalments: float, low: float = param(600.0), mid: float = param(8040.0), high: float = param(9960.0)) -> float:
    return float((existing_instalments > low) + (existing_instalments > mid) + (existing_instalments > high))


def existing_instalments_high(existing_instalments: float, threshold: float = param(9960.0)) -> bool:
    return existing_instalments > threshold


def existing_instalments_capped(existing_instalments: float, cap: float = param(29880.0)) -> float:
    return min(existing_instalments, cap)


def existing_instalments_log(existing_instalments: float) -> float:
    return math.log1p(max(existing_instalments, 0.0))


def existing_instalments_zscore(existing_instalments: float, mean: float = param(8040.0), std: float = param(9360.0)) -> float:
    return (existing_instalments - mean) / std


def existing_instalments_above_median(existing_instalments: float, median: float = param(8040.0)) -> bool:
    return existing_instalments > median


def existing_instalments_floor(existing_instalments: float, floor: float = param(600.0)) -> float:
    return max(existing_instalments, floor)


def requested_amount_band(requested_amount: float, low: float = param(2000.0), mid: float = param(50000.0), high: float = param(144000.0)) -> float:
    return float((requested_amount > low) + (requested_amount > mid) + (requested_amount > high))


def requested_amount_high(requested_amount: float, threshold: float = param(144000.0)) -> bool:
    return requested_amount > threshold


def requested_amount_capped(requested_amount: float, cap: float = param(432000.0)) -> float:
    return min(requested_amount, cap)


def requested_amount_log(requested_amount: float) -> float:
    return math.log1p(max(requested_amount, 0.0))


def requested_amount_zscore(requested_amount: float, mean: float = param(50000.0), std: float = param(142000.0)) -> float:
    return (requested_amount - mean) / std


def requested_amount_above_median(requested_amount: float, median: float = param(50000.0)) -> bool:
    return requested_amount > median


def requested_amount_floor(requested_amount: float, floor: float = param(2000.0)) -> float:
    return max(requested_amount, floor)


def collateral_value_band(collateral_value: float, low: float = param(258000.0), mid: float = param(408000.0), high: float = param(438000.0)) -> float:
    return float((collateral_value > low) + (collateral_value > mid) + (collateral_value > high))


def collateral_value_high(collateral_value: float, threshold: float = param(438000.0)) -> bool:
    return collateral_value > threshold


def collateral_value_capped(collateral_value: float, cap: float = param(1314000.0)) -> float:
    return min(collateral_value, cap)


def collateral_value_log(collateral_value: float) -> float:
    return math.log1p(max(collateral_value, 0.0))


def collateral_value_zscore(collateral_value: float, mean: float = param(408000.0), std: float = param(180000.0)) -> float:
    return (collateral_value - mean) / std


def collateral_value_above_median(collateral_value: float, median: float = param(408000.0)) -> bool:
    return collateral_value > median


def collateral_value_floor(collateral_value: float, floor: float = param(258000.0)) -> float:
    return max(collateral_value, floor)


def card_utilisation_band(card_utilisation: float, low: float = param(5.0), mid: float = param(13.5), high: float = param(19.2)) -> float:
    return float((card_utilisation > low) + (card_utilisation > mid) + (card_utilisation > high))


def card_utilisation_high(card_utilisation: float, threshold: float = param(19.2)) -> bool:
    return card_utilisation > threshold


def card_utilisation_capped(card_utilisation: float, cap: float = param(57.599999999999994)) -> float:
    return min(card_utilisation, cap)


def card_utilisation_log(card_utilisation: float) -> float:
    return math.log1p(max(card_utilisation, 0.0))


def card_utilisation_zscore(card_utilisation: float, mean: float = param(13.5), std: float = param(14.2)) -> float:
    return (card_utilisation - mean) / std


def card_utilisation_above_median(card_utilisation: float, median: float = param(13.5)) -> bool:
    return card_utilisation > median


def card_utilisation_floor(card_utilisation: float, floor: float = param(5.0)) -> float:
    return max(card_utilisation, floor)


def debt_service_ratio(existing_instalments: float, gross_income: float) -> float:
    return existing_instalments / max(gross_income, 1.0)


debt = dag(
    existing_instalments_band,
    existing_instalments_high,
    existing_instalments_capped,
    existing_instalments_log,
    existing_instalments_zscore,
    existing_instalments_above_median,
    existing_instalments_floor,
    requested_amount_band,
    requested_amount_high,
    requested_amount_capped,
    requested_amount_log,
    requested_amount_zscore,
    requested_amount_above_median,
    requested_amount_floor,
    collateral_value_band,
    collateral_value_high,
    collateral_value_capped,
    collateral_value_log,
    collateral_value_zscore,
    collateral_value_above_median,
    collateral_value_floor,
    card_utilisation_band,
    card_utilisation_high,
    card_utilisation_capped,
    card_utilisation_log,
    card_utilisation_zscore,
    card_utilisation_above_median,
    card_utilisation_floor,
    debt_service_ratio,
    name="debt",
)
