"""Composite indicators built from the other features.

Generated by make_bank.py; edit the generator, not this file."""
import math  # noqa: F401

from decider import dag, param, step  # noqa: F401


def existing_instalments_to_net_income(existing_instalments: float, net_income: float) -> float:
    return existing_instalments / max(net_income, 1.0)


def existing_instalments_to_net_income_flag(existing_instalments: float, net_income: float, limit: float = param(0.65)) -> bool:
    return existing_instalments / max(net_income, 1.0) > limit


def expenses_to_net_income(expenses: float, net_income: float) -> float:
    return expenses / max(net_income, 1.0)


def expenses_to_net_income_flag(expenses: float, net_income: float, limit: float = param(0.3)) -> bool:
    return expenses / max(net_income, 1.0) > limit


def requested_amount_to_gross_income(requested_amount: float, gross_income: float) -> float:
    return requested_amount / max(gross_income, 1.0)


def requested_amount_to_gross_income_flag(requested_amount: float, gross_income: float, limit: float = param(0.47)) -> bool:
    return requested_amount / max(gross_income, 1.0) > limit


def requested_amount_to_collateral_value(requested_amount: float, collateral_value: float) -> float:
    return requested_amount / max(collateral_value, 1.0)


def requested_amount_to_collateral_value_flag(requested_amount: float, collateral_value: float, limit: float = param(0.51)) -> bool:
    return requested_amount / max(collateral_value, 1.0) > limit


def existing_instalments_to_gross_income(existing_instalments: float, gross_income: float) -> float:
    return existing_instalments / max(gross_income, 1.0)


def existing_instalments_to_gross_income_flag(existing_instalments: float, gross_income: float, limit: float = param(0.47)) -> bool:
    return existing_instalments / max(gross_income, 1.0) > limit


def expenses_to_gross_income(expenses: float, gross_income: float) -> float:
    return expenses / max(gross_income, 1.0)


def expenses_to_gross_income_flag(expenses: float, gross_income: float, limit: float = param(0.25)) -> bool:
    return expenses / max(gross_income, 1.0) > limit


def months_employed_to_age(months_employed: float, age: float) -> float:
    return months_employed / max(age, 1.0)


def months_employed_to_age_flag(months_employed: float, age: float, limit: float = param(0.31)) -> bool:
    return months_employed / max(age, 1.0) > limit


def months_at_address_to_age(months_at_address: float, age: float) -> float:
    return months_at_address / max(age, 1.0)


def months_at_address_to_age_flag(months_at_address: float, age: float, limit: float = param(0.57)) -> bool:
    return months_at_address / max(age, 1.0) > limit


def dependants_to_net_income(dependants: float, net_income: float) -> float:
    return dependants / max(net_income, 1.0)


def dependants_to_net_income_flag(dependants: float, net_income: float, limit: float = param(0.35)) -> bool:
    return dependants / max(net_income, 1.0) > limit


def missed_payments_12m_to_months_employed(missed_payments_12m: float, months_employed: float) -> float:
    return missed_payments_12m / max(months_employed, 1.0)


def missed_payments_12m_to_months_employed_flag(missed_payments_12m: float, months_employed: float, limit: float = param(0.34)) -> bool:
    return missed_payments_12m / max(months_employed, 1.0) > limit


def enquiries_6m_to_months_at_address(enquiries_6m: float, months_at_address: float) -> float:
    return enquiries_6m / max(months_at_address, 1.0)


def enquiries_6m_to_months_at_address_flag(enquiries_6m: float, months_at_address: float, limit: float = param(0.59)) -> bool:
    return enquiries_6m / max(months_at_address, 1.0) > limit


def card_utilisation_to_bureau_score(card_utilisation: float, bureau_score: float) -> float:
    return card_utilisation / max(bureau_score, 1.0)


def card_utilisation_to_bureau_score_flag(card_utilisation: float, bureau_score: float, limit: float = param(0.29)) -> bool:
    return card_utilisation / max(bureau_score, 1.0) > limit


def gross_income_to_net_income(gross_income: float, net_income: float) -> float:
    return gross_income / max(net_income, 1.0)


def gross_income_to_net_income_flag(gross_income: float, net_income: float, limit: float = param(0.35)) -> bool:
    return gross_income / max(net_income, 1.0) > limit


def gross_income_to_collateral_value(gross_income: float, collateral_value: float) -> float:
    return gross_income / max(collateral_value, 1.0)


def gross_income_to_collateral_value_flag(gross_income: float, collateral_value: float, limit: float = param(0.24)) -> bool:
    return gross_income / max(collateral_value, 1.0) > limit


def net_income_to_requested_amount(net_income: float, requested_amount: float) -> float:
    return net_income / max(requested_amount, 1.0)


def net_income_to_requested_amount_flag(net_income: float, requested_amount: float, limit: float = param(0.52)) -> bool:
    return net_income / max(requested_amount, 1.0) > limit


def net_income_to_collateral_value(net_income: float, collateral_value: float) -> float:
    return net_income / max(collateral_value, 1.0)


def net_income_to_collateral_value_flag(net_income: float, collateral_value: float, limit: float = param(0.52)) -> bool:
    return net_income / max(collateral_value, 1.0) > limit


def expenses_to_existing_instalments(expenses: float, existing_instalments: float) -> float:
    return expenses / max(existing_instalments, 1.0)


def expenses_to_existing_instalments_flag(expenses: float, existing_instalments: float, limit: float = param(0.35)) -> bool:
    return expenses / max(existing_instalments, 1.0) > limit


def expenses_to_requested_amount(expenses: float, requested_amount: float) -> float:
    return expenses / max(requested_amount, 1.0)


def expenses_to_requested_amount_flag(expenses: float, requested_amount: float, limit: float = param(0.7)) -> bool:
    return expenses / max(requested_amount, 1.0) > limit


def expenses_to_collateral_value(expenses: float, collateral_value: float) -> float:
    return expenses / max(collateral_value, 1.0)


def expenses_to_collateral_value_flag(expenses: float, collateral_value: float, limit: float = param(0.54)) -> bool:
    return expenses / max(collateral_value, 1.0) > limit


def existing_instalments_to_requested_amount(existing_instalments: float, requested_amount: float) -> float:
    return existing_instalments / max(requested_amount, 1.0)


def existing_instalments_to_requested_amount_flag(existing_instalments: float, requested_amount: float, limit: float = param(0.51)) -> bool:
    return existing_instalments / max(requested_amount, 1.0) > limit


def existing_instalments_to_collateral_value(existing_instalments: float, collateral_value: float) -> float:
    return existing_instalments / max(collateral_value, 1.0)


def existing_instalments_to_collateral_value_flag(existing_instalments: float, collateral_value: float, limit: float = param(0.54)) -> bool:
    return existing_instalments / max(collateral_value, 1.0) > limit


derived = dag(
    existing_instalments_to_net_income,
    existing_instalments_to_net_income_flag,
    expenses_to_net_income,
    expenses_to_net_income_flag,
    requested_amount_to_gross_income,
    requested_amount_to_gross_income_flag,
    requested_amount_to_collateral_value,
    requested_amount_to_collateral_value_flag,
    existing_instalments_to_gross_income,
    existing_instalments_to_gross_income_flag,
    expenses_to_gross_income,
    expenses_to_gross_income_flag,
    months_employed_to_age,
    months_employed_to_age_flag,
    months_at_address_to_age,
    months_at_address_to_age_flag,
    dependants_to_net_income,
    dependants_to_net_income_flag,
    missed_payments_12m_to_months_employed,
    missed_payments_12m_to_months_employed_flag,
    enquiries_6m_to_months_at_address,
    enquiries_6m_to_months_at_address_flag,
    card_utilisation_to_bureau_score,
    card_utilisation_to_bureau_score_flag,
    gross_income_to_net_income,
    gross_income_to_net_income_flag,
    gross_income_to_collateral_value,
    gross_income_to_collateral_value_flag,
    net_income_to_requested_amount,
    net_income_to_requested_amount_flag,
    net_income_to_collateral_value,
    net_income_to_collateral_value_flag,
    expenses_to_existing_instalments,
    expenses_to_existing_instalments_flag,
    expenses_to_requested_amount,
    expenses_to_requested_amount_flag,
    expenses_to_collateral_value,
    expenses_to_collateral_value_flag,
    existing_instalments_to_requested_amount,
    existing_instalments_to_requested_amount_flag,
    existing_instalments_to_collateral_value,
    existing_instalments_to_collateral_value_flag,
    name="derived",
)
