"""Household: dependants and living costs.

Generated by make_bank.py; edit the generator, not this file."""
import math  # noqa: F401

from decider import dag, param, step  # noqa: F401


def expenses_band(expenses: float, low: float = param(1200.0), mid: float = param(8100.0), high: float = param(19200.0)) -> float:
    return float((expenses > low) + (expenses > mid) + (expenses > high))


def expenses_high(expenses: float, threshold: float = param(19200.0)) -> bool:
    return expenses > threshold


def expenses_capped(expenses: float, cap: float = param(57600.0)) -> float:
    return min(expenses, cap)


def expenses_log(expenses: float) -> float:
    return math.log1p(max(expenses, 0.0))


def expenses_zscore(expenses: float, mean: float = param(8100.0), std: float = param(18000.0)) -> float:
    return (expenses - mean) / std


def expenses_above_median(expenses: float, median: float = param(8100.0)) -> bool:
    return expenses > median


def expenses_floor(expenses: float, floor: float = param(1200.0)) -> float:
    return max(expenses, floor)


def dependants_band(dependants: float, low: float = param(11.0), mid: float = param(12.0), high: float = param(18.0)) -> float:
    return float((dependants > low) + (dependants > mid) + (dependants > high))


def dependants_high(dependants: float, threshold: float = param(18.0)) -> bool:
    return dependants > threshold


def dependants_capped(dependants: float, cap: float = param(54.0)) -> float:
    return min(dependants, cap)


def dependants_log(dependants: float) -> float:
    return math.log1p(max(dependants, 0.0))


def dependants_zscore(dependants: float, mean: float = param(12.0), std: float = param(7.0)) -> float:
    return (dependants - mean) / std


def dependants_above_median(dependants: float, median: float = param(12.0)) -> bool:
    return dependants > median


def dependants_floor(dependants: float, floor: float = param(11.0)) -> float:
    return max(dependants, floor)


def requested_term_band(requested_term: float, low: float = param(12.5), mid: float = param(20.2), high: float = param(20.5)) -> float:
    return float((requested_term > low) + (requested_term > mid) + (requested_term > high))


def requested_term_high(requested_term: float, threshold: float = param(20.5)) -> bool:
    return requested_term > threshold


def requested_term_capped(requested_term: float, cap: float = param(61.5)) -> float:
    return min(requested_term, cap)


def requested_term_log(requested_term: float) -> float:
    return math.log1p(max(requested_term, 0.0))


def requested_term_zscore(requested_term: float, mean: float = param(20.2), std: float = param(8.0)) -> float:
    return (requested_term - mean) / std


def requested_term_above_median(requested_term: float, median: float = param(20.2)) -> bool:
    return requested_term > median


def requested_term_floor(requested_term: float, floor: float = param(12.5)) -> float:
    return max(requested_term, floor)


def living_cost_floor(dependants: float, per_adult: float = param(3200.0), per_dependant: float = param(1450.0)) -> float:
    return per_adult + per_dependant * dependants


def expenses_declared_low(expenses: float, living_cost_floor: float) -> bool:
    return expenses < living_cost_floor


def expenses_used(expenses: float, living_cost_floor: float) -> float:
    return max(expenses, living_cost_floor)


household = dag(
    expenses_band,
    expenses_high,
    expenses_capped,
    expenses_log,
    expenses_zscore,
    expenses_above_median,
    expenses_floor,
    dependants_band,
    dependants_high,
    dependants_capped,
    dependants_log,
    dependants_zscore,
    dependants_above_median,
    dependants_floor,
    requested_term_band,
    requested_term_high,
    requested_term_capped,
    requested_term_log,
    requested_term_zscore,
    requested_term_above_median,
    requested_term_floor,
    living_cost_floor,
    expenses_declared_low,
    expenses_used,
    name="household",
)
