"""Income: bands, stability and what is left each month.

Generated by make_bank.py; edit the generator, not this file."""
import math  # noqa: F401

from decider import dag, param, step  # noqa: F401


def gross_income_band(gross_income: float, low: float = param(19200.0), mid: float = param(22800.0), high: float = param(27000.0)) -> float:
    return float((gross_income > low) + (gross_income > mid) + (gross_income > high))


def gross_income_high(gross_income: float, threshold: float = param(27000.0)) -> bool:
    return gross_income > threshold


def gross_income_capped(gross_income: float, cap: float = param(81000.0)) -> float:
    return min(gross_income, cap)


def gross_income_log(gross_income: float) -> float:
    return math.log1p(max(gross_income, 0.0))


def gross_income_zscore(gross_income: float, mean: float = param(22800.0), std: float = param(7800.0)) -> float:
    return (gross_income - mean) / std


def gross_income_above_median(gross_income: float, median: float = param(22800.0)) -> bool:
    return gross_income > median


def gross_income_floor(gross_income: float, floor: float = param(19200.0)) -> float:
    return max(gross_income, floor)


def net_income_band(net_income: float, low: float = param(16000.0), mid: float = param(24000.0), high: float = param(27000.0)) -> float:
    return float((net_income > low) + (net_income > mid) + (net_income > high))


def net_income_high(net_income: float, threshold: float = param(27000.0)) -> bool:
    return net_income > threshold


def net_income_capped(net_income: float, cap: float = param(81000.0)) -> float:
    return min(net_income, cap)


def net_income_log(net_income: float) -> float:
    return math.log1p(max(net_income, 0.0))


def net_income_zscore(net_income: float, mean: float = param(24000.0), std: float = param(11000.0)) -> float:
    return (net_income - mean) / std


def net_income_above_median(net_income: float, median: float = param(24000.0)) -> bool:
    return net_income > median


def net_income_floor(net_income: float, floor: float = param(16000.0)) -> float:
    return max(net_income, floor)


def disposable_income(net_income: float, expenses: float, existing_instalments: float) -> float:
    return net_income - expenses - existing_instalments


def disposable_income_buffered(disposable_income: float, buffer: float = param(0.1)) -> float:
    return disposable_income * (1 - buffer)


income = dag(
    gross_income_band,
    gross_income_high,
    gross_income_capped,
    gross_income_log,
    gross_income_zscore,
    gross_income_above_median,
    gross_income_floor,
    net_income_band,
    net_income_high,
    net_income_capped,
    net_income_log,
    net_income_zscore,
    net_income_above_median,
    net_income_floor,
    disposable_income,
    disposable_income_buffered,
    name="income",
)
