"""Stability: employment, address and age.

Generated by make_bank.py; edit the generator, not this file."""
import math  # noqa: F401

from decider import dag, param, step  # noqa: F401


def age_band(age: float, low: float = param(2.0), mid: float = param(15.8), high: float = param(21.2)) -> float:
    return float((age > low) + (age > mid) + (age > high))


def age_high(age: float, threshold: float = param(21.2)) -> bool:
    return age > threshold


def age_capped(age: float, cap: float = param(63.599999999999994)) -> float:
    return min(age, cap)


def age_log(age: float) -> float:
    return math.log1p(max(age, 0.0))


def age_zscore(age: float, mean: float = param(15.8), std: float = param(19.2)) -> float:
    return (age - mean) / std


def age_above_median(age: float, median: float = param(15.8)) -> bool:
    return age > median


def age_floor(age: float, floor: float = param(2.0)) -> float:
    return max(age, floor)


def months_employed_band(months_employed: float, low: float = param(2.0), mid: float = param(2.8), high: float = param(22.0)) -> float:
    return float((months_employed > low) + (months_employed > mid) + (months_employed > high))


def months_employed_high(months_employed: float, threshold: float = param(22.0)) -> bool:
    return months_employed > threshold


def months_employed_capped(months_employed: float, cap: float = param(66.0)) -> float:
    return min(months_employed, cap)


def months_employed_log(months_employed: float) -> float:
    return math.log1p(max(months_employed, 0.0))


def months_employed_zscore(months_employed: float, mean: float = param(2.8), std: float = param(20.0)) -> float:
    return (months_employed - mean) / std


def months_employed_above_median(months_employed: float, median: float = param(2.8)) -> bool:
    return months_employed > median


def months_employed_floor(months_employed: float, floor: float = param(2.0)) -> float:
    return max(months_employed, floor)


def months_at_address_band(months_at_address: float, low: float = param(1.0), mid: float = param(7.2), high: float = param(10.8)) -> float:
    return float((months_at_address > low) + (months_at_address > mid) + (months_at_address > high))


def months_at_address_high(months_at_address: float, threshold: float = param(10.8)) -> bool:
    return months_at_address > threshold


def months_at_address_capped(months_at_address: float, cap: float = param(32.400000000000006)) -> float:
    return min(months_at_address, cap)


def months_at_address_log(months_at_address: float) -> float:
    return math.log1p(max(months_at_address, 0.0))


def months_at_address_zscore(months_at_address: float, mean: float = param(7.2), std: float = param(9.8)) -> float:
    return (months_at_address - mean) / std


def months_at_address_above_median(months_at_address: float, median: float = param(7.2)) -> bool:
    return months_at_address > median


def months_at_address_floor(months_at_address: float, floor: float = param(1.0)) -> float:
    return max(months_at_address, floor)


def age_years_band(age: float, young: float = param(25.0), mature: float = param(55.0)) -> float:
    return 0.0 if age < young else (2.0 if age >= mature else 1.0)


stability = dag(
    age_band,
    age_high,
    age_capped,
    age_log,
    age_zscore,
    age_above_median,
    age_floor,
    months_employed_band,
    months_employed_high,
    months_employed_capped,
    months_employed_log,
    months_employed_zscore,
    months_employed_above_median,
    months_employed_floor,
    months_at_address_band,
    months_at_address_high,
    months_at_address_capped,
    months_at_address_log,
    months_at_address_zscore,
    months_at_address_above_median,
    months_at_address_floor,
    age_years_band,
    name="stability",
)
